### ISSUE TITLE
https requests leaking memory

### ISSUE THREAD

**Issue by stephenmathieson** [bagder/curl#142]
it looks like even the simplest https requests are leaking memory.

valgrind reports the following example leaves "*43,397 bytes in 947 blocks*" available:

```c

#include <stdio.h>
#include <curl/curl.h>

size_t
callback(void *x, size_t size, size_t nmemb, void *y) {
  return size * nmemb;
}

int
main(){
  CURL *curl;
  long status;

  curl = curl_easy_init();
  if (!curl) return 1;

  curl_easy_setopt(curl, CURLOPT_URL, "https://google.com/");
  curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, callback);
  curl_easy_setopt(curl, CURLOPT_WRITEDATA, NULL);
  curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1);

  curl_easy_perform(curl);
  curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &status);

  printf("%ld\n", status);

  curl_easy_cleanup(curl);
  return 0;
}
```

for more see: https://gist.github.com/stephenmathieson/12647b3caad72be5c911

**Comment by dfandrich** [comment]
On Fri, Feb 27, 2015 at 04:40:59PM -0800, Stephen Mathieson wrote:
> it looks like even the simplest https requests are leaking memory.
> 
> valgrind reports the following example leaves "43,397 bytes in 947 blocks"
> available:

The code doesn't call curl_global_cleanup() which could make a big
difference. The autobuilds show many environments are not leaking memory, so
it's likely something in your environment. If you can still reproduce it,
please include more information on the platform and libraries you're using
including version numbers.

>>> Dan

**Comment by stephenmathieson** [comment]
added `curl_global_cleanup()` which had no effect: https://gist.github.com/stephenmathieson/12647b3caad72be5c911

here's some info on my env:

```
$ uname --all 
Linux precise64 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-werror --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) 
$ curl-config --cc
gcc
$ curl-config --libs
-L/usr/lib/x86_64-linux-gnu -lcurl -Wl,-Bsymbolic-functions -Wl,-z,relro
$ curl-config --version
libcurl 7.22.0
```

let me know if anything else may help

**Comment by bagder** [comment]
Can you please try a recent version and see if it remains? Are you using a recent gnutls version?

**Comment by bagder** [comment]
No feedback, closing. If this can be repeated on a recent version then we re-open!

**Comment by aless673** [comment]
Hi, valgrind gives me an error with installed package **libcurl4-gnutls-dev**

`==24961== Memcheck, a memory error detector
==24961== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==24961== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==24961== Command: ./test
==24961==
==24961== Conditional jump or move depends on uninitialised value(s)
==24961==    at 0x714C8DD: gnutls_session_get_data (in /usr/lib/x86_64-linux-gnu/libgnutls.so.26.22.6)
==24961==    by 0x52BC909: ??? (in /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.3.0)
==24961==    by 0x52BCE19: ??? (in /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.3.0)
==24961==    by 0x52BD8DF: ??? (in /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.3.0)
==24961==    by 0x52817AC: ??? (in /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.3.0)
==24961==    by 0x5290E34: ??? (in /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.3.0)
==24961==    by 0x52A3AA9: ??? (in /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.3.0)
==24961==    by 0x52A4530: curl_multi_perform (in /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.3.0)
==24961==    by 0x529BC92: curl_easy_perform (in /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.3.0)
==24961==    by 0x402019: main (main.c:231)
==24961==  Uninitialised value was created by a stack allocation
==24961==    at 0x52BC1F0: ??? (in /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.3.0)
==24961==
==24961==
==24961== HEAP SUMMARY:
==24961==     in use at exit: 130,209 bytes in 2,841 blocks
==24961==   total heap usage: 382,569 allocs, 379,728 frees, 209,881,515 bytes allocated
==24961==
==24961== LEAK SUMMARY:
==24961==    definitely lost: 0 bytes in 0 blocks
==24961==    indirectly lost: 0 bytes in 0 blocks
==24961==      possibly lost: 0 bytes in 0 blocks
==24961==    still reachable: 130,209 bytes in 2,841 blocks
==24961==         suppressed: 0 bytes in 0 blocks
==24961== Reachable blocks (those to which a pointer was found) are not shown.
==24961== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==24961==
==24961== For counts of detected and suppressed errors, rerun with: -v
==24961== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
`

Same program with **libcurl4-openssl-dev** :+1:  

`==25663== Memcheck, a memory error detector
==25663== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==25663== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==25663== Command: ./test
==25663==
==25663==
==25663== HEAP SUMMARY:
==25663==     in use at exit: 42,136 bytes in 36 blocks
==25663==   total heap usage: 55,299 allocs, 55,263 frees, 159,446,583 bytes allocated
==25663==
==25663== LEAK SUMMARY:
==25663==    definitely lost: 0 bytes in 0 blocks
==25663==    indirectly lost: 0 bytes in 0 blocks
==25663==      possibly lost: 0 bytes in 0 blocks
==25663==    still reachable: 42,136 bytes in 36 blocks
==25663==         suppressed: 0 bytes in 0 blocks
==25663== Reachable blocks (those to which a pointer was found) are not shown.
==25663== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==25663==
==25663== For counts of detected and suppressed errors, rerun with: -v
==25663== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)`

Curl request is done like in this example : http://curl.haxx.se/libcurl/c/getinmemory.html

I investigated and found that the leak occured when https url is used. Only with gnutls.
