### ISSUE TITLE
curl 7.41.1 does not exist

### ISSUE THREAD

**Issue by anisse** [bagder/curl#146]
The latest release and git tag is 7.41.0, but 7.41.1 is referenced on these pages:
http://curl.haxx.se/docs/vulnerabilities.html
http://curl.haxx.se/docs/vuln-7.41.1.html
http://curl.haxx.se/changes.html
http://curl.haxx.se/docs/releases.html

**Comment by bagder** [comment]
Grrr, another typo. Thanks for pointing this out, should be fixed now!

**Comment by anisse** [comment]
Wow, that was fast! Thanks !
