### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [bagder/curl#148]
I would like to point out that identifiers like "[`__CURL_CURLVER_H`](https://github.com/bagder/curl/blob/4aa9bb6b13c3af90e8129758057bf34d18c916ed/include/curl/curlver.h#L1)" and "[`__CURL_MULTI_H`](https://github.com/bagder/curl/blob/19122c07682c268c2383218f62e09c3d24a41e76/include/curl/multi.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/seccode/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by bagder** [comment]
This is not a problem in the real world though. libcurl is more portable than most projects and we've had such identifiers for at least 15 years. If someone brings a patch for it then I'll merge but I don't think it is worth wasting many cycles on.

**Comment by elfring** [comment]
Would you like to achieve that your source files will become standard-compliant?
