### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [bagder/curl#150]
I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.

Would you like to add more error handling for return values from functions like the following?
- [fseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html "Reposition a file-position indicator in a stream.") ⇒ [vms_realfilesize](https://github.com/bagder/curl/blob/c715fa0b60c86449e09b313245de621b32e329d2/src/tool_operate.c#L135)
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [new_metalink_resource](https://github.com/bagder/curl/blob/709cf76f6bb7dbaca14e3e8df160ccfac04dcecb/src/tool_metalink.c#L688)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [parse_cert_parameter](https://github.com/bagder/curl/blob/c715fa0b60c86449e09b313245de621b32e329d2/src/tool_getparam.c#L278)

**Comment by bagder** [comment]
vms_realwfilesize() doesn't have any fseek calls. I assume you mean the ones in operate_do(). I consider them mostly harmless. The same goes for the parse_cert_parameter strdups.

The metalink function was improved slightly in commit 3ac3331e.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by bagder** [comment]
Can you identify any actual problems or bugs due to your discoveries? Can you submit a patch with your suggested fixes?

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for your software?

Do you find information sources like the following useful?
* Article "[A Reusable Aspect for Memory Allocation Checking](http://aspectc.net/ac_tutorial.html#reusablemachecking "AspectC Tutorial")"
* Document "[Aspect-Oriented Software Development - An Introduction](http://www.info.ucl.ac.be/~jbrichau/courses/introductionToAOSD.pdf "AOSD")" by Johan Brichau and Theo D'Hondt
* Paper "[On Typesafe Aspect Implementations in C++](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.125.2164 "AspectC++")" by Daniel Lohmann and Olaf Spinczyk

**Comment by bagder** [comment]
Does that mean you can't identify a problem or provide a patch?

**Comment by evert** [comment]
No, he wants to have a long-winded argument about software architecture!

**Comment by elfring** [comment]
The suggested tools can help to transform source code in various ways.
Which transformations are acceptable for you to be performed by another software tool automatically?

**Comment by bagder** [comment]
No bug then. Closed.
