### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [bagder/curl#151]
Would you like to add the configuration script "[AX_PTHREAD](http://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads?")" to [your build specification](https://github.com/bagder/curl/blob/492dfca65d0147f2920b38d724186fdf39b2541b/configure.ac#L3142 "Configuration checks")?

**Comment by bagder** [comment]
Why would we do that?

**Comment by elfring** [comment]
How do you think about to prepare also your software for variations around the parameter "`-lpthread`" which is referenced in the build script?

**Comment by bagder** [comment]
When you're suggesting these things I think you should consider providing us with clear motivations or explanations why. As far as I know, our pthread configure tests work good enough. Are you of a different opinion?

**Comment by elfring** [comment]
Do you get any more ideas from comments in the suggested configuration script?
Can it help to reuse known checks?

**Comment by bagder** [comment]
Help in which way? What problem are you trying to solve?

**Comment by elfring** [comment]
How do you think about to improve portability also for your software around Pthread build parameters?

**Comment by bagder** [comment]
"Improve" implies there's a problem now. If you can't point out a problem there's nothing to improve here!

**Comment by elfring** [comment]
Would you like to get benefits from the GNU Autoconf Archive?

**Comment by bagder** [comment]
Not bug. Closing.
