### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [bagder/curl#153]
The function "[siglongjmp](http://pubs.opengroup.org/onlinepubs/9699919799/functions/siglongjmp.html "non-local goto with signal handling")" does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I guess that a different program design will be needed for your function "[alarmfunc](https://github.com/bagder/curl/blob/df5578a7a304a23f9aa3670daff8573ec3ef416f/lib/hostip.c#L528 "Reconsider signal handling implementation")".

**Comment by bagder** [comment]
This is sort of a known issue that nobody seems very keen at fixing, and most users seem to like one of the non-blocking resolver backends these days, If you want to work on this we'll be happy, otherwise I think it will be closed soon as not fixed.
