### ISSUE TITLE
Closed connection not reported as error in cleartext HTTP2 upgrade

### ISSUE THREAD

**Issue by bdarnell** [bagder/curl#166]
I'm using the multi interface to fetch an HTTP url with CURLOPT_HTTP_VERSION set to CURL_HTTP_VERSION_2 (so HTTP2 is not actually in use; it's an HTTP1 request with an upgrade header). If the server closes the socket without sending a response, this is not reported as an error (curl_multi_info_read returns a result of CURLE_OK). Without setting CURLOPT_HTTP_VERSION it correctly reports CURLE_PARTIAL_FILE.

Versions: libcurl 7.41.0 and nghttp2 0.7.5 on OSX

**Comment by bagder** [comment]
Thanks, I can repeat it too...

**Comment by bagder** [comment]
Fixed now in commit 0cf649d9c. Thanks a lot, case closed!
