### ISSUE TITLE
does not create empty files with -o

### ISSUE THREAD

**Issue by joeyh** [bagder/curl#183]
I'd expect curl -o to always create the specified file, if the url download succeeded. This consistency means it's easy to use it in a script; run curl, check its exit status and if it succeeded, the url content is there in the file to be used. And it just seems to make sense. But, reality is different when downloading an url that happens to be empty:

joey@darkstar:~>curl -o hello http://tmp.kitenet.net/empty
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:-  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:-  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
joey@darkstar:~>cat hello
cat: hello: No such file or directory

This behavior is not documented on the man page either. So you have either a behavior bug (IMHO) or at least a documentation bug.

I'm using curl 7.38.0.

**Comment by bagder** [comment]
It certainly works like this on purpose, it is not a mistake. The documentation should probably be clarified to make this less surprising.

The idea is to not create a file in case of errors so it creates the file on demand when the first data arrives. But if no data ever arrives...

**Comment by joeyh** [comment]
Daniel Stenberg wrote:
> It certainly works like this on purpose, it is not a mistake. The documentation
> should probably be clarified to make this less surprising.
> 
> The idea is to not create a file in case of errors so it creates the file on
> demand when the first data arrives. But if no data ever arrives...

Seems like you could create the file once the data transfer is complete,
if it's not been created already on demand. I think that would be better
than documenting a complicating special case.

-- 
see shy jo

**Comment by kdudka** [comment]
The current behavior sounds counter-intuitive to me, too.  I would expect that successful download of a remote empty file results in a local empty file.

**Comment by bagder** [comment]
I wouldn't mind having it create the file if it ends successfully!

**Comment by bagder** [comment]
@joeyh feel like making a patch for it?

**Comment by kdudka** [comment]
I have proposed a patch for this on the mailing-list:

http://thread.gmane.org/gmane.comp.web.curl.library/45327/focus=45328

**Comment by kdudka** [comment]
I have merged the fix for this issue: https://github.com/bagder/curl/compare/a9e46749b2...992a731116
