### ISSUE TITLE
Windows build for nghttp2 supported?

### ISSUE THREAD

**Issue by remoe** [bagder/curl#184]
I've tried to build curl with nghttp2 on windows x64:

https://github.com/tatsuhiro-t/nghttp2/issues/195

Currently, it's not really possible to build CURL with nghttp2 support without build modifications?

And I don't know what are the "official" way to build CURL for windows:

- nmake /f Makefile.vc mode=dll ...
- SLN files in projects folder
- cmake

?

Thanks

**Comment by bagder** [comment]
They're all official but yeah at some point we will reduce the number of options. The nmake versions in the root dir is probably the one most likely to get ditched first.

Otherwise we're a bit short on people working on windows and I'm not sure anyone has built http2 support with MSVC previously. Feel free to use your own preferred method and add http2 support to it!

**Comment by remoe** [comment]
ok, thanks for this explanation.

**Comment by TDannhauer** [comment]
Hmm sad, it's still not possible to build curl with nghttp2 on windows.

**Comment by bagder** [comment]
It is still very much possible as lots of people already do it since a long time back. I assume you're talking about lack of support in some specific build files? If so, we do welcome patches and help to fix remaining problems.

**Comment by TDannhauer** [comment]
sorry, I meant out of the box.

Cmake warns to be poorly maintained and failed in configuring 
winbuild does not support an out-of -the -switch build. 
installing cygwin or MinGW is not an option.

So what is the preferred way to compile curl  with http2 using MSVC?

**Comment by bagder** [comment]
cmake support for nghttp2 builds is discussed in #922 

I think most people who build curl with nghttp2 on windows use msys/mingw, but I'm not sure. I'm not on windows myself.

So again: it works for some build setups, just not all. And possibly not the one you want to use.

**Comment by TDannhauer** [comment]
OK thanks,
Than I readjust my statement to : "It's sad that it is still not possible to build curl with http2 support out of the box using MSVC with the latest stable release" ;)

Curl is not my main focus so I can't invest lots of time to integrate http2 support in windows. So I will ship curl with http 1 support only.

Anyway: Good work and very clean project structure when buijlding curl form sources. Great job!
Thanks,
Torben

**Comment by remoe** [comment]
@bagder i never use a msys/mingw environment for a real windows build :) 
My branch #922 should be ready for another test.
