### ISSUE TITLE
CyaSSL has changed their code-base to reflect company name wolfSSL

### ISSUE THREAD

**Issue by kaleb-himes** [bagder/curl#188]
I can send you a .patch file with relevant changes. Please contact me at kaleb@wolfssl.com and I will forward you the patch we used for updating our version of curl.

-Regards,

Kaleb Himes

**Comment by kaleb-himes** [comment]
I have pushed the patch to this repo if you want to grab from there:

https://github.com/kaleb-himes/curl_wolfssl_patch

**Comment by bagder** [comment]
Please make it a proper pull request or send the patch to the mailing list.

Also, the configure script is generated so there's no point in editing that.

**Comment by jay** [comment]
By keeping cyassl in most places though we have that backwards compatibility. Some changes were made already by Dan Fandrich (7868dc7, 9a743bc, maybe others) to use the wolfSSL name when appropriate. I made some changes as well. I'm sure there are other places though. If I were you I'd pull from master and propose changes based on that.

**Comment by bagder** [comment]
Due to this partial out-of-date situation, I'm closing this and hope for a refreshed version.
