### ISSUE TITLE
multi_addtimeout is too slow!

### ISSUE THREAD

**Issue by waruqi** [bagder/curl#216]
hi!

I found multi_addtimeout was too slow when calling the following function:

curl_multi_perform
- multi_runsingle
   - Curl_resolver_is_resolved
     - Curl_expire
       - multi_addtimeout
         - curlx_tvdiff

Why do not use the min-heap or red-black tree to manage the timeout tasks?

**Comment by bagder** [comment]
What exactly is "too slow" to you? How slow is it? How does it become a problem for you?

**Comment by bagder** [comment]
I assume you refer to the 7.41.0 version of the code?

**Comment by waruqi** [comment]
I found this problem when I was analyzing performance of other ios application.

I am sorry I can not known the version because I have only one binary file.

**Comment by waruqi** [comment]
libcurl 7.37.0

**Comment by bagder** [comment]
Commit cacdc27f52ba is probably what you'd like, which greatly reduces the number of (superfluous) timeouts that were added. The function were only slow because it could end up adding hundreds of thousands of timeouts that shouldn't be there in the first place. Please upgrade.
