### ISSUE TITLE
Choose the name of file in braces for complex URLs

### ISSUE THREAD

**Issue by rodrigozanatta** [bagder/curl#221]
When using some trick to download various URLs with braces {}, there is a bug in cURL because or you can save using the URL part in braces as names or choose only one name. The problem is if if the names in braces are complex.

I would like to suggest the ability to configure the name inside the braces. Today we have this grammar:

* {partURL1,partURL2,partURL3}

and I suggest use this (*can the cURL use the : as separator?*)

* {partURL1**:name1**,partURL2**:name2**,partURL3**:name3**}
* {partURL1**:name1**,partURL2,partURL3}
  - *partURL1* will use the **name1** and the others will use partURL2 and partURL3 as name

So the command 
>curl --url 'http://www.google.com/{various:first,complex,names:third}' --output 'name_#1.html'

will produce:

**http://www.google.com/various** and save in **name_first.html**
**http://www.google.com/complex** and save in **name_complex.html** (*I don't send the name, use the part URL as default*)
**http://www.google.com/names**   and save in **name_third.html**

**Comment by bagder** [comment]
This isn't a bug, this is an idea on how to improve curl in the future. It belongs in the TODO file, and I've now added it there in commit 1ba6e4c8. Closing this issue.
