### ISSUE TITLE
Windows projects' .gitignore should not exclude vcxproj files

### ISSUE THREAD

**Issue by matthauck** [bagder/curl#222]
For example, in projects/Windows/VC11/lib, the solution files do not have a corresponding project vcxproj file -- these solution files fail to open. Downloading the zip for the release, however, from http://curl.haxx.se/download.html, does indeed properly include these project files. 

The `.gitignore`s in there are excluding these on purpose, which it probably shouldn't be doing.

**Comment by jay** [comment]
Thanks for your report. From projects/README:

> If you are using the source code from the git repository, rather than a release archive or nightly build, you will need to generate the project files. Please run "generate -help" for usage details. 

So .gitignore should be excluding these files.

**Comment by matthauck** [comment]
Ah ok. My mistake. Thanks!
