### ISSUE TITLE
curl_version_info.3 documentation missing "const" for protocols field

### ISSUE THREAD

**Issue by jmarshall** [bagder/curl#225]
Rather minor, but… the `curl_version_info.3` man page documents the `curl_version_info_data` struct's fields, including

    const char **protocols;   /* list of protocols */

However `protocols` is in fact a `const char * const *` — which makes a difference when user code is declaring a variable to traverse the list.

**Comment by bagder** [comment]
Thanks a lot, fixed now in 63c64e05a449
