### ISSUE TITLE
CURLOPT_HEADERFUNCTION manpage: mixes "ptr" and "buffer"

### ISSUE THREAD

**Issue by bsammon** [bagder/curl#229]
in the manpage for CURLOPT_HEADERFUNCTION, the "SYNOPSIS" section refers to the "buffer" parameter, but the "DESCRIPTION" section refers to "ptr".

I think those two things are referring to the same thing?

**Comment by bagder** [comment]
Thanks a lot, fixed in git now. Should appear on the site momentarily. Cased closed!
