### ISSUE TITLE
Compilation fails on 7.42.0 when USE_NTLM is not defined

### ISSUE THREAD

**Issue by prapin** [bagder/curl#231]
On the 7.42.0 release out of the box, if USE_NTLM is not defined (typically we don't have any SSL library available), compilation fails on line 3212 of url.c because trying to access member 'ntlm' which is only defined when USE_NTLM is on.

**Comment by bagder** [comment]
Fix landed in commit fd9d3a1ef1f7b1c, thanks!

**Comment by bagder** [comment]
Even if I wrote the bug URL wrong in the commit message :-(
