### ISSUE TITLE
building 7.42

### ISSUE THREAD

**Issue by aguasonic** [bagder/curl#233]
Building on:

3.16.0-34-generic #47-Ubuntu SMP Fri Apr 10 18:02:58 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
=================================================================================
url.c: In function 'ConnectionExists':
url.c:3212:32: error: 'struct connectdata' has no member named 'ntlm'
          (wantNTLMhttp || check->ntlm.state != NTLMSTATE_NONE)) {
                                ^
Makefile:1197: recipe for target 'libcurl_la-url.lo' failed

**Comment by kdudka** [comment]
Thanks for the report!  This has already been reported (and fixed) as #231.
