### ISSUE TITLE
getinfo with OpenSSL backend - No connection information available

### ISSUE THREAD

**Issue by dkjjr89** [bagder/curl#234]
My understanding of OpenSSL (granted is limited) is that with a connection structure you can obtain the context that created the connection.  I am not aware of a way to obtain an existing connection from a context structure.  In version libcurl 7.41.0 I changed line 310 of lib/getino.c from:

    internals = conn->ssl[sockindex].ctx;

To:

    internals = conn->ssl[sockindex].handle;

**Comment by bagder** [comment]
This may be the right thing to do, yes. It also struck me that since we do not at all document what sort of internal handle you get back, no application can reliably use this anyway. We should fix that too.

**Comment by bagder** [comment]
I took the question to the list just to see if there's anyone with thoughts (like for example Christian who brought the feature initially): http://curl.haxx.se/mail/lib-2015-04/0149.html

**Comment by bagder** [comment]
I'm reluctant to change the existing code since it has been like this for a while already and there may be apps using it.

**Comment by dkjjr89** [comment]
I understand.  Thanks!

**Comment by jay** [comment]
@dkjjr89 I've added `CURLINFO_TLS_SSL_PTR` which should do what you want, please see 332414a. The option name is subject to change. Barring anything unforeseen it will be in the next version of curl, 7.48.0.
