### ISSUE TITLE
Long certificate serial number with OpenSSL backend is null

### ISSUE THREAD

**Issue by dkjjr89** [bagder/curl#235]
In lib/vtls/openssl/c in version 7.41.0 at line 2466 we have:

      ptr = bufp;
      *ptr++ = 0;
      if(num->type == V_ASN1_NEG_INTEGER)
        *ptr++='-';

      for(j=0; (j<num->length) && (left>=4); j++) {
        /* TODO: length restrictions */
        snprintf(ptr, 3, "%02x%c",num->data[j],
                 ((j+1 == num->length)?'\n':':'));
        ptr += 3;
        left-=4;

Since bufp gets pushed to return a certificate serial number setting the first character to null will always cause null to be returned, therefore, line 2477 should be removed.  The snprintf call attempts to create a colon separated string but just the hexadecimal value is being inserted.  Also, I could not locate documentation that says the serial number should be colon separated.  To get long serial numbers returned from the library I changed the above block to:

      ptr = bufp;
      if(num->type == V_ASN1_NEG_INTEGER)
        *ptr++='-';

      for(j=0; (j<num->length) && (left>=3); j++) {
        /* TODO: length restrictions */
        snprintf(ptr, 3, "%02x",num->data[j]);
        ptr += 2;
        left-=2;

Hope this helps!

**Comment by bagder** [comment]
Thanks! I wrote up a slightly modified fix but based on your report and hints here. Landed in aff153f83a.

**Comment by dkjjr89** [comment]
Thank you!

**Comment by jay** [comment]
For other octets retrieved via CURLINFO_CERTINFO like rsa and signature a colon is used as the separator for each octet. I'm not sure why not for serial number. OpenSSL in their output uses the colon as a separator but only for long serial numbers (see openssl x509 -noout -text -in cert). I don't see why not do it that way for all. Though changing it to be consistent with the others at this point may break a user's parsing of it.

Another thing that looks strange in that area is output of negative serial numbers. The current way is to prefix the octets with - to designate negative direction (a la integer). but [the way OpenSSL does it](https://github.com/openssl/openssl/blob/a0eed48/crypto/asn1/a_int.c#L90-L113) looks more correct.. although again any change at the point may break a user's parsing.

**Comment by bagder** [comment]
@jay changing it could still be safe as it was completely broken before and thus was never parsed successfully anyway! I can see how matching openssl's output could be valuable.

I also glanced over the negative thing before I ignored it but you're right, we should make sure to output the same serial number that openssl does, even when negative.

**Comment by jay** [comment]
Ok. If you have no objections I'll replace that block with `i2c_ASN1_INTEGER`.

**Comment by bagder** [comment]
No objection at all!

**Comment by jay** [comment]
They're not using `i2c_ASN1_INTEGER`, for the output. I assumed they were based on what I was reading. Mistake! I should've tested the output of a large negative serial number to be sure. I created a cert with a serial of -999,999,999,999,999,999,999:
```
openssl req -config openssl.cnf -x509 -newkey rsa:2048 -keyout serial_number_negative_nines.key -out serial_number_negative_nines.crt -days 3650 -nodes -batch -set_serial -999999999999999999999 -subj /CN=localhost/
openssl x509 -noout -text -in serial_number_negative_nines.crt
```
Here's the relevant part of their x509 output, which comes from [X509_print_ex](https://github.com/openssl/openssl/blob/a0eed48/crypto/asn1/t_x509.c#L137-L164):
```
        Serial Number:
             (Negative)36:35:c9:ad:c5:de:9f:ff:ff
```
And if I specify -serial it also shows `serial=-3635C9ADC5DE9FFFFF`. So I guess there is some basis. A smaller number that fits in a long like -2000 shows `Serial Number: -2000 (-0x7d0)` and `serial=-07D0`. 

What libcurl is doing right now is the same as the OpenSSL 'serial' format, not the OpenSSL 'Serial Number' format. That's probably fine given that nobody's used it yet, but if you want I can change it to their 'Serial Number' format as seen in X509_print_ex. libcurl had something [similar](https://github.com/bagder/curl/blob/cc628cd/lib/vtls/openssl.c#L2475-L2479) to that for small numbers prior to your change but it would have to be modified to take into account negative numbers.

So it doesn't look like much of an issue anymore. Shame, the i2c method still looks more correct to me and easier to parse!
