### ISSUE TITLE
SSL through proxy header leak

### ISSUE THREAD

**Issue by catnip2** [bagder/curl#236]
sending a request to an https:// host via a proxy leaks headers, including sensitive infromation like cookies:
# curl -v "https://www.google.com/" --proxy 127.0.0.1:8484 -H 'Cookie: a=b'
* About to connect() to proxy 127.0.0.1 port 8484
*   Trying 127.0.0.1... connected
* Connected to 127.0.0.1 (127.0.0.1) port 8484
* Establish HTTP proxy tunnel to www.google.com:443
> CONNECT www.google.com:443 HTTP/1.0
> Host: www.google.com:443
> User-Agent: Mozilla/5.0 (Windows NT 5.1; rv:28.0) Gecko/20100101 Firefox/28.0
> Proxy-Connection: Keep-Alive
> Cookie: a=b

# nc -l 8484 -k
CONNECT www.google.com:443 HTTP/1.0
Host: www.google.com:443
User-Agent: Mozilla/5.0 (Windows NT 5.1; rv:28.0) Gecko/20100101 Firefox/28.0
Proxy-Connection: Keep-Alive
Cookie: a=b

this seems like a security concern, curl should only send the HTTPHEADERS through the tunnel after it's established - not to the proxy itself

**Comment by bagder** [comment]
You do NOT submit security related issues in a public bug tracker. This puts us in a very unfortunate and undesired position. In this case, this is in fact a known issue that we're already working on.

Send security related problems by email to curl-security@haxx.se and we work them out without the public eye until we have a remedy and solution to spare users and minimize the impact of the problem.

I'm closing this now primarily to limit the exposure, but the cat is already out of the bag...
