### ISSUE TITLE
Curl 7.42.0 build regression when ssl is disabled

### ISSUE THREAD

**Issue by ezegomez** [bagder/curl#238]
./configure --enable-shared=no --disable-threaded-resolver --enable-debug --disable-curldebug --enable-optimize --disable-ipv6 --disable-ftp --disable-file --disable-ldap --disable-ldaps --disable-rtsp --disable-dict --disable-telnet --disable-tftp --disable-pop3 --disable-imap --disable-smtp --disable-gopher --disable-manual --disable-sspi --disable-cookies --disable-ntlm-wb --without-ca-bundle --without-ca-path --without-ssl --without-gnutls --without-nss --without-zlib --without-libidn

libtool: compile:  gcc -DHAVE_CONFIG_H -I../include/curl -I../include -I../include -I../lib -I../lib -DBUILDING_LIBCURL -DCURL_STATICLIB -DCURL_HIDDEN_SYMBOLS -DDEBUGBUILD -fvisibility=hidden -g -O2 -pedantic -Wall -W -Wpointer-arith -Wwrite-strings -Wunused -Wshadow -Winline -Wnested-externs -Wmissing-declarations -Wmissing-prototypes -Wno-long-long -Wfloat-equal -Wno-multichar -Wsign-compare -Wundef -Wno-format-nonliteral -Wendif-labels -Wstrict-prototypes -Wdeclaration-after-statement -Wstrict-aliasing=3 -Wno-system-headers -MT libcurl_la-url.lo -MD -MP -MF .deps/libcurl_la-url.Tpo -c url.c  -fPIC -DPIC -o libcurl_la-url.o
url.c: In function 'ConnectionExists':
url.c:3212: error: 'struct connectdata' has no member named 'ntlm'
make[2]: *** [libcurl_la-url.lo] Error 1

  curl version:     7.42.0
  Host setup:       x86_64-unknown-linux-gnu
  Install prefix:   /usr/local
  Compiler:         gcc
  SSL support:      no      (--with-{ssl,gnutls,nss,polarssl,cyassl,axtls,winssl,darwinssl} )
  SSH support:      no      (--with-libssh2)
  zlib support:     no      (--with-zlib)
  GSS-API support:  no      (--with-gssapi)
  TLS-SRP support:  no      (--enable-tls-srp)
  resolver:         default (--enable-ares / --enable-threaded-resolver)
  IPv6 support:     no      (--enable-ipv6)
  Unix sockets support: enabled
  IDN support:      no      (--with-{libidn,winidn})
  Build libcurl:    Shared=no, Static=yes
  Built-in manual:  no      (--enable-manual)
  --libcurl option: enabled (--disable-libcurl-option)
  Verbose errors:   enabled (--disable-verbose)
  SSPI support:     no      (--enable-sspi)
  ca cert bundle:   no
  ca cert path:     no
  LDAP support:     no      (--enable-ldap / --with-ldap-lib / --with-lber-lib)
  LDAPS support:    no      (--enable-ldaps)
  RTSP support:     no      (--enable-rtsp)
  RTMP support:     no      (--with-librtmp)
  metalink support: no      (--with-libmetalink)
  HTTP2 support:    disabled (--with-nghttp2)
  Protocols:        HTTP

Seems to have been triggered by the security fixes in this release not being under proper inclusion guards. Compiles properly just removing without-ssl.

**Comment by bagder** [comment]
Fixed already, you can cherry-pick commit fd9d3a1ef1f7b1cb5 and 85c45d153b901.

We will also do a 7.42.1 release next week that will include this fix.
