### ISSUE TITLE
curl -z -o appears to be broken

### ISSUE THREAD

**Issue by tempoz** [bagder/curl#240]
I updated curl on ArchLinux this morning, and my script which uses curl -z and -o appears to be broken. It now replaces the file passed to -o with an empty file if the file I ask for is older than the file I pass to -z, as opposed to the old behavior, which left the file passed to -o in place.

**Comment by jay** [comment]
Thanks for your report. This is a duplicate of #237 and fixed in 7.43.1 which will be released this week.

**Comment by jay** [comment]
s/7.43.1/7.42.1

**Comment by tempoz** [comment]
Haha, thank you very much for your quick reply.
