### ISSUE TITLE
[linux] curl 7.42 causes vmware to crash

### ISSUE THREAD

**Issue by quasifilmie** [bagder/curl#251]
Description:

Checking for updates in Vmware causes the program to crash with the 
new version of curl. Downgrading to curl 7.41 is temporary solution. 

Steps to reproduce

1. Install Vmware Workstation 11.1
2. Install curl 7.42
3. Start vmware, go to help > software updates

Vmware almost immediately crashes when checking for updates.

Relevant link to someone reporting similar crash: http://osdir.com/ml/blfs-support/2015-04/msg00079.html

I am using Arch Linux 64-bit with Linux 4.0.1

Curl 7.42.1 reproduces the same results as 7.42

Downstream: https://bugs.archlinux.org/task/44783

EDIT: can't figure out how to attach files on this. But i attached a log of the vmware crashes in the Arch Linux bug-tracker.

**Comment by dfandrich** [comment]
Here's the backtrace copied from that log file:

*** Error in `/usr/lib/vmware/bin/vmware': free(): invalid pointer: 0x00007fd488940330 ***
======= Backtrace: =========
/usr/lib/libc.so.6(+0x71bad)[0x7fd4855fbbad]
/usr/lib/libc.so.6(+0x770fe)[0x7fd4856010fe]
/usr/lib/libc.so.6(+0x778db)[0x7fd4856018db]
/usr/lib/vmware/lib/libcrypto.so.1.0.1/libcrypto.so.1.0.1(CRYPTO_free+0x1d)[0x7fd4841791cd]
/usr/lib/libssl.so.1.0.0(SSL_CTX_set_alpn_protos+0x1d)[0x7fd47737042d]
/usr/lib/libcurl.so.4(+0x54165)[0x7fd477a53165]
/usr/lib/libcurl.so.4(+0x572c0)[0x7fd477a562c0]
/usr/lib/libcurl.so.4(+0x11c2d)[0x7fd477a10c2d]
/usr/lib/libcurl.so.4(+0x221e1)[0x7fd477a211e1]
/usr/lib/libcurl.so.4(+0x35866)[0x7fd477a34866]
/usr/lib/libcurl.so.4(+0x36834)[0x7fd477a35834]
/usr/lib/libcurl.so.4(curl_multi_socket_action+0x17)[0x7fd477a35947]
/usr/lib/vmware/lib/libcds.so/libcds.so(+0x1b537)[0x7fd4756c0537]
/usr/lib/vmware/lib/libvmwareui.so.0/libvmwareui.so.0(+0x988bfa)[0x7fd47455cbfa]
/usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x15d)[0x7fd48478d90d]
/usr/lib/libglib-2.0.so.0(+0x49ce0)[0x7fd48478dce0]
/usr/lib/libglib-2.0.so.0(g_main_loop_run+0xc2)[0x7fd48478e002]
/usr/lib/libgtk-x11-2.0.so.0(gtk_main+0xb7)[0x7fd47a550467]
/usr/lib/vmware/lib/libvmware.so/libvmware.so(main+0x59)[0x7fd4735f96b9]
/usr/lib/vmware/bin/vmware(main+0x7f7)[0x7fd4863b35c7]
/usr/lib/libc.so.6(__libc_start_main+0xf0)[0x7fd4855aa790]
/usr/lib/vmware/bin/vmware(+0x15ce9)[0x7fd4863b2ce9]

The relevant call (in ossl_connect_step1()) was changed in curl-7.42.0 (commit 2e9494b1) so this does look pretty suspicious. Does it work if you revert that commit?

**Comment by quasifilmie** [comment]
I am not familiar with using git. I have tried doing 

git format-patch -1 <sha1sum>

and

git revert <sha1sum>

If you give me or show me how to make patch file by reverting that commit, I can work with that.

**Comment by bagder** [comment]
"git format-patch -1 sha1sum 2e9494b" will make you a patch for that specific commit. You can then use that to apply (reversed) on a source tree to revert it.

If you build from a git checkout, you can just clone the git tree, then do "git revert 2e9494b" and build everything and you'll have the master tree with that commit reverted.

**Comment by bagder** [comment]
Can you tell us the exact OpenSSL version you're using?

**Comment by quasifilmie** [comment]
I am using openssl version 1.0.2a.  https://www.archlinux.org/packages/core/x86_64/openssl/

VMware does not crash after reverting the commit.  Thanks for the help badger!

**Comment by bagder** [comment]
I'm afraid that just reverting that commit is not an option for us in general though, so I cannot consider this to be a fix for the problem. Only a crude work-around.

The symbol names in your stack trace say 1.0.0 and 1.0.1, are you *sure* this is using 1.0.2?

**Comment by quasifilmie** [comment]
Sorry for the delayed response. Yes I am sure.

**Comment by falconindy** [comment]
There's still a potential version mismatch -- notice that libcrypto is being pulled from some internal VMware directory, but libssl comes from the system.

**Comment by bagder** [comment]
That, and they have different SO numbers: 1.0.0 vs 1.0.1 that looks highly unusual. Without further "evidence", I consider this crash the result of a local setup confusion rather than an actual libcurl bug.

**Comment by fastcat** [comment]
I hit a problem like this too.  In my case, the issue was the OS upgrade from OpenSSL 1.0.1 to 1.0.2, and like the report here, vmware is bizarrely loading half of openssl from its directories and half from the OS, even though it has all of it available in a coherent version in its directory.

**Comment by bagder** [comment]
Presumed user-error
