### ISSUE TITLE
build static mode, but use /md option in winbuild

### ISSUE THREAD

**Issue by tryy** [bagder/curl#254]
MakefileBuild.vc line 239
# Runtime library configuration
!IF "$(RTLIBCFG)"=="static"
RTLIB = /MT
RTLIB_DEBUG = /MTd
!ELSE
RTLIB = /MD
RTLIB_DEBUG  = /MDd
!ENDIF

RTLIBCFG is not exist.
it's look like a bug.

**Comment by rhuijben** [comment]
You can pass that variable to NMake to change the configuration. By default it would be "", which is not "static".

**Comment by jay** [comment]
It's probably that even if you build libcurl static you'll be using a Microsoft C RunTime (CRT) DLL. Usually the static CRT runtime isn't recommended. The CRT DLLs are updated by Microsoft Update for security and stability. You're better off using the CRT DLLs. Still, that option is undocumented and it might be good to document it somewhere.

**Comment by bagder** [comment]
In general we should reduce the number of ways to build on/for windows. Then it'd also be easier to document the procedure...

**Comment by jay** [comment]
> In general we should reduce the number of ways to build on/for windows. Then it'd also be easier to document the procedure...

@bagder I'm reluctant to rock the boat on that. What's that famous saying... easy to add, hard to take away...

@rhuijben Thanks, fixed in f010f3e.
