### ISSUE TITLE
Minor typo in excellent curl tutorial...

### ISSUE THREAD

**Issue by fredstluka** [bagder/curl#255]
I found a minor typo in the excellent curl tutorial at:
- http://curl.haxx.se/docs/manual.html

Wrong:  Alas, to both read and write cookies ...
Right:  Also, to both read and write cookies ...

Thanks for this incredibly useful tool!

--Fred Stluka
fred@bristle.com

**Comment by bagder** [comment]
Thanks, fixed in fa08362a

**Comment by fredstluka** [comment]
Wow!  Fastest bug fix ever!

--Fred
