### ISSUE TITLE
NTLM loops when connection persistence is not available

### ISSUE THREAD

**Issue by frenche** [bagder/curl#256]
Hi,

The following 'curl' command is doomed to fail since NTLM requires a persistent connection to complete the negotiation.

```
# curl http://my.host.com/ -v -0 -u usera:passa --ntlm
...
curl: (47) Maximum (50) redirects followed
```

I think we could be more graceful, this commit fixes it for me:
https://github.com/frenche/curl/commit/e0db49acf1b0305aebe985204cc727661acf3942

I can do a pull request if it is fine.
And as soon as I understand how to to it properly :)

Thanks,
Isaac B.

**Comment by michael-o** [comment]
How is NTLM supposed to work where you cannot persist over the connection?

**Comment by frenche** [comment]
It is supposed to fail as authentication-failed (and return 401 and content to the app).
Looping and then failing on max-redirects doesn't sound the best way to handle it.

**Comment by michael-o** [comment]
Now I see, you have enabled HTTP 1.0, right? Why should this fail if the server sends a keep-alive?

**Comment by frenche** [comment]
On Tue, May 5, 2015 at 9:55 PM, Michael Osipov <notifications@github.com>
wrote:

> Now I see, you have enabled HTTP 1.0, right? Why should this fail if the
> server sends a keep-alive?
>
>
> - Yes (that's the '-0').
- Not sure, but I think client has to request keep-alive first.

Anyway, the suggested code verifies after fact if the connection is getting
close while negotiating and fails auth (so there was no keep-alive, maybe
better to also check that keep-alive aren't supported so if the connection
was closing for a different reason we should restart auth as it may
succeed).

Thanks.

**Comment by michael-o** [comment]
Here is the deal: http://en.wikipedia.org/wiki/HTTP_persistent_connection#HTTP_1.0

Pretty non-standard :-1:

**Comment by frenche** [comment]
Not sure I understand what you mean by the last comment.

**Comment by michael-o** [comment]
I referred to this

> Under HTTP 1.0, there is no official specification for how keepalive operates

**Comment by bagder** [comment]
@michael-o I think that is beside the point, I believe @frenche's case should still be handled better than looping like crazy and his patch is probably a good step in the right direction.

**Comment by frenche** [comment]
@michael-o note that I've encounter this in prod not in lab testings.
I think it's important to cover such edge cases even though it is becomes tedious sometimes.

@bagder any specific additional steps in mind?

Thanks!

**Comment by bagder** [comment]
@frenche well, a gold star would be handed out if you'd accompany the patch with a test case! =)

**Comment by frenche** [comment]
Hi,

On Sun, May 10, 2015 at 4:56 PM, Daniel Stenberg
<notifications@github.com> wrote:
>
> @frenche well, a gold star would be handed out if you'd accompany the patch with a test case! =)

Anything for a golden star :)

But I think we already have a test case for it, namely:
https://github.com/bagder/curl/blob/master/tests/data/test159

The reason this test currently passes without the fix is because the
'fake' server response is 'HTTP 1.1' and it does not send a
"Connection: close" header.
So it seem 'libcurl' upgrades to 'HTTP 1.1' and keeps the connection
open (although the user requested 1.0, in other words it decides the
HTTP version only based on server response).
I wonder if that is what we expect in such case.

Basically if I change the the 'fake' server response to 'HTTP 1.0' it
fails without the fix and succeeds with the fix applied.
However the 'HTTP 1.1' server response seem okay according to RFC 2145
although I'd expect it to close the connection in order to behave as
'HTTP 1.0'.

Quote from RFC 2145:
   One consequence of these rules is that an HTTP/1.1 message sent to an
   HTTP/1.0 recipient (or a recipient whose version is unknown) MUST be
   constructed so that it remains a valid HTTP/1.0 message when all
   headers not defined in the HTTP/1.0 specification [1] are removed.

So this lead me to test leaving the 'fake' server response as 'HTTP
1.1' and adding 'Connection: close' to the response (in test 159).
However my fix did not work for this case because we apparently only
check for 'Connection' header after 'Curl_http_input_auth()' call (the
code flow isn't clear to me but gdb indicated that).
Which means my fix would also probably cause the request to fail when
using 'HTTP 1.0' along with 'Connection: Keep-Alive' although it could
succeed this way.

Currently trying to think of a better alternative for the fix.
Any insight is very welcome.

Thanks,
Isaac B.

**Comment by frenche** [comment]
Hi again,

The function Curl_http_readwrite_headers() is one big loop and we need to hook after all the headers have been parsed as they can come in any order.

Please review PR #280 I think is OK.
I edited test 159 instead of creating a new one (hope it is done OK).

Thanks!

**Comment by bagder** [comment]
Merged the fix.
