### ISSUE TITLE
Cannot compile current master on Windows with GCC

### ISSUE THREAD

**Issue by michael-o** [bagder/curl#265]
Trying to compile curl gives me:

    D:\Projekte\curl>mingw32-make mingw32-sspi-winssl
    ...
    gcc -I. -I../include  -g -O2 -Wall -fno-strict-aliasing -m32 -DBUILDING_LIBCURL -DUSE_WINDOWS_SSPI -DUSE_SCHANNEL -c htt
    p_negotiate_sspi.c -o http_negotiate_sspi.o
    http_negotiate_sspi.c: In function 'Curl_input_negotiate':
    http_negotiate_sspi.c:97:15: error: 'data' undeclared (first use in this function)
           proxy ? data->set.str[STRING_PROXY_SERVICE_NAME] :
                   ^
    http_negotiate_sspi.c:97:15: note: each undeclared identifier is reported only once for each function it appears in
    Makefile.m32:311: recipe for target 'http_negotiate_sspi.o' failed
    mingw32-make[1]: *** [http_negotiate_sspi.o] Error 1
    mingw32-make[1]: Leaving directory 'D:/Projekte/curl/lib'
    Makefile:87: recipe for target 'mingw32-sspi-winssl' failed
    mingw32-make: *** [mingw32-sspi-winssl] Error 2

I have GCC 4.8.1 and GNU make 3.81.

**Comment by bagder** [comment]
Isn't 'data' a local variable in that function?

**Comment by jay** [comment]
My mingw32 didn't come with mingw32-make and actually in early versions I remember their msys installer said you shouldn't have it. I built master (1c01cee 2015-05-14) just now using the msys make and didn't have any problems. If you tell me how to install your mingw environment I'll try to reproduce but no guarantees on a fix.

**Comment by michael-o** [comment]
I'll retry with plain make.

**Comment by jay** [comment]
> I'll retry with plain make.

I found mingw32-make. I wasn't able to reproduce the problem. I did `buildconf.bat` and then `mingw32-make mingw32-sspi-winssl` and it built successfully from master (1c01cee 2015-05-14).

**Comment by michael-o** [comment]
I can confirm that. I did pull again from master. I had some revision from master which was half-baked. It does compile now.
