### ISSUE TITLE
Tag 7.42.1 contains incorrect version in curlver.h

### ISSUE THREAD

**Issue by michael-o** [bagder/curl#266]
Just compiled from tag 7.42.1 and noticed that [`curlver.h`](https://github.com/bagder/curl/blob/curl-7_42_1/include/curl/curlver.h#L33-L39) advertises itself incorrectly. I would expect to see `7.42.1` and not `7.42.0-DEV`. This is a release version and not a dev version, regardless from Git or from a tarball.

**Comment by Rider-Linden** [comment]
Please see https://github.com/bagder/curl/pull/257

**Comment by michael-o** [comment]
@Rider-Linden, on the 7.42.x branch has been fixed. The tag is still broken.

**Comment by bagder** [comment]
The release versions are tarballs, the tagged source tree are the exact moments in time the releases were made. It *does* *not* mean that we have the curlver.h file in git match the file in the release, as it gets generated by the release script itself. This has always been the case, 7.42.1 was nothing new in this regard.

**Comment by michael-o** [comment]
@bagder, why did you merge then the fix from #257 and are not willing to cherry pick it to the tag?

**Comment by bagder** [comment]
I merged it into the branch, and thus building from the branch gets the benefit from the #257 fix. The tag is already set as that's when the release was made. I can't change the release that was already made. I do not move release-tags.

**Comment by michael-o** [comment]
I accept that you do not intend to modify tags.
