### ISSUE TITLE
Curl_splay hangs in some cases

### ISSUE THREAD

**Issue by salos1982** [bagder/curl#269]
function struct Curl_tree *Curl_splay(struct timeval i,
                             struct Curl_tree *t)

one of callstacks
>	Hero_phone.dll!Curl_splay(timeval i, Curl_tree * t) Line 65	C
 	Hero_phone.dll!Curl_splayremovebyaddr(Curl_tree * t, Curl_tree * removenode, Curl_tree * * newroot) Line 255	C
 	Hero_phone.dll!Curl_expire(SessionHandle * data, long milli) Line 2652	C
 	Hero_phone.dll!Curl_resolver_is_resolved(connectdata * conn, Curl_dns_entry * * entry) Line 544	C
 	Hero_phone.dll!multi_runsingle(Curl_multi * multi, timeval now, SessionHandle * data) Line 1127	C
 	Hero_phone.dll!curl_multi_perform(void * multi_handle, int * running_handles) Line 1791	C

hangs because in some case t->smaller == t or t->larger == t. In this case we have endless loop I added asserts in this loop to detect issue
for(;;) {
    comp = compare(i, t->key);
    if(comp < 0) {
      if(t->smaller == NULL)
        break;
      if(compare(i, t->smaller->key) < 0) {
        y = t->smaller;                           /* rotate smaller */
        t->smaller = y->larger;
        y->larger = t;
        t = y;
        if(t->smaller == NULL)
          break;
      }
	  assert(r != t); //<- this is possible situation
      r->smaller = t;                               /* link smaller */
      r = t;
      t = t->smaller;
	  assert(t->smaller != t);
    }
    else if(comp > 0) {
      if(t->larger == NULL)
        break;
      if(compare(i, t->larger->key) > 0) {
        y = t->larger;                          /* rotate larger */
        t->larger = y->smaller;
        y->smaller = t;
        t = y;
        if(t->larger == NULL)
          break;
      }
	  assert(l != t);//<- this is possible situation
      l->larger = t;                              /* link larger */
      l = t;
      t = t->larger;
	  assert(t->larger != t);
    }
    else
      break;
  }

I do not understand what this function do so I cannot fix it. The strange issue is that this bug appears only on windows phone 8.1 (probably only on x64 processors). I use curl on other platforms for a long time and I have no such issue for other platforms (windows, android, ios)

**Comment by bagder** [comment]
Then please help us repeat the problem, I do not experience these problems. There's a unit test for the splay functions in test 1309 and I'm not aware of any existing flaws there.

The splay functions implement a splay tree: http://en.wikipedia.org/wiki/Splay_tree

**Comment by jay** [comment]
some general statement on splay trees which may or may not apply here (haven't read the code)... splay trees change themselves as they're accessed which can be a pitfall. i can imagine if the reporter has a callback that calls something in libcurl that does something to change the splay tree. tricky stuff. a few google results show up, specifically [this one](http://curl.haxx.se/mail/lib-2011-07/0000.html) (use of the word pitfall could not be more appropriate) and the reporter may want to consider if they have something similar.

**Comment by bagder** [comment]
This is also why understanding how the situation occurred is crucial. Just knowing that it _can_ break somehow doesn't help us very much.
