### ISSUE TITLE
Incomplete FTPS transfers through HTTP proxy

### ISSUE THREAD

**Issue by starless72** [bagder/curl#277]
When doing a FTPS connection through a HTTP proxy (Blue Coat ProxySG) and downloading a file using a clear data channel through the same proxy, the downloaded file is truncated.
As far as I can see it looks like curl is considering the "Connection established" header from the proxy as part of the file, and so closes the file transfer some bytes too early.

This happens with curl 7.40.0 on RedHat 6.3:

curl 7.40.0 (x86_64-redhat-linux-gnu) libcurl/7.40.0 OpenSSL/1.0.1e zlib/1.2.3 c-ares/1.10.0 libidn/1.18 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets Metalink

This is the command line I use:

`curl --trace-ascii - -k --ftp-ssl-control --disable-epsv --proxy <proxyIP>:3128 --proxytunnel ftp://<ftpUser>:<ftpPassword>@<serverIP>//testpub.xml`

The same operation works fine with older curl versions. It has been tested to work with versions 7.19.7, 7.25.0, 7.26.0 and 7.27.0, while it does NOT work with versions 7.29, 7.31, 7.38, 7.39 and 7.40, although I can't confirm the behaviour was always exactly the same (for example, I recall that with 7.29 the transfer just timed out).

**Comment by starless72** [comment]
The problem is still present in a more recent snapshot.
I downloaded http://curl.haxx.se/snapshots/curl-7.42.0-20150331.tar.gz, built it with default configure, make, make install on another RHEL 6.3 machine, then copied the /usr/local/* curl-related content on the target machine which is behind the proxy, and launched the same test command using /usr/local/bin/curl, but I get the exact same result, the downloaded file is not complete.
I hope the process I used is OK. I do not have complete freedom of what I can do on the target machine. Here is what I get with curl -V after installing the daily snapshot this way:

```
# /usr/local/bin/curl -V
curl 7.42.0-20150331 (x86_64-unknown-linux-gnu) libcurl/7.42.0-20150331 OpenSSL/1.0.0 zlib/1.2.3 libidn/1.18
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: IDN IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets
```

**Comment by starless72** [comment]
Here is a sample XML file I was downloading from the server, and also the full --trace-ascii logs from 7.19.7 and 7.40.0 containing also curl -V output and the used command line.
In the trace for version 7.40 you can see that the transfer is interrupted before the complete XML file is downloaded.

https://gist.github.com/starless72/e736ee1f20eab72c17ad

**Comment by bagder** [comment]
Can you provide a recipe that repeats the problem?

**Comment by starless72** [comment]
Er, sorry maybe you mean something specific I do not know when you talk about "recipe"... but anyway I'm afraid that to reproduce the issue the same kind of HTTP proxy is required.

**Comment by bagder** [comment]
What makes you say that? Did you try others and it always worked? Does your brand have something special going on?

**Comment by starless72** [comment]
Yes we did not experience the same issues when trying with http://www.charlesproxy.com/ for example.
This might be related to how curl interprets the HTTP header sent by the Blue Coat proxy, see issue description.

**Comment by bagder** [comment]
It is not likely to be because of proxy headers, then it wouldn't had gone through and after it as connected to the ftp server the proxy headers are not considered anymore.

The strange thing is that it looks just as if the connection gets aborted at that point as it reads no further bytes, but it also end up *not* complaining about a misaligned size (the SIZE response clearly says the server knows the file is larger).

I can only encourage you to either debug this yourself or possibly to bisect to find the exact change that broke it, as that might help us better understand what happens. Not being able to repeat this problem on my own makes it very hard for me track it down.

**Comment by starless72** [comment]
Hi,
I'm trying to find which version introduced the problem, by testing RHEL6 packages from http://nervion.us.es/city-fan/yum-repo/rhel6/x86_64/

For the moment I can tell you that curl-7.28.1-3.0.cf works fine, while curl-7.29.0-1.0.cf does not work, even though it still does not show the incomplete transfer problem, but just times out instead, as I recalled. Also curl-7.31.0-1.0.cf still has the same timeout problem.

Does this give you any hints on possible reasons for the issue?

Here is the trace from curl-7.29.0-1.0.cf: https://gist.github.com/starless72/fd9f1a850b652dcabda7
There is a long delay before the last "Proxy CONNECT aborted" line, that's why I talk about a timeout.

These are the installed versions of libssh2 and c-ares:

libssh2.x86_64                        1.5.0-1.0.cf.rhel6
c-ares.x86_64                         1.9.1-75.1

**Comment by bagder** [comment]
I cannot repeat this. I just landed the fix for #278, does it make curl behave any different for this problem?

**Comment by bagder** [comment]
Please try out the current git version and if there's still a problem, provide a detailed trace log again in previous fashion and lets go from there.

**Comment by starless72** [comment]
Sorry for the delay.
Yes I tested the same file transfer with curl 7.44.0 20150625 daily snapshot and it worked fine, good job!
Thanks.
