### ISSUE TITLE
CURLOPT_POSTFIELDS manpage: point readers to "curl_easy_escape"

### ISSUE THREAD

**Issue by bsammon** [bagder/curl#281]
as a newcomer to libcurl, I found it hard to find information on whether libcurl provided URL-encoding facilities.  It wasn't until a google search found a relevant post in the libcurl mailing list, that I found the curl_easy_escape function.

I think the CURLOPT_POSTFIELDS manpage should point users to the curl_easy_escape() function.

I think they are closely related enough that it should be mentioned twice, once in the "DESCRIPTION" section of the CURLOPT_POSTFIELDS manpage, and again in the "SEE ALSO" section.

**Comment by jay** [comment]
> I think the CURLOPT_POSTFIELDS manpage should point users to the curl_easy_escape() function.

Good point but I think once is probably enough. Landed in db979fe. Thanks
