### ISSUE TITLE
suggestions for curl_easy_escape manpage

### ISSUE THREAD

**Issue by bsammon** [bagder/curl#282]
1: In the SYNOPSIS section, the second argument is referred to as "url".  The DESCRIPTION section refers to it alternately as "the given input string" and the "input url".
As it is reasonable to use curl_easy_escape on strings that are not URLs (though they'll probably end up as part of one), I suggest replacing the "url" label with "str" or something like that.

2: It refers to RFC 2396.  Should that refer to a more recent RFC?

**Comment by jay** [comment]
I think I fixed all of what you described here in db979fe (issue #281) except for the RFC. If `curl_easy_escape` is implemented according to that RFC then it would be correct to reference it. Someone else will have to weigh in on that.

**Comment by bagder** [comment]
RFC3986 is the most recent URI syntax RFC and it seems to refer to that already.

**Comment by bsammon** [comment]
1.  Hm.  you fixed half of what I described here in db979fe, and the other half 6 months ago.  My computer has 7.41.0.  Thought I had verified this against the git version, bit I didn't notice the mismatch.  Sorry for any confusion.

2. According to https://tools.ietf.org/html/rfc2396, RFC2396 has been superceded by RFC3986.
but I guess the manpage shouldn't reference RFC3986 until someone has checked curl_easy_escape against it.

**Comment by bagder** [comment]
Where do you see 2396? http://curl.haxx.se/libcurl/c/curl_easy_escape.html clearly shows 3986

**Comment by bagder** [comment]
ah _unescape_ ...

**Comment by bagder** [comment]
fixed now!
