### ISSUE TITLE
OS X: Using PEM private keys fail with error: OSStatus -25299

### ISSUE THREAD

**Issue by ahmetalpbalkan** [bagder/curl#283]
This has been previously reported [here](http://sourceforge.net/p/curl/bugs/1417/) and was found invalid, but it doesn't look like that. By providing a PEM File (that is definitely in pem format) to `-E` like this causes the error:

```
$ curl -v -k -E mycert.pem http://url
* Hostname was NOT found in DNS cache
*   Trying 23.102.135.246...
* Connected to host.name.com (xx.102.135.xxx) port 443 (#0)
* WARNING: SSL: Certificate type not set, assuming PKCS#12 format.
* SSL: Can't load the certificate "mycert.pem" and its private key: OSStatus -25299
* Closing connection 0
```

Quite many more reports of this error can be found by Googling. ([1](https://github.com/boot2docker/boot2docker/issues/573), [2](http://earthwithsun.com/questions/851604/mac-os-x-yosemite-and-client-ssl-certificates)) Looks like this is specific to OS X.

If I switch to a Linux machine and use the same file, it works just fine and makes the request.

On OS X (that fails):

```
curl 7.37.1 (x86_64-apple-darwin14.0) libcurl/7.37.1 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IPv6 Largefile NTLM NTLM_WB SSL libz
```

On Linux (that works):

```
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
```

My pem file is in a format like:

```
-----BEGIN RSA PRIVATE KEY-----
...
-----END RSA PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
```

**Comment by nickzman** [comment]
This is not a curl bug. The Secure Transport back-end to curl only supports client IDs that are in PKCS#12 (P12) format; it does not support client IDs in PEM format because Apple does not allow us to create a security identity from an identity file in PEM format without using a private API. And we can't use the private API, because apps that use private API are not allowed in any of Apple's app stores.

This is documented in the man page: "The certificate must be in PKCS#12 format if using Secure Transport..."

I suggest that you convert your certificate & private key into a single P12 file; both the OpenSSL and Secure Transport back-ends support P12 (if OpenSSL was compiled with PKCS#12 support). You can use the openssl tool to handle the conversion.

**Comment by davidxia** [comment]
@ahmetalpbalkan This SO answer worked for me http://stackoverflow.com/a/24433135/553994.

Notice that `curl --version` for the homebrew installed one will say `OpenSSL` instead of `SecureTransport`

```
/usr/local/opt/curl/bin/curl --version

curl 7.45.0 (x86_64-apple-darwin15.0.0) libcurl/7.45.0 OpenSSL/1.0.2d zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

curl --version

curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets
```

**Comment by JohnMorales** [comment]
For anyone else getting to this issue when searching for "OSStatus -25299", this is how to convert a pem + cert to pkcs12..


`openssl pkcs12 -export -in ./client.crt -inkey ./client.pem -out client.p12`

where client.crt is your cert, client.pem is your private key, and client.p12 is your new password encrypted cert/key pkcs12 container.

With that I was able to use curl correctly with something like:
 `curl -v -k -E ./client.p12:password http://url`

**Comment by stevegraham** [comment]
Is OpenSSL still a dependency of the version that ships with Mac OS X? If so could cURL automatically create a PKCS#12 identity at runtime from normal X.509 and PKCS#8 arguments using OpenSSL APIs under the hood?

Would this a PR be welcome for this?

**Comment by bagder** [comment]
> Is OpenSSL still a dependency of the version that ships with Mac OS X?

Nope. I think a major part of the point of supporting the OS X native API instead of OpenSSL was to get rid of that dependency...

**Comment by stevegraham** [comment]
> Nope.

That's a shame.

Anyway, are you prepared to discuss a patch that did runtime transposition of X.509 and PKCS#8 into PKCS#12 (p12) at runtime if it didn't introduce external dependencies?

I need to look into this more according to RFC7292, encryption, enveloping, signing, etc of p12 contents is optional. Off the top of my head, we'd need a base64 encoder/decoder (✅ curl has this already), and a static p12 template to interpolate the binary cert and key?

RFC7292 - https://tools.ietf.org/html/rfc7292

Use case for not simply using p12: My company uses client authenticated TLS on our API. We never see the private key and developers are not required to use OpenSSL at all. Our web interface generates a key pair using WebCrypto, signs a PKCS#10 CSR for us, and we sign a cert the user then downloads. We've gone to great lengths to avoid the the developer having to mess around with the OpenSSL CLI, it would be a shame for our Mac OS X developers to have to use OpenSSL to create a p12 file. We're trying hard to fix developer experience with client SSL and would like to help restore this functionality for Mac OS X users.

What do you think?

**Comment by bagder** [comment]
> Anyway, are you prepared to discuss a patch that did runtime transposition of X.509 and PKCS#8 into PKCS#12 (p12) at runtime

Yes, very much so! But for discussions I recommend the curl-library mailing list and if you have a patch you could opt to instead do a pull-request.

**Comment by gajus** [comment]
> For anyone else getting to this issue when searching for "OSStatus -25299", this is how to convert a pem + cert to pkcs12..
> [..]

or just install curl with openssl support:

```sh
brew install curl --with-openssl && brew link curl --force
```

**Comment by adangert** [comment]
@gajus worked!! thanks

**Comment by gzldx** [comment]
use /usr/local/Cellar/curl/7.52.1/bin/curl is OK, the problem is we use the default version of curl in Mac is 7.43.0(/usr/bin/curl --version)

**Comment by gzldx** [comment]
>curl --version
curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5

>/usr/local/Cellar/curl/7.52.1/bin/curl --version
curl 7.52.1 (x86_64-apple-darwin15.6.0) libcurl/7.52.1 OpenSSL/1.0.2j zlib/1.2.5

**Comment by bagder** [comment]
As the man page says:

> (iOS  and macOS only) If curl is built against Secure Transport, then the certificate string can either be the name of a certificate/private key in the system or user keychain, or the path to a PKCS#12-encoded certificate and private key. If you want to use a file from the current  directory, please precede it with "./" prefix, in order to avoid confusion with a nickname.

(and please don't use closed issues to continue discussions/ask questeions, file new issues if you have problems or take discussions to the curl-library list)

**Comment by knasim** [comment]
SSL is a huge PITA !
