### ISSUE TITLE
on linux, -lcrypto linker flag is missing

### ISSUE THREAD

**Issue by kotoroshinoto** [bagder/curl#286]
was getting this error: curl-tool_metalink.o: undefined reference to symbol 'MD5_Final@@libcrypto.so.10'

**Comment by bagder** [comment]
Please give us a lot more details to go on, this is impossible to say anything about.

**Comment by dfandrich** [comment]
Especially, what SSL library you're using.

**Comment by kotoroshinoto** [comment]
the configure script was not finding pkgconfig for openssl. Fixing that allowed things to proceed properly. Figured it out shortly before bed. Thank you for your prompt attention though. It is appreciated.

libssl and such were on the search path, is there no way beyond pkgconfig to make sure it picks up the other required linkers?

**Comment by bagder** [comment]
Without pkgconfig it becomes a guessing game, and we can always improve our guessing but in reality that's rarely the better way forward.
