### ISSUE TITLE
Streaming input file while uploading with curl

### ISSUE THREAD

**Issue by dmgening** [bagder/curl#290]
Hello, recently i've encouraged problem while uploading large file with curl, approximately from 5 to 20Gb. While attaching file content to request body, file have been fully cached in RAM. So uploading 10Gb file would produce 10Gb memory load for curl process. I'm uploading file with following command: 

        $CURL -f --data-binary "@$file" "$HOOP_HOST/$UPLOAD_PATH?user.name=$HOOP_USER&op=create"

My curl version is 

    curl 7.37.1 (x86_64-apple-darwin14.0) libcurl/7.37.1 SecureTransport zlib/1.2.5
    Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp 
    Features: AsynchDNS GSS-Negotiate IPv6 Largefile NTLM NTLM_WB SSL libz 

My question - is it possible to stream input file for request without buffering similarly to `-N` option for output?

**Comment by bagder** [comment]
Would it be possible to make it work that way? Yes. Does it work that way now? No...

**Comment by jamshid** [comment]
I thought `curl -T bigfile https://example.com/` performs the PUT (or use -XPOST) without loading the entire file in memory. In a quick test I don't see the curl process' memory growing. But documentation for `-T` doesn't say anything about memory usage, and I guess you'd know...

**Comment by abhillman** [comment]
I am running CURL 7.37.1. FWIW: it would appear that using `-d @data` will cause a lot of memory usage, but that `-F data=@data` uses relatively little memory when POSTing a large file.

**Comment by bagder** [comment]
> -d @data causes a lot of memory usage

That's expected, yes.

**Comment by henryptung** [comment]
@bagder Would it make sense to reopen this ticket as a feature request, or would you prefer a separate ticket?

**Comment by bagder** [comment]
If you insist on filing a feature request, then please explain how "-T file -X POST" isn't good enough and make the request as a PR against the TODO document where you add the feature request. We don't keep feature-requests open in the issue tracker.

Much better than filing another feature-request (we're drowning in good ideas) is to actually work on making it happen.
