### ISSUE TITLE
Pre Compiler errors from CURL Header files

### ISSUE THREAD

**Issue by kcfitzger** [bagder/curl#293]
I am trying to compile a C program in UNIX, on an HP/UX server and I am getting unexplained errors. The CURL header files look all right to me, yet I cannot get a clean compile. I have tried adding PCADD=DEFINE= in my make file, but nothing I have tried works. Here are the errors I am receiving when I try and compile. Any help with this issue would be GREATLY appreciated:

Pro*C/C++: Release 11.2.0.3.0 - Production on Tue May 26 15:16:52 2015

Copyright (c) 1982, 2011, Oracle and/or its affiliates.  All rights reserved.

System default option values taken from: /u01/app/oracle/product/11.2.0/client_2/precomp/admin/pcscfg.cfg

Syntax error at line 171, column 9, file /usr/include/curl/curlbuild.h:
Error at line 171, column 9 in file /usr/include/curl/curlbuild.h
typedef CURL_TYPEOF_CURL_OFF_T curl_off_t;
........1
PCC-S-02201, Encountered the symbol "int64_t" when expecting one of the followin
g:

   auto, char, const, double, enum, float, int, long,
   ulong_varchar, OCIBFileLocator OCIBlobLocator,
   OCIClobLocator, OCIDateTime, OCIExtProcContext, OCIInterval,
   OCIRowid, OCIDate, OCINumber, OCIRaw, OCIString, register,
   short, signed, sql_context, sql_cursor, static, struct,
   union, unsigned, utext, uvarchar, varchar, void, volatile,
   a typedef name,
The symbol "enum," was substituted for "int64_t" to continue.

Syntax error at line 204, column 9, file /usr/include/sys/socket.h:
Error at line 204, column 9 in file /usr/include/sys/socket.h
        sa_family_t     sa_family;      /* address family */
........1
PCC-S-02201, Encountered the symbol "sa_family_t" when expecting one of the foll
owing:

   char, const, double, enum, float, int, long, ulong_varchar,
   OCIBFileLocator OCIBlobLocator, OCIClobLocator, OCIDateTime,
   OCIExtProcContext, OCIInterval, OCIRowid, OCIDate, OCINumber,
   OCIRaw, OCIString, short, signed, sql_context, sql_cursor,
   struct, union, unsigned, utext, uvarchar, varchar, void,
   volatile, a typedef name,
The symbol "enum," was substituted for "sa_family_t" to continue.

Syntax error at line 239, column 2, file /usr/include/sys/socket.h:
Error at line 239, column 2 in file /usr/include/sys/socket.h
        sa_family_t   ss_family;                /* address family */
.1
PCC-S-02201, Encountered the symbol "sa_family_t" when expecting one of the foll
owing:

   char, const, double, enum, float, int, long, ulong_varchar,
   OCIBFileLocator OCIBlobLocator, OCIClobLocator, OCIDateTime,
   OCIExtProcContext, OCIInterval, OCIRowid, OCIDate, OCINumber,
   OCIRaw, OCIString, short, signed, sql_context, sql_cursor,
   struct, union, unsigned, utext, uvarchar, varchar, void,
   volatile, a typedef name,
The symbol "enum," was substituted for "sa_family_t" to continue.

Syntax error at line 230, column 3, file /usr/include/curl/curl.h:
Error at line 230, column 3 in file /usr/include/curl/curl.h
  curlfiletype filetype;
..1
PCC-S-02201, Encountered the symbol "curlfiletype" when expecting one of the fol
lowing:

   } char, const, double, enum, float, int, long, ulong_varchar,
   OCIBFileLocator OCIBlobLocator, OCIClobLocator, OCIDateTime,
   OCIExtProcContext, OCIInterval, OCIRowid, OCIDate, OCINumber,
   OCIRaw, OCIString, short, signed, sql_context, sql_cursor,
   struct, union, unsigned, utext, uvarchar, varchar, void,
   volatile, a typedef name,
The symbol "enum," was substituted for "curlfiletype" to continue.

Syntax error at line 235, column 3, file /usr/include/curl/curl.h:
Error at line 235, column 3 in file /usr/include/curl/curl.h
  curl_off_t size;
..1
PCC-S-02201, Encountered the symbol "curl_off_t" when expecting one of the follo
wing:

   } char, const, double, enum, float, int, long, ulong_varchar,
   OCIBFileLocator OCIBlobLocator, OCIClobLocator, OCIDateTime,
   OCIExtProcContext, OCIInterval, OCIRowid, OCIDate, OCINumber,
   OCIRaw, OCIString, short, signed, sql_context, sql_cursor,
   struct, union, unsigned, utext, uvarchar, varchar, void,
   volatile, a typedef name,
The symbol "enum," was substituted for "curl_off_t" to continue.

Syntax error at line 296, column 35, file /usr/include/curl/curl.h:
Error at line 296, column 35 in file /usr/include/curl/curl.h
                                  curl_off_t offset,
..................................1
PCC-S-02201, Encountered the symbol "curl_off_t" when expecting one of the follo
wing:

   ... auto, char, const, double, enum, float, int, long,
   ulong_varchar, OCIBFileLocator OCIBlobLocator,
   OCIClobLocator, OCIDateTime, OCIExtProcContext, OCIInterval,
   OCIRowid, OCIDate, OCINumber, OCIRaw, OCIString, register,
   short, signed, sql_context, sql_cursor, static, struct,
   union, unsigned, utext, uvarchar, varchar, void, volatile,
   a typedef name, exec oracle, exec oracle begin, exec,
   exec sql, exec sql begin, exec sql type, exec sql var,
The symbol "enum," was substituted for "curl_off_t" to continue.

Syntax error at line 325, column 38, file /usr/include/curl/curl.h:
Error at line 325, column 38 in file /usr/include/curl/curl.h
                                     curl_socket_t curlfd,
.....................................1
PCC-S-02201, Encountered the symbol "curl_socket_t" when expecting one of the fo
llowing:

   ... auto, char, const, double, enum, float, int, long,
   ulong_varchar, OCIBFileLocator OCIBlobLocator,
   OCIClobLocator, OCIDateTime, OCIExtProcContext, OCIInterval,
   OCIRowid, OCIDate, OCINumber, OCIRaw, OCIString, register,
   short, signed, sql_context, sql_cursor, static, struct,
   union, unsigned, utext, uvarchar, varchar, void, volatile,
   a typedef name, exec oracle, exec oracle begin, exec,
   exec sql, exec sql begin, exec sql type, exec sql var,
The symbol "exec," was substituted for "curl_socket_t" to continue.

Syntax error at line 328, column 1, file /usr/include/curl/curl.h:
Error at line 328, column 1 in file /usr/include/curl/curl.h
struct curl_sockaddr {
1
PCC-S-02201, Encountered the symbol "struct" when expecting one of the following
:

   , )
The symbol "," was substituted for "struct" to continue.

Syntax error at line 336, column 2, file /usr/include/curl/curl.h:
Error at line 336, column 2 in file /usr/include/curl/curl.h
};
.1
PCC-S-02201, Encountered the symbol ";" when expecting one of the following:

   , ( ) [ * auto, const, extern, register, static, volatile,
   an identifier,

Syntax error at line 0, column 0, file prvp026m.sc:
Error at line 0, column 0 in file prvp026m.sc
PCC-S-02201, Encountered the symbol "<eof>" when expecting one of the following:

   ; : an identifier, end-exec, random_terminal

Error at line 0, column 0 in file prvp026m.sc
PCC-F-02102, Fatal error while doing C preprocessing
/cust/test/dswi/src/custom.mak:68: recipe for target 'prvp026m.c' failed
gmake: *** [prvp026m.c] Error 1

**Comment by bagder** [comment]
Which libcurl version is this?

Does your compiler/system support 64 bit types at all? What does configure say about "checking for 64-bit curl_off_t data type" and the subsequent "checking size of curl_off_t" ?

Further, you get a syntax error in /usr/include/sys/socket.h which looks really strange. Are you building other software fine with this compiler setup?

**Comment by kcfitzger** [comment]
libcurl version is 7.28.1
Yes, the compiler will support 64 bit data types. In the custom.mak we are forcing it to a 32-bit compilation though.
I'm not sure about your last question. My C program has embedded sql (so it's a .sc program), and I am calling a C sub-program with some HTTP commands that has #include <sys/socket.h> in it. I tried commenting it out, but still got the errors.

**Comment by kcfitzger** [comment]
#include <sys/socket.h> that is.

**Comment by kcfitzger** [comment]
sys/socket.h

**Comment by bagder** [comment]
The syntax error in the system include file works like a marker to me that something is weird with your compiler setup. Normally the system headers should not cause syntax errors when you include one of them.

> compiler will support 64 bit data types. In the custom.mak we are forcing it to a 32-bit

That is probably reason enough to cause problems. libcurl detects and sets things up for 64bit when you run configure, only to have it knee-capped when you then build your application. I would suggest that if you want to disable 64bit use in your application, build libcurl without 64bit support too already when you run configure.

**Comment by kcfitzger** [comment]
Hi Daniel, Sorry, I got sidetracked by another project. My system guys are telling me that we have both the 64 and 32 byte versions of CURL compiled on our system. Are you saying that we need to remove the 64 byte version? Or is there a command I can include in my make file (C code) that will point only to the 32 byte version?

Thanks again for your assistance…..

Kevin Fitzgerald
Provider SE
Eligibility/SSI SE
Healthcheck SE
TPL SE
Batch Promotion Coordinator
HP Enterprise Services
Work:  847-485-8060
Cell: 847-204-5077
kevin.fitzgerald@hp.com

**Comment by bagder** [comment]
You need to use one set of curl headers for the 32bit build and another set for the 64bit build. Configure generates stuff in the headers that are specific for that particular invoke of configure.

**Comment by kcfitzger** [comment]
Hi Daniel, well, I have gotten past my compile issues and now I have another. I pretty much copied the send/receive code from the CURL website, and I am attempting to send an XML request to a web service. I am getting back an error response. Am I missing something in my CURL code?

CURL Code:

curl = curl_easy_init();
            if(curl)
            {
               /* specify target URL */
               curl_easy_setopt(curl, CURLOPT_URL, url);

               curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, FALSE);

               curl_easy_setopt(curl, CURLOPT_CONNECT_ONLY, 1L);
               res = curl_easy_perform(curl);

               if(CURLE_OK != res)
               {
                   printf("Error: %s\n", strerror(res));
                   return 1;
               }

               /* Extract the socket from the curl handle - we'll need it for waiting.
                * Note that this API takes a pointer to a 'long' while we use
                * curl_socket_t for sockets otherwise.
               */
               res = curl_easy_getinfo(curl, CURLINFO_LASTSOCKET, &sockextr);

               if(CURLE_OK != res)
               {
                   printf("Error: %s\n", curl_easy_strerror(res));
                   return 1;
               }

               sockfd = sockextr;

               /* wait for the socket to become ready for sending */
               if(!wait_on_socket(sockfd, 0, 60000L))
               {
                   printf("Error: timeout.\n");
                   return 1;
               }

               puts("Sending request.");
               /* Send the request. Real applications should check the iolen
                * to see if all the request has been sent */
               res = curl_easy_send(curl, full_msg, strlen(full_msg), &iolen);
if(CURLE_OK != res)
               {
                   printf("Send Error: %s\n", curl_easy_strerror(res));
                   return 1;
               }
               puts("Reading response.");

               /* read the response */
               wait_on_socket(sockfd, 1, 60000L);
               res = curl_easy_recv(curl, s1, BUF_SZ9, &iolen);

               if(CURLE_OK != res)
               {
                   printf("Recieve Error: %s\n", curl_easy_strerror(res));
                   return 1;
               }

               nread = (curl_off_t)iolen;

               printf("Received %" CURL_FORMAT_CURL_OFF_T " bytes.\n", nread);
               fprintf(stdout, "InString = %s\n", s1);
               /* always cleanup */
               curl_easy_cleanup(curl);


ERROR Message:

Reading response.
Received 2056 bytes.
InString = HTTP/1.1 500 Internal Server Error
Date: Mon, 08 Jun 2015 19:27:32 GMT
Server: Microsoft-IIS/6.0
X-Powered-By: ASP.NET
X-AspNet-Version: 2.0.50727
Cache-Control: private
Content-Type: application/soap+xml; charset=utf-8
Content-Length: 1805

<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><soap:Fault><soap:Code><soap:Value>soap:Receiver</soap:Value></soap:Code><soap:Reason><soap:Text xml:lang="en">System.Web.Services.Protocols.SoapException: Server was unable to process request. ---&gt; System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Web.Services.Protocols.SoapServerProtocol.SoapEnvelopeReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at System.Web.Services.Protocols.SoapServerProtocol.SoapEnvelopeReader.MoveToContent()
   at System.Web.Services.Protocols.SoapServerProtocolHelper.GetRequestElement()
   at System.Web.Services.Protocols.Soap12ServerProtocolHelper.RouteRequest()
   at System.Web.Services.Protocols.SoapServerProtocol.RouteRequest(SoapServerMessage message)
   at System.Web.Services.Protocols.SoapServerProtocol.Initialize()
   at System.Web.Services.Protocols.ServerProtocol.SetContext(Type type, HttpContext context, HttpRequest request, HttpResponse response)
   at System.Web.Services.Protocols.ServerProtocolFactory.Create(Type type, HttpContext context, HttpRequest request, HttpResponse response, Boolean&amp; abortProcessing)
   --- End of inner exception stack trace ---</soap:Text></soap:Reason><soap:Detail /></soap:Fault></soap:Body></soap:Envelope>

Kevin Fitzgerald
Provider SE
Eligibility/SSI SE
Healthcheck SE
TPL SE
Batch Promotion Coordinator
HP Enterprise Services
Work:  847-485-8060
Cell: 847-204-5077
kevin.fitzgerald@hp.com

**Comment by bagder** [comment]
For general libcurl discussions and support, please use the curl-library mailing list. This is a (closed) issue about preprocessor errors that magically vanished. Let's not add non-related stuff to it.
