### ISSUE TITLE
credentials for NTLM auth

### ISSUE THREAD

**Issue by DarovskikhAndrei** [bagder/curl#296]
If I specify password and not specify username for ntlm auth, then curl library will use current user for ntlm auth. It is ambiguous behaviour.

This patch fix it:
Index: curl.h
===================================================================
--- curl.h	(revision 373210)
+++ curl.h	(working copy)
@@ -519,6 +519,7 @@
   CURLE_CHUNK_FAILED,            /* 88 - chunk callback reported error */
   CURLE_NO_CONNECTION_AVAILABLE, /* 89 - No connection available, the
                                     session will be queued */
+  CURLE_CREDENTALS_ERROR,        /* 90 - use password without user in NTLM auth */
   CURL_LAST /* never use! */
 } CURLcode;

Index: curl_ntlm_msgs.c
===================================================================
--- curl_ntlm_msgs.c	(revision 373210)
+++ curl_ntlm_msgs.c	(working copy)
@@ -429,8 +429,11 @@
     /* setup ntlm identity's flags */
     ntlm->identity.Flags = SECFLAG_WINNT_AUTH_IDENTITY;
   }
-  else
-    ntlm->p_identity = NULL;
+  else {
+      if(passwdp && *passwdp)
+          return CURLE_CREDENTALS_ERROR;
+      ntlm->p_identity = NULL;
+  }
 
   status = s_pSecFn->AcquireCredentialsHandle(NULL,
                                               (TCHAR *) TEXT("NTLM"),

**Comment by bagder** [comment]
This patch ended up completely unreadable and unparsable. Can you please try to submit it again with the necessary markdown formatting or perhaps easier, make a pull-request for it?

**Comment by DarovskikhAndrei** [comment]
I use curl 7.32 and now update it to 7.42.1 version. After I will do patch to fix this error.

**Comment by bagder** [comment]
Let's re-open if something new happens
