### ISSUE TITLE
PK pinning support for iOS- darwin ssl

### ISSUE THREAD

**Issue by danisoft2** [bagder/curl#297]
Hi, 

I'm working on a cross platform project which requires SSL pinning (public key pinning) for the TLS connectivity.
In Android and Windows we use OpenSSL as the TLS library and it does support CURLOPT_PINNEDPUBLICKEY for the pinning and it works perfectly.

In iOS however we use DarwinSSL as this is the native ssl library which also allows us to do the CA verfivication whereas the OpenSSL on iOS does not allow CA validation (cannot retrieve the certs info from the keychain).

So, we must use DarwinSSL on iOS for the CA validation and we also want to verify the PK.
I did some investigation and it seems that this logic should be added to 'curl/libs/vtls/darwinssl.c'. 
Any idea how to add it? Has anyone implemented before for ios?

Thanks,
Dan.

**Comment by bagder** [comment]
This is an issue tracker, if you want to discuss developer problems and get help on how to do those things, you really should use the curl-library mailing list instead to reach the entire libcurl developer community.

To implement key pinning for a TLS backend you need to figure out how to use the API to extract the public key and then be able to compare that to the pinned one. Inspiration should be able to get from the openssl or GnuTLS backends which both have this feature already.

**Comment by danisoft2** [comment]
You are right, i will post it in the mailing list (i'm kind of new with curl).
I will mark it as closed.
Thanks again.
