### ISSUE TITLE
Using nghttp2 Compile error 

### ISSUE THREAD

**Issue by stdying** [bagder/curl#298]
http2.c: In function 'Curl_http2_init':
http2.c:581:7: warning: passing argument 2 of 'nghttp2_session_callbacks_set_on_invalid_frame_recv_callback' from incompatible pointer type [enabled by default]
       (callbacks, on_invalid_frame_recv);
       ^
In file included from http2.c:27:0:
/usr/local/include/nghttp2/nghttp2.h:1720:1: note: expected 'nghttp2_on_invalid_frame_recv_callback' but argument is of type 'int (*)(struct nghttp2_session *, const union nghttp2_frame *, uint32_t,  void *)'
 nghttp2_session_callbacks_set_on_invalid_frame_recv_callback(
 ^
http2.c: In function 'Curl_http2_switched':
http2.c:1022:6: error: 'NGHTTP2_CLIENT_CONNECTION_PREFACE' undeclared (first use in this function)
      NGHTTP2_CLIENT_CONNECTION_PREFACE,
      ^
http2.c:1022:6: note: each undeclared identifier is reported only once for each function it appears in
http2.c:1023:6: error: 'NGHTTP2_CLIENT_CONNECTION_PREFACE_LEN' undeclared (first use in this function)
      NGHTTP2_CLIENT_CONNECTION_PREFACE_LEN,
      ^
make[2]: *** [libcurl_la-http2.lo] error 1

**Comment by bagder** [comment]
Which libcurl and nghttp2 versions?

**Comment by stdying** [comment]
- curl-7.42.1

- nghttp2 
./configure

configure: summary of build options:

    Version:        1.0.2-DEV shared 14:1:0
    Host type:      x86_64-unknown-linux-gnu
    Install prefix: /usr/local
    C compiler:     gcc
    CFLAGS:         -g -O2
    WARNCFLAGS:     
    LDFLAGS:        
    LIBS:           
    CPPFLAGS:       
    C preprocessor: gcc -E
    C++ compiler:   g++
    CXXFLAGS:       -g -O2 -std=c++11
    CXXCPP:         g++ -E
    Library types:  Shared=yes, Static=yes
    Python:
      Python:         /usr/bin/python
      PYTHON_VERSION: 2.7
      pyexecdir:      ${exec_prefix}/lib/python2.7/dist-packages
      Python-dev:     yes
      PYTHON_CPPFLAGS:-I/usr/include/python2.7
      PYTHON_LDFLAGS: -L/usr/lib -lpython2.7
      Cython:         cython
    Test:
      CUnit:          yes
      Failmalloc:     yes
    Libs:
      OpenSSL:        yes
      Libxml2:        yes
      Libev:          yes
      Libevent(SSL):  yes
      Spdylay:        yes
      Jansson:        yes
      Jemalloc:       yes
      Zlib:           yes
      Boost CPPFLAGS: 
      Boost LDFLAGS:  
      Boost::ASIO:    
      Boost::System:  
      Boost::Thread:  
    Features:
      Applications:   yes
      HPACK tools:    yes
      Libnghttp2_asio:no
      Examples:       yes
      Python bindings:yes
      Threading:      yes

**Comment by bagder** [comment]
You're using an unsupported combination!

For curl 7.42.1 or earlier, use nghttp2 0.7.15 or earlier.
For curl > 7.42.1 (like current git or the pending 7.43.0 release), use nghttp2 1.0.0 or later

**Comment by stdying** [comment]
good
