### ISSUE TITLE
SSLv2_client_method missing symbol

### ISSUE THREAD

**Issue by nickdesaulniers** [bagder/curl#299]
I'm currently trying to statically link libcrypto, libssl, and libcurl in an application.  I think I'm doing every right, but may be wrong, but I have one undefined symbol left, and I think it's a problem with libcurl, or even how I'm configuring it.  When I build, I see:

```
...
Undefined symbols for architecture x86_64:
  "_SSLv2_client_method", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
...
```

I'm trying to statically link against openssl-1.0.2a and libcurl-7.42.1.  I configure the build of libssl.a with:

```
./Configure darwin64-x86_64-cc no-ssl2 no-ssl3 no-idea no-shared no-npn no-psk no-srp
```

and then I configure libcurl.a with:

```
PKG_CONFIG_PATH=../../openssl-1.0.2a ../configure --disable-shared --without-zlib --without-libidn --disable-ldap
```

**Comment by nickdesaulniers** [comment]
I'm not sure how libcurl is detecting whether or not libssl was configured with `no-ssl2`, but maybe I'm doing something wrong?

**Comment by jay** [comment]
That doesn't sound right, since 7.24 (over 3 years ago) it uses the linker to test for `SSLv2_client_method` in ssl lib. If the function is found then configure defines `HAVE_SSLV2_CLIENT_METHOD` and if that's defined then the openssl source file (name/location has changed, currently vtls/openssl.c) defines `OPENSSL_NO_SSL2` and then in connect the `SSLv2_client_method` call is only exposed if not NO_SSL2.

My guess is configure is using some older version for the tests, maybe your pkgconfig dir is wrong? I think it usually ends in pkgconfig but I don't recall what happens when it's not installed. I'd check the configure log to see what's happening. Also if I recall there was/is some issue working with the static openssl libraries, configure always prefers dynamic openssl instead of static or it's the other way around, or if it can't find dynamic it converts to static but won't build or something.

**Comment by nickdesaulniers** [comment]
> it uses the linker to test for SSLv2_client_method in ssl lib

```
➜  openssl-1.0.2a git:(master) ✗ nm libssl.a 2>/dev/null| grep SSLv2_client_method
➜  openssl-1.0.2a git:(master) ✗
```

> maybe your pkgconfig dir is wrong? I think it usually ends in pkgconfig

`openssl.pc`, `libcrypto.pc`, and `libssl.pc` are all in the top level dir of `openssl-1.0.2a`.

> I'd check the configure log to see what's happening.

Where does curl store the configure log?

**Comment by jay** [comment]
> Where does curl store the configure log?

./config.log

**Comment by bagder** [comment]
Hm, when I try to run curl's configure to build and use a static-only OpenSSL lib setup on Linux I need to provide "LIBS="-ldl" ./configure ..."  or it'll fail. I don't think the regular .pc files are made for linking statically.

**Comment by jay** [comment]
The pc files I have in Ubuntu 14 support static, the libcrypto has `Libs.private: -ldl`. Though whether their config always adds that when it makes the pc files I don't know. 
~~~
pkg-config --libs --cflags openssl
 -lssl -lcrypto  
pkg-config --static --libs --cflags openssl
 -lssl -lcrypto -ldl  
~~~

**Comment by nickdesaulniers** [comment]
```
➜  build git:(master) ✗ ack HAVE_SSLV2_CLIENT_METHOD config.log
| #define HAVE_SSLV2_CLIENT_METHOD 1
...
```

**Comment by nickdesaulniers** [comment]
```
➜  openssl-1.0.2a git:(master) ✗ PKG_CONFIG_PATH=. pkg-config libssl --libs --static --cflags
-I/usr/local/ssl/include -L/usr/local/ssl/lib -lssl -lcrypto
```
but I don't want the builds of openssl in those dirs, I want to statically link the build in this dir.

**Comment by nickdesaulniers** [comment]
```
➜  deps git:(master) ✗ cat openssl-1.0.2a/libssl.pc | grep Libs.private
Libs.private:
➜  deps git:(master) ✗ cat openssl-1.0.2a/libcrypto.pc | grep Libs.private
Libs.private:
```

**Comment by jay** [comment]
Well I don't know if you need ldl on your system. For mine OpenSSL and curl both depend on dynamic libraries even when I link static. Example:
~~~
owner@ubuntu1404-x64-vm:~/curl/lib/.libs$ gcc --static -o a a.c -L. -lcurl -I ../../include -lssl -lcrypto -ldl -lz
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
(.text+0x11): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
./libcurl.a(libcurl_la-netrc.o): In function `Curl_parsenetrc':
netrc.c:(.text+0x3b1): warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
./libcurl.a(libcurl_la-curl_addrinfo.o): In function `Curl_getaddrinfo_ex':
curl_addrinfo.c:(.text+0x70): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
owner@ubuntu1404-x64-vm:~/curl/lib/.libs$ ldd a
	not a dynamic executable
~~~

My guess for your situation though is they don't generate the pc files or don't add the paths or something until it's installed. Either generate the pc files yourself, or install openssl 1.0.2 to some location then use that pkgconfig dir or pass to curl configure `--with-ssl=/that/dir` which also requires installing OpenSSL there as a prerequisite.

**Comment by bagder** [comment]
> but I don't want the builds of openssl in those dirs, I want to statically link the build in this dir.

Then check the log again to find what things that made those wrong paths get used. Somehow configure gets the wrong one. Personally I tend to build my static OpenSSL builds as static-only and then just do --with-ssl=[PATH] and that LIBS="-ldl" trick and that have worked since forever.

**Comment by nickdesaulniers** [comment]
Will try `--with-ssl`. Note `./configure --help` advises *against* that:
```
  --with-ssl=PATH         Where to look for OpenSSL, PATH points to the SSL
                          installation (default: /usr/local/ssl); when
                          possible, set the PKG_CONFIG_PATH environment
                          variable instead of using this option
```

**Comment by bagder** [comment]
Yes, we advice against using static libs too.

**Comment by nickdesaulniers** [comment]
When I run:
```
../configure --disable-shared --without-zlib --without-libidn --disable-ldap --with-ssl=../../openssl-1.0.2a && make
```

make fails with:
```
../libtool: line 5986: cd: ../../openssl-1.0.2a/lib: No such file or directory
libtool: link: cannot determine absolute directory name of `../../openssl-1.0.2a/lib'
```

Is there a unix-ism for expanding relative paths to absolute paths?

**Comment by nickdesaulniers** [comment]
oh, well it's looking for a dir that doesn't exist:
```
➜  build git:(master) ✗ ls ../../openssl-1.0.2a | grep lib
libcrypto.a
libcrypto.pc
libssl.a
libssl.pc
shlib
```

**Comment by bagder** [comment]
You're supposed to pass in the path prefix to the installed path, it _should_ have a lib subdirectory or you have a very funny installation.

**Comment by bagder** [comment]
$ ls -l ~/build-openssl/
total 16
drwxr-xr-x 2 daniel daniel 4096 May 27 15:17 bin
drwxr-xr-x 3 daniel daniel 4096 May 27 15:09 include
drwxr-xr-x 4 daniel daniel 4096 May 27 15:17 lib
drwxr-xr-x 6 daniel daniel 4096 May 27 15:17 ssl

**Comment by nickdesaulniers** [comment]
I *don't* want to install it.  I want to do an out of source build and link against that single build of a .a file.  Maybe I should build openssl and explicitly set the install path to that particular out of source build dir, then pass that to libcurl's configure step?

**Comment by bagder** [comment]
That's the by far easiest solution and how I took for granted everyone would do it. Alternatively you "mimic" an install tree in your build tree by adding symlinks or similar, but I really see no point in doing it that way...

**Comment by nickdesaulniers** [comment]
So I'm [not able to build openSSL](https://groups.google.com/forum/#!topic/mailing.openssl.dev/5L4Cu-dPg9I)...

LibreSSL is much saner to build, but doesn't seem to work when configuring libcurl now...
```
➜  build git:(master) ✗ ../configure --disable-shared --without-zlib --without-libidn --disable-ldap --with-ssl=../../libressl-2.1.6/build
....
checking run-time libs availability... failed
configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lssl -lcrypto -lssl -lcrypto
```
same results with:
```
➜  build git:(master) ✗ PKG_CONFIG_PATH=../../libressl-2.1.6/build ../configure --disable-shared --without-zlib --without-libidn --disable-ldap
```

**Comment by nickdesaulniers** [comment]
hey were in business!  Just wiped out the curl and re-extracted, and everything's working.  For future travelers, I built libressl with:

```
../configure --prefix=`pwd`
make install
```

and build libcurl with:

```
PKG_CONFIG_PATH=../../libressl-2.1.6/build ../configure --disable-shared --without-zlib --without-libidn --disable-ldap
make
```

both were out of source.  Thanks for your time Daniel.  Also, nice [post](http://daniel.haxx.se/blog/2014/08/05/eight-months-mozilla/).  [8 months must be a special number](https://nickdesaulniers.github.io/blog/2013/06/13/8-months-in-mozilla/)?
