### ISSUE TITLE
curl_easy_perform() blocking

### ISSUE THREAD

**Issue by znoodl** [bagder/curl#300]
Hi:
    I am using libcurl to do a HTTP client for myself. , It blocking on `curl_easy_perform()` when I use `curl_easy_setopt(curl, CURLOPT_HTTPPUT, 1);`, but `curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "PUT");` not.  And it also blocking on `curl_multi_perform()` .
I don't know why .

**Comment by bagder** [comment]
`CURLOPT_HTTPPUT` means you do a PUT and then you need to provide data to upload, and a size for it. Did you?

Setting `CURLOPT_CUSTOMREQUEST` to "PUT" just makes libcurl do a regular GET-style transfer but replace the method keyword in the request and it won't upload anything.

**Comment by znoodl** [comment]
OK, I know now.
Thank you very much.
:)
