### ISSUE TITLE
cookie doesn't work with curl 7.29 

### ISSUE THREAD

**Issue by pivasoftware** [bagder/curl#313]
I'am using openwrt AA and I use libcurl 7.29 for http communication.
my cwmp client communicate with ACS server (feeacs ) and the communication is stoped since curl can't send the cookies to the server 
in the other hand this issue is not reproduced with curl 7.40

this HTTP header of my server 
Server: Apache-Coyote/1.1
Set-Cookie: JSESSIONID=72D8DC23BD37016CD5557BB353DD008E; Path=/tt/; HttpOnly
SOAPAction: 
Content-Type: text/xml;charset=ISO-8859-1
Content-Length: 491
Date: Wed, 03 Jun 2015 14:02:53 GMT   

I'am wonder if I can continue use the curl version 7.29 and just merge the solution which solve the cookies issue !
it's possible  to get this patches

**Comment by jay** [comment]
For future reference discussions like this are best brought to the libcurl developer mailing list.
http://cool.haxx.se/mailman/listinfo/curl-library
If the issue isn't reproducible in later versions of curl then you can assume it was fixed at some point. To backport you'd need to do a bisect to figure out what change fixed the issue. Though I advise you for security and stability reasons don't backport and instead use the latest version. If there is some issue in the latest version of curl that prevents you from using it then open a different issue for that.
