### ISSUE TITLE
sftp upload hangs

### ISSUE THREAD

**Issue by majestix508** [bagder/curl#315]
Hi,

my sftp upload isn't working - connection works, but the the file gets created and my program hangs.
Heres my curl version:

curl 7.42.1 (x86_64-unknown-linux-gnu) libcurl/7.42.1 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5 libssh2/0.18
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: IDN IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets

sftp and ftps is enabled with libssh2

here's my code for the sftp upload summarized:
```c
    curl_easy_setopt(m_curl, CURLOPT_USERNAME, a_crUsername.c_str());
    curl_easy_setopt(m_curl, CURLOPT_PASSWORD, a_crPassword.c_str());
    curl_easy_setopt(m_curl, CURLOPT_UPLOAD, 1L);
    //Create FTP Uri
    string l_uri;
    if (m_Type == FTPTYPE_SFTP)
        l_uri = "sftp://";
    else if (m_Type == FTPTYPE_FTPS)
        l_uri = "ftps://";
    else
        l_uri = "ftp://";

    l_uri += a_crHostname+"/" + filename;
    curl_easy_setopt(m_curl, CURLOPT_URL, l_uri.c_str());

    struct curl_slist* list = NULL;
    if (m_Type != FTPTYPE_SFTP ){
        //Set Type I (Image-Binary)
        list = curl_slist_append(list, "TYPE I");
        curl_easy_setopt(m_curl, CURLOPT_QUOTE, list);
    }

    struct FTPData l_data;
    l_data.m_Data = (char *)a_cpBuffer;
    l_data.m_size = (size_t)a_cBufferLength;
    /* we want to use our own read function */
    curl_easy_setopt(m_curl, CURLOPT_READFUNCTION, &CFtp::HandleReadData);

    /* pointer to pass to our read function */
    curl_easy_setopt(m_curl, CURLOPT_READDATA, &l_data);

    /* Set the size of the file to upload (optional). */
    curl_easy_setopt(m_curl, CURLOPT_INFILESIZE_LARGE, (curl_off_t)a_cBufferLength);

    res = curl_easy_perform(m_curl);
```
Here's the read callback:

```c
size_t CFtp::HandleReadData(char *buffer, size_t size, size_t nitems, void *instream)
{
    struct FTPData *data = (struct CFtp::FTPData *) instream;
    if (size*nitems <1)
        return 0;
    if (data && data->m_size) {
        *(char*)buffer = data->m_Data[0]; /* copy one single byte */
        data->m_Data++;                   /* advance pointer */
        data->m_size--;                   /* less data left */
        return 1;                         /* we return 1 byte at a time! */
    }
    return 0; /* no mire data left to deliver */
}
```
Here's the Verbose output:
*   Trying xxx.xxx.xxx.xxx...
* Connected to xxx.xxx.at (xxx.xxx.xxx.xxx) port 22 (#0)
* SSH MD5 fingerprint: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
* SSH authentication methods available: publickey,gssapi-with-mic,password
* Using SSH public key file '(nil)'
* Using SSH private key file '/home/user//.ssh/id_rsa'
* SSH public key authentication failed: Unable to open public key file
* Initialized password authentication
* Authentication complete

I tried this on the command-line with almost the same result - curl hangs but after transfering the file - here's the command:
/opt/curl-7.42.1/bin/curl  -v -u username:password  -T /home/user/apple-touch-icon.png sftp://xxxxx.xxxx.at/home/auser/test.png --libcurl test.c --no-keepalive

and the output:
*   Trying xxx.xxx.xxx.xxx...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to apaoses02.apa.at (194.158.132.102) port 22 (#0)
* SSH MD5 fingerprint: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* SSH authentication methods available: publickey,gssapi-with-mic,password
* Using SSH public key file '(nil)'
* Using SSH private key file '/home/user//.ssh/id_rsa'
* SSH public key authentication failed: Unable to open public key file
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0* Initialized password authentication
* Authentication complete
  0  3319    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0} [0 bytes data]

**Comment by bagder** [comment]
Those are *awfully* old libssh2 and openssl versions you're using. I'd strongly urge you to upgrade - not only because of this problem.

If the problem remains with a modern libssh2, I'd be interested. Even if the problem then possibly need to be taken over to the libssh2 project...

**Comment by majestix508** [comment]
That's RHEL 5 :-) 
I'll try to recompile with the latest openssl and libssh2

**Comment by majestix508** [comment]
Ok
compiled openSSL .1.0.2c and libssh2 1.6.0
recompiled curl and this is the new output:

curl 7.42.1 (x86_64-unknown-linux-gnu) libcurl/7.42.1 OpenSSL/1.0.2c zlib/1.2.3 libidn/0.6.5 libssh2/1.6.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

Also my testprogram works now.

I struggled a bit on openSSL and libssh2 cause libssh2 needed the new openSSL and not the system openSSL. Both are now shared libs and I couldn't find a way to compile both static and link them with my exec. At the moment I must set LD_LIBRARY_PATH.....

**Comment by bagder** [comment]
Good news, thanks!
