### ISSUE TITLE
libcurl doesn't parse .netrc correctly when default is used

### ISSUE THREAD

**Issue by alvaropalmaaste** [bagder/curl#317]
I'm using libcurl along with this .netrc config file:

default login my_user password my_password

Which works fine when I use it from a regular FTP client.

However, when I use it from libcurl, the user is ignored and instead, anonymous is set:

* Couldn't find host XX.YY.ZZ.WW in the .netrc file; using defaults
* Hostname was NOT found in DNS cache
*   Trying XX.YY.ZZ.WW...
* Connected to XX.YY.ZZ.WW (XX.YY.ZZ.WW) port 21 (#0)
< 220 XX.YY.ZZ.WW FTP server (Version 5.60) ready.
> USER anonymous

**Comment by jay** [comment]
Thanks for your report, the [fix](https://github.com/bagder/curl/commit/48be87e) for that issue is in 7.43 which was just released.
