### ISSUE TITLE
Uninitialized garbage in error message

### ISSUE THREAD

**Issue by sneis** [bagder/curl#318]
If you look at lib/vtls/openssl.c there is an uninitialized char array error_buffer in ossl_connect_step2. If you look at the switch statement following the declatation of error_buffer, you may end in the code for ```case 0x14090086:``` which contains something like ```if (...) { /* set error_buffer */ } else cert_problem="SSL certificate problem, verify that the CA cert is OK" ;``` Note that if you get to the else part, error_buffer is not touched! Then right before the return you call ```failf(data, "%s%s", cert_problem ? cert_problem : "", error_buffer);``` which copies the uninitialized buffer right after the message about the certificate problem, so we get arbitrary "garbage" in the error output.

**Comment by bagder** [comment]
Thanks lot, fixed in 26ddc536b0
