### ISSUE TITLE
test suite fails in check-easy wrt CURLOPT_PIPEWAIT (7.43.0)

### ISSUE THREAD

**Issue by fenrus75** [bagder/curl#320]
.. contents:: :depth: 2
FAIL: check-easy
================
Missing CURLOPT_PIPEWAIT

**Comment by bagder** [comment]
Sorry, which test suite fails on this?

**Comment by fenrus75** [comment]
=========================================
   curl -: docs/libcurl/test-suite.log
=========================================
# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
.. contents:: :depth: 2
FAIL: check-easy
================
Missing CURLOPT_PIPEWAIT



the docs/libcurt one

**Comment by bagder** [comment]
Ah yes, thanks. Fixed now in commit 570076e82c9b4

**Comment by fenrus75** [comment]
thanks a lot for the fast repsonse!
will include the commit in our distro package
