### ISSUE TITLE
cURL "freezes" in Windows when drag scrollbar in console window

### ISSUE THREAD

**Issue by z0hm** [bagder/curl#322]
WinXPSP2 x32, curl 7.42.1.
Old bug. Open console - run cmd.exe, run curl.exe URL for download - if you pull the scrollbar, then curl freezes, traffic is interrupted, and then disconnects, if you hold for a while scrollbar to view the output in the console.

**Comment by bagder** [comment]
What does do exactly to make curl fail? Does it prevent/pause the writing to stdout? Isn't this a bug in Windows rather than in curl?

**Comment by z0hm** [comment]
I don't know. But this may not be a bug in the implementation of output to the console in CURL for Windows?
<a href="http://piccy.info/view3/8386516/350e9ce28c5942872a6d68df400338dc/" target="_blank"><img src="http://i.piccy.info/i9/eadb2ee08f9a8b359b2593a185563ce6/1435074445/37058/922948/2015_06_23_184546_500.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a>

**Comment by jay** [comment]
Windows console IO is blocking as far as I know though I recall there may be some workaround for reading. [WriteConsole](https://msdn.microsoft.com/en-us/library/windows/desktop/ms687401.aspx) is unable to write to the console while you have mousedown on the scrollbar or are selecting text or have selected text but not yet copied it. It's not specifically documented that way from what I see but that's the way it has behaved forever. It should be considered expected behavior in Windows for any program that outputs to the console and should not be considered a bug in curl.

**Comment by z0hm** [comment]
But why not make a workaround - stop the output in the console , so that traffic is not interrupted ? the user uses a scrollbar to see the old records in the console. And after the user releases the scrollbar to bring the latest information ( progress ) .

**Comment by jay** [comment]
If we are able in some reliable way to check the console to see if it's ok to write before writing there's still the possibility that when `WriteConsole` is called the status may have changed by then. So though we could skip a WriteConsole call that by itself wouldn't solve the issue unless we call WriteConsole (or whatever is calling it like fprintf) in a separate thread.

It's conceivable we could do some limited version of what you are suggesting by writing some of the [progress output](https://github.com/bagder/curl/blob/curl-7_43_0/lib/progress.c#L368-L489) to stderr from a separate thread. That's not a catch all but it would help at least. I'm not sure if it's worth the time though. I've reopened this as an enhancement, let's see if anyone else has an opinion.

**Comment by gvanem** [comment]
> But why not make a workaround - stop the output in the console , so that traffic is not interrupted ? 

Isn't the current process (i.e. curl) suspended when you drag the scrollbar? (Check with WinDbg, Process Explorer for example). Hence it would be nearly impossible for curl to *stop the output in the console*.
