### ISSUE TITLE
--show-error does not seem to work when also use --output.

### ISSUE THREAD

**Issue by jvvv** [bagder/curl#328]
Slackware-14.1,  updated to curl-7.43.0.
The command line:
<code>curl -s -S -o outputfile url</code>
shows no errors, even with erroneous url filespec. No output redirection used. I checked the resulting output file and found the errors written there. I expected the error to go to stderr, but instead the progress bar is showing up on stderr and stdout is empty. Am I reading the manual page correctly? I am trying to migrate from wget to curl, so perhaps I am confusing the issue by my past usage of wget. But I need to capture errors reliably, so any help would be greatly appreciated.

**Comment by jay** [comment]
Yes the progress bar if you choose to show it will be output to stderr. curl's `-o` is the output file for the resource you are retrieving whereas wget's `-o` is the output file to log what is normally sent to stderr (status including the progress etc).

The error message if you show it should be output to stderr as well... For example this is what happens for me using 7.43.0 in Windows 7 x64 and Ubuntu 14.04 x64 LTS. I suppressed stdout as you can see.
```
curl -s -S -o out does://not.exist 1>NUL
curl: (1) Protocol "does" not supported or disabled in libcurl
```
Can you try that command, or give me a command you've actually ran so I can try to reproduce it here? I need something that actually demonstrates the bug to investigate further so please give me a repro exactly as you've tried it.

**Comment by jvvv** [comment]
The command line I am using (generic form):

<code>curl -s -S -o outputfile url</code>

If I use your example, or anything similar with an unreal url, then the output arrives just the way you described: error messages to stderr and outputfile is empty.
But if there is a server response, then usually I see a 404 error in the outputfile and empty stderr.
This is what I get when I only mangle the mangle the source filename or part of the path to it.

A fully worked test case:

<code>curl -s -S -o curl-7.43.0.tar.bz2 http://curl.haxx.se/download/curl-7.43.0.tar.bz3</code>

Contents of outputfile (curl-7.43.0.tar.bz2):
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /download/curl-7.43.0.tar.bz3 was not found on this server.</p>
<hr>
<address>Apache/2.4.9 (Debian) Server at curl.haxx.se Port 80</address>
</body></html>
```

I wonder if the file descriptors are kept in an array, and maybe I'm seeing an index variable that's off by one?

**Comment by jay** [comment]
No that's no bug. You want the [`-f` switch](http://curl.haxx.se/docs/manpage.html#-f) probably.
```
>curl -f -s -S -o curl-7.43.0.tar.bz2 http://curl.haxx.se/download/curl-7.43.0.tar.bz3
curl: (22) The requested URL returned error: 404 Not Found
```

You can also do something like [`-w %{http_code}`](http://curl.haxx.se/docs/manpage.html#-w) to write the HTTP code to stdout if you needed to.

Please refer to the manual for more information. If you need more help with curl subscribe to the [curl-users mailing list](http://cool.haxx.se/mailman/listinfo/curl-users).

**Comment by jvvv** [comment]
Thanks so much for your help. The -f option is what I needed; the -w option looks to be very useful. Sorry to use your time this way. If I have any future issues, I will direct my questions to the mailing list first. I completely missed the -f and -w options. Very embarrassing, but done and can't be undone. Thanks again.
