### ISSUE TITLE
High CPU usage when using --limit-rate option

### ISSUE THREAD

**Issue by Konstantinusz** [bagder/curl#336]
On my VPS I am using cURL to serve files from file hosting services. I would like to limit the download speed to 320K so I used --limit-rate 320K. Unfortunately I experienced a reasonably high CPU usage when using this option, CPU was at 50% with one working thread, I used the command line utility "top" to examine CPU usage. If I omit this option CPU usage is only 1-2 % with one working thread.

**Comment by bagder** [comment]
Which curl version? What protocol did you download from?

**Comment by Konstantinusz** [comment]
curl 7.43.0 (i686-pc-linux-gnu) libcurl/7.43.0 OpenSSL/1.0.2a zlib/1.2.8 libidn/1.30 libssh2/1.5.0

I am downloading from simple http links which need cookie based authentication. My command line passed to the shell looks like: 
```
{ stdbuf -i0 -o0 -e0 curl $range --limit-rate 320K -b ./cookie.txt "$url" -L -o - 2>&1 1>&3 |stdbuf -i0 -o0 -e0 tr \"\r\" \"\n\"|sed -u -n '0~5p' 1>&2; } 3>&1
```
Earlier I used only this simpler command line with same result (high CPU usage):
```
curl $range --limit-rate 320K -b ./cookie.txt "$url" -L -o - 
```
It sends the downloaded data to the CGI program stdout with appropriate headers:
```
Content-Type: application/force-download
Content-Length: 249070398
Last-Modified: Thu, 16 Apr 2015 22:34:25 GMT
Connection: close
Content-Disposition: attachment; filename="viralvideo.avi"
```
So users can download the files as they would download from the file hosting service.

**Comment by jay** [comment]
FWIW I tried to reproduce using your simpler command in Windows 7 x64 and Ubuntu 14 x64 and I don't see an increase in CPU usage. Actually when I rate limit 320k I get the opposite effect in Ubuntu, the cpu usage is lower by at most several percentage points. (0-2%,avg 1 rate limited; 0-8%,avg 3 no limit). I also tried purposely slowing the pipe read, and later again using a lower rate limit, but in either case there was very little cpu difference.

~~~
curl 7.44.0-DEV (x86_64-unknown-linux-gnu) libcurl/7.44.0-DEV OpenSSL/1.0.2c zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
Linux ubuntu1404-x64-vm 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
~~~
The exact command I used:
~~~
curl --limit-rate 320K http://mirror.umd.edu/ubuntu-iso/15.04/ubuntu-15.04-desktop-i386.iso -L -o - | ./g
~~~
Where `g` is a program that did fread stdin at various buffer sizes and possible sleep. I also tried `>/dev/null` and the results were the same. Try piping to something else see what happens.

Worth mentioning that I did this in a VM which you can be sure had some effect on the results.

Also I don't follow how you're using `-I`, it seems like you'd want `-D` instead; unless you mean you're passing on just the headers back to the user separately or something.

**Comment by Konstantinusz** [comment]
Yes, you are right. I checked it again with issuing the cURL command line at a bash prompt, and the high CPU usage didn't appeared. I think maybe the CGI environment or Apache web server causes the high CPU usage somehow. This is a screenshot of htop utility showing that the CPU usage is at 98% for the cURL process: http://i.imgur.com/ZFj6Fqc.png
I made this screendhot when cURL was invoked by the CGI application and was running in the Apache webserver user account called "daemon".

**Comment by Konstantinusz** [comment]
And yes I am sending headers and file binary data separately. I simply capture the headers sent by the remote file hosting server and optional range request sent by remote client to my CGI app with commands (Ruby language):

```
range=ENV["HTTP_RANGE"]==nil ? "" : "-r #{ENV["HTTP_RANGE"].split("=")[1]}"
header=%x{curl #{range} -s -b ./cookie.txt "#{url}" -L -I}.force_encoding("utf-8").encode("utf-8").split("\r\n").last(7).join("\r\n")
if range !="" then
      header="Status: 206 Partial Content\r\n"+header
end
```

and then I simply send the headers I got from the file hosting service to the remote client by writing them to the CGI application's stdout followed by the binary file data immediately:

```
puts header
puts
system "{ stdbuf -i0 -o0 -e0 curl #{range} --limit-rate 320K -b ./cookie.txt \"#{ff_url}\" -L -o - 2>&1 1>&3 |stdbuf -i0 -o0 -e0 tr \"\r\" \"\n\"|sed -u -n '0~5p' 1>&2; } 3>&1"
```

**Comment by jay** [comment]
If you could clarify, you are able to reproduce using the simple command you quoted several posts back but only in the CGI script? What is the actual `system` line when you use the simple command? Did you try that from the shell? I suggest you eliminate as much as you can from the system line and see what happens. I'd also play around with different system lines to see if they have the same issue like `curl --limit-rate 320K http://mirror.umd.edu/ubuntu-iso/15.04/ubuntu-15.04-desktop-i386.iso -L -o - > /dev/null` and then check top and see if there's still a cpu problem. Basically work it until you can identify what is causing the high cpu.

**Comment by Konstantinusz** [comment]
I think the --limit-rate option causes the issue, because when I omit that option, the CPU usage is always nearly at 0%-0.8%. This is the screenshot of htop utility showing low CPU usage when I omitted the option --limit rate: http://i.imgur.com/KrNQlyr.png

Yes, I tried to call cURL simply from shell with both --limit-rate and without it, there were no high CPU usage in both cases.

Simple version of my cURL command line was (Ruby code):
```
system "curl #{range} -b ./cookie.txt \"#{url}\" -L -o -"
```

```
system "curl #{range} --limit-rate 320K -b ./cookie.txt \"#{url}\" -L -o -"
```

I experienced the high CPU usage only with the later which contains the option --limit-rate.

I also tried redirect stdout to a file at the server side, on my VPS and then using options -O -J as well to save the file at server side eliminating the use of stdout completely, but the result was the same in both cases, high CPU usage when using the --limit-rate option:
```
system "curl #{range} --limit-rate 320K -b ./cookie.txt \"#{url}\" -L -o - > videofile.bin"
```
```
system "curl #{range} --limit-rate 320K -b ./cookie.txt \"#{url}\" -L -O -J"
```

**Comment by bagder** [comment]
I'm trying this, and it works perfectly fine for me with a 0.3 CPU% usage

~~~~
curl http://localhost/4GB --limit-rate 320K -o /dev/null

**Comment by Konstantinusz** [comment]
I think the problem is I am using an outdated version of Apache, installed with an  ApacheFriends LAMPP package, which contains an outdated version of libcurl.so.4
but I haven't checked this yet.

**Comment by Konstantinusz** [comment]
Problem solved, I simply renamed the outdated libcurl.so.4.3.0 which was located in /opt/lampp/lib/ and now everything seems to be fine, I don't experience high CPU load, only 1.7-7 % which is quite acceptable on a VPS. On the top of that error messages referring libcurl also disappeared from the Apache error_log There were always a lot of "curl: /opt/lampp/lib/libcurl.so.4: no version information available (required by curl)" messages in error_log.

**Comment by bagder** [comment]
Thanks, we consider this fixed then!
