### ISSUE TITLE
libCurl segfaults when executing easy_perform

### ISSUE THREAD

**Issue by pscoe2** [bagder/curl#343]
Hi,

I am facing the below mentioned crash in libcurl. I am attaching the crash stack and the calling code for your reference. 

libCurl Version: 7.39.0
OS Version:            Mac OS X 10.10.3 (14D136)
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT

Stack Trace:
0   libsystem_platform.dylib      	0x00007fff8d15bb13 _platform_strcmp + 19
1   libsystem_info.dylib          	0x00007fff871dd9a8 _mdns_hostent_append_alias + 67
2   libsystem_info.dylib          	0x00007fff871dd4be _mdns_query_callback + 248
3   libsystem_dnssd.dylib         	0x00007fff8f687c9b handle_query_response + 243
4   libsystem_dnssd.dylib         	0x00007fff8f6861b8 DNSServiceProcessResult + 680
5   libsystem_info.dylib          	0x00007fff871dc8c4 _mdns_search + 1602
6   libsystem_info.dylib          	0x00007fff871e1875 mdns_addrinfo + 692
7   libsystem_info.dylib          	0x00007fff871e1581 search_addrinfo + 179
8   libsystem_info.dylib          	0x00007fff871d9f7e si_addrinfo + 1395
9   libsystem_info.dylib          	0x00007fff871d9967 getaddrinfo + 179
10  se.haxx.curl.libcurl          	0x0000000110a465d9 Curl_getaddrinfo_ex + 40
11  se.haxx.curl.libcurl          	0x0000000110a42407 Curl_getaddrinfo + 267
12  se.haxx.curl.libcurl          	0x0000000110a19276 Curl_resolv + 243
13  se.haxx.curl.libcurl          	0x0000000110a1936e Curl_resolv_timeout + 119
14  se.haxx.curl.libcurl          	0x0000000110a2bcc3 create_conn + 11389
15  se.haxx.curl.libcurl          	0x0000000110a2bea1 Curl_connect + 37
16  se.haxx.curl.libcurl          	0x0000000110a3df3f multi_runsingle + 712
17  se.haxx.curl.libcurl          	0x0000000110a3f2c0 curl_multi_perform + 163
18  se.haxx.curl.libcurl          	0x0000000110a377b4 curl_easy_perform + 394

Calling code:

        CURL *curl = curl_easy_init();
	long longinfo = 400; // BAD REQUEST if we have error on client side

	if(curl) {
		if(mProxy.length())
			curl_easy_setopt(curl,CURLOPT_PROXY, mProxy.c_str());

		StreamCallbackData callbackData;
		callbackData.outputStream = outstream;

		curl_easy_setopt(curl, CURLOPT_URL, url.c_str());
		curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, DataStreamCallback);
        #if Macintosh
		//Take care of timeouts as we are setting curl for no signal
		curl_easy_setopt(curl, CURLOPT_NOSIGNAL, 1L); //No SIGALRM
		curl_easy_setopt(curl, CURLOPT_FTP_RESPONSE_TIMEOUT, 20L);
         #endif
		// Setting 20 second network timeout
		curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT, 20L);
		
		// Download speed must not be less than 100b/sec for 10 seconds
		curl_easy_setopt(curl, CURLOPT_LOW_SPEED_LIMIT, 100);
		curl_easy_setopt(curl, CURLOPT_LOW_SPEED_TIME, 10);
		curl_easy_setopt(curl, CURLOPT_WRITEDATA, (void *)&callbackData);

		CURLcode res = curl_easy_perform(curl);

		if(res == 0)
		{
			curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &longinfo);
		}
		curl_easy_cleanup(curl);
		}
	return longinfo;

**Comment by bagder** [comment]
Can you please provide a full stand-alone source code that triggers this problem? I would also imagine that the exact URL you use will be a factor here. Have you tried with the latest version?

**Comment by pscoe2** [comment]
Hi Daniel,

I haven't tried this in the latest version of libcurl, but the problem I am facing is intermittent and happens rarely and randomly, thus it is hard to point out the exact URL which causes this. 
I did check that only one thread was calling libcurl when the application crashed. It wasn't the main thread though.
Can this be because of a libcurl being called in a thread other than main?
What other part of code can I post in helping resolve the problem. The data writing function or something else?

**Comment by bagder** [comment]
I need a way to reproduce or I need a lot more details about the specific crashes you see. Those "more details" could for example include all function arguments in that stack trace - consider building debug-enabled (without optimization) so that you have more symbols left to ease this.

**Comment by bagder** [comment]
No response, closing.
