### ISSUE TITLE
SIGSEGV in multi.c

### ISSUE THREAD

**Issue by TommyOswald** [bagder/curl#344]
At HP we are running cURL 7.42.1 in our firmware.  We get the following crash:

      if(!(k->keepon & KEEP_SEND)) {
        /* We're done sending */
        data->easy_conn->writechannel_inuse = FALSE;  <--- L1523 where the crash occurs.
      }

I am thinking it is a cleanup issue, i.e., we have already called curl_easy_cleanup() with our cURL handle and the above line of code is executed afterwords.

Any information regarding this issue or related issues would be greatly appreciated.

Test Regards,

Tom

**Comment by bagder** [comment]
Can you help us reproduce the problem?

**Comment by TommyOswald** [comment]
Hi Daniel,

We have a complicated test environment that is not at this location.  In short, no.  However, in looking at our implementation, I am running curl_easy_perform() in a pthread, but calling curl_easy_cleanup() in a separate thread.  I am in process of changing that so curl_easy_cleanup() is called in the pthread after curl_easy_perform() exists.  I am thinking this may fix it.

Your thoughts?

Best Regards,

Tom

**Comment by bagder** [comment]
I think it sounds like a good theory!
