### ISSUE TITLE
curl_multi_fdset not able to set write_fd_set while sending large string(1.3mb) over HTTPS on IOS

### ISSUE THREAD

**Issue by motobhakta** [bagder/curl#350]
Approx after 60 iteration curl_multi_fdset not able to set write_fd_set anymore, hence 
select(n + 1, &rfd, &wfd, &efd, &tv) always returns 0 on IOS. Any patch for this kind of issue earlier ?

**Comment by bagder** [comment]
Please give us more details to allow us to repeat this problem. Does the curl tool work for this task? Which curl version are you using?

**Comment by motobhakta** [comment]
The code snippet is as follows 
https://github.com/rhomobile/rhodes/blob/master/platform/shared/net/CURLNetRequest.cpp#L820-L851

Have not tried yet using curl tool, never pasted 1.3 mb of string in console ...

**Comment by bagder** [comment]
curl can read from a file...

**Comment by bagder** [comment]
Can you try to write a separate stand-alone example that only serves to repeat the problem against a public URL or a local test server so that I can build and run it locally?

**Comment by bagder** [comment]
No response, closing.

**Comment by patrikhson** [comment]
Hey,
Here are some useful links that I've chosen just for you, check it out <http://stirdardoshi.instantappnow.com/xywkox>

paf@frobbit.se
