### ISSUE TITLE
Add curl_multi_wait to the multi interface overview

### ISSUE THREAD

**Issue by tstack** [bagder/curl#356]
The multi interface overview documentation (http://curl.haxx.se/libcurl/c/libcurl-multi.html) talks about the fdset and socket action mechanisms, but doesn't mention the "new" curl_multi_wait() function.  I spent awhile getting the socket action stuff to work and then stumbled on the wait() function by accident.  It would've been nice to not spend the time on the first approach ;)

**Comment by bagder** [comment]
Oh, good point! I'll add something...
