### ISSUE TITLE
Make up to date CHANGES log available via URL

### ISSUE THREAD

**Issue by mc0e** [bagder/curl#364]
I certainly can see that editing the CHANGES file by hand is tedious, and inferior to producing it from the git log, but it's also a bit tedious to have to download the entire repository and run a script in order to check when something was fixed.

Could we have an automated process whereby the change log is produced on a regular basis and uploaded some place accessible.  E.g. maybe on git.io.  Maybe even fire the updates off a web hook?

**Comment by bagder** [comment]
While we don't exactly provide the generated file online right now, we do offer some that are almost that: http://curl.haxx.se/dev/sourceactivity.html is the last (100?) commits and http://curl.haxx.se/dev/release-notes.html is the RELEASE-NOTES of the pending release that we sync every now and then so that it is generally fairly in sync with what is in current git/daily snapshots.

**Comment by bagder** [comment]
Would you consider those good enough or you think we should make the actual generated CHANGES one available too?

**Comment by mc0e** [comment]
Given that I know about an issue that has been fixed here, I want to know in what release version it was fixed, to make sense of what OS dist

**Comment by bagder** [comment]
Most people use http://curl.haxx.se/changes.html for that. It is slightly more high level and filtered to reduce the noise of the CHANGES list.

**Comment by mc0e** [comment]
That's good stuff.  Can a reference to that be put at the top of the CHANGES file here?

**Comment by bagder** [comment]
A good idea indeed, fixed now!

**Comment by mc0e** [comment]
Excellent.

**Comment by mc0e** [comment]
http://curl.haxx.se/dev/sourceactivity.html and http://curl.haxx.se/dev/release-notes.html might be worth a mention as well?

**Comment by bagder** [comment]
I figured it would be a bit messy especially since the CHANGES file is not html. Those pages are already mentioned in the "related" box on that changelog page
