### ISSUE TITLE
Please add --no-progress option.

### ISSUE THREAD

**Issue by codearoo** [bagder/curl#367]
I run from a script and it still outputs this progress. The environment I'm running it from logs each change in the STDIO on a separate line, and so progress takes up a lot of lines.

There is mention in the manual about how it somehow would figure out when it should not, but it's not working. Need an option to stop it.

**Comment by bagder** [comment]
~~~
       -s, --silent
              Silent  or  quiet  mode. Don't show progress meter or error mes‐
              sages.  Makes Curl mute. It will still output the data  you  ask
              for, potentially even to the terminal/stdout unless you redirect
              it.

**Comment by codearoo** [comment]
silent sadly is not an option.

Because in this case I actually am waiting for a response from the curl command. And --silent  prevents outputting that.

**Comment by bagder** [comment]
No, --silent inhibits the extra outputs to stderr. curl will still write the actual stuff that comes from the remote server.

**Comment by codearoo** [comment]
OH IT DID!!!!  SORRY..  the output in one case was not noticeable.
