### ISSUE TITLE
Odd error message when attempting HEAD request with a body

### ISSUE THREAD

**Issue by daurnimator** [bagder/curl#397]
This error message doesn't really make sense:
```
$ curl -v -I http://127.0.0.1:8000/  -d hi
Warning: You can only select one HTTP request!
```

(infact, I expect the operation to work; though I can understand if it's too much of a corner case)

Trying to do this via `-X` instead of `-I` results in:
```
$ curl -v http://127.0.0.1:8000/ -d hi -X HEAD
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> HEAD / HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: curl/7.44.0-DEV
> Accept: */*
> Content-Length: 2
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 2 out of 2 bytes
< HTTP/1.1 200 OK
< server: lua-http
< content-type: text/plain
< date: Mon, 24 Aug 2015 02:12:57 GMT
< content-length: 2
< 
^C
```
That `^C` is me cancelling it due to hanging, I assume waiting for the response body.

**Comment by bagder** [comment]
Yeah, I would say you found a HTTP request setup curl really cannot perform without waiting for a response.. -I makes a HEAD and sends no body, -d makes a POST with a body. Both allow the method to be changed, but of course the HEAD request doesn't send data and changing the post to send a HEAD method will still make it wait for the response.

Then again, I don't see what good a HEAD with a request-body would do?

**Comment by onecityuni** [comment]
If you're getting "Error 124"
try the solutions below:

Error 101 (net::ERR_CONNECTION_RESET)
Error 2 (net::ERR_FAILED): Unknown error
Error 104 (net::ERR_CONNECTION_FAILED)
Error 105 (net::ERR_NAME_NOT_RESOLVED)
Error 102 (net::ERR_CONNECTION_REFUSED): Unknown error
Error 324 (net::ERR_EMPTY_RESPONSE)
Check for malware
Clear your cookies
check your antivirus and firewall settings and or adjust your proxy settings

love fanny

**Comment by bagder** [comment]
@onecityuni : sorry, but how is that relevant here?

**Comment by daurnimator** [comment]
> Then again, I don't see what good a HEAD with a request-body would do?

I'm writing my own http library and validating it against other implementations; ran into this curl issue.

There's nothing that says you can't send a body with a HEAD (or GET) request.
From RFC 7231:
> A payload within a HEAD request message has no defined semantics; sending a payload body on a HEAD request might cause some existing implementations to reject the request.

In terms of a real life example, I remember once running into some server that had a max length for the status line, and people got around it by sending the query params in the body (for a GET request). I can see it as reasonable to want to perform a HEAD request to match that GET request.

**Comment by bagder** [comment]
HTTP doesn't allow you to move things from the status line to the request-body though, that's just a work-around for a broken implementation.

I agree that HTTP in itself doesn't forbid HEAD with a request-body, I'm just saying that you'll have to search pretty good to find a server that wants this. After all, you're the first person asking for this in curl for about 18 years.

So before I proceed and do anything I wanted to understand the use-case to see if this was actually a real concern.

**Comment by daurnimator** [comment]
> I agree that HTTP in itself doesn't forbid HEAD with a request-body, I'm just saying that you'll have to search pretty good to find a server that wants this. After all, you're the first person asking for this in curl for about 18 years.

Indeed. Hence why I made the bug report about the confusing error message, rather than a feature request :)

**Comment by bagder** [comment]
Well, the error message is still technically correct because -d implies POST and -I implies HEAD and they cannot be used in a single request...

**Comment by daurnimator** [comment]
Ah, I misunderstood the error message

**Comment by bagder** [comment]
I've improved that message a bit now at least

**Comment by daurnimator** [comment]
> I've improved that message a bit now at least

FTR, that was done in ce034356d2fc9ac94bca4959a4054169129bf5d8
I don't suppose you could list the conflicting options in the error message?

It wasn't clear to me that `-d` would turn on 'POST mode': I thought it would just add a body.

**Comment by bagder** [comment]
A very good idea! Commit 4a889441d3 has spells out which specific options that were used that are conflicting.

**Comment by daurnimator** [comment]
That solves the issue for now (fixing the error message).
I'll leave it up to you to decide if you want to actually support the use case I was trying i.e. HEAD request with a body.
