### ISSUE TITLE
How to use CURLOPT_TLSAUTH_TYPE(3) ?

### ISSUE THREAD

**Issue by frgm** [bagder/curl#413]
from [CURLOPT_TLSAUTH_TYPE(3)](http://curl.haxx.se/libcurl/c/CURLOPT_TLSAUTH_TYPE.html):
`CURLcode curl_easy_setopt(CURL *handle, CURLOPT_TLSAUTH_TYPE, long bitmask); `

but [here](https://github.com/bagder/curl/blob/9756d1da7637d1913b7ca2b589e4635f32ed3e00/lib/url.c#L2613) (lib/url.c):
`if(strnequal((char *)va_arg(param, char *), "SRP", strlen("SRP")))`
i.e. it accepts string ?

There should be 
`data->set.ssl.authtype = va_arg(param, long);` ?

**Comment by frenche** [comment]
Looks right.

In my opinion we should remove this option all together and change CURLOPT_TLSAUTH_USERNAME to CURLOPT_TLSSRP_USERNAME (same for pwd).

**Comment by bagder** [comment]
@frenche what would we gain with that?

We can't actually _remove_ anything without breaking backwards compatibility, but we can add new names/aliases and promote for future users.

**Comment by bagder** [comment]
@frgm yes you're right. Quite clearly the documentation is wrong and it accepts nothing but a string. Will you do a PR for it?

**Comment by frenche** [comment]
@bagder - simplicity for the users and easier maintenance of the code.

This parameter will probably never hold anything else but SRP.
Given the doc was wrong and given SRP has its own problems[1] I thought it is a good opportunity to get rid of it once and for all (as I doubt it will break anything).

[1] http://tiebing.blogspot.co.il/2013/09/tls-psk-tls-srp-and-tls-jpake.html

**Comment by frgm** [comment]
@bagder is https://github.com/bagder/curl/pull/414/ OK ?

**Comment by bagder** [comment]
@frenche I just don't see what we gain by changing this and risk breaking things for a few users.

I closed this since this issue is now fixed. Thanks @frgm !
