### ISSUE TITLE
CURLOPT_PROXY: IPv6 address without port

### ISSUE THREAD

**Issue by MarcelRaad** [bagder/curl#415]
The following code doesn't work:
```
curl_easy_setopt(easy_handle, CURLOPT_PROXY, "2a00:fac0:a000::7:13");
curl_easy_setopt(easy_handle, CURLOPT_PROXYPORT, 8080L);
```

url.c:parse_proxy sets the proxy name to "2a00" and overrides the port with 0, as it tries to parse "fac0:a000::7:13" as a port number. Is this a bug or expected behavior?

Unfortunately the documentation at http://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html doesn't mention if IPv6 addresses have to be in square brackets even if they don't contain a port number or a scheme. If so, probably the documentation should reflect that and parse_proxy should return an error if the port string is invalid.

**Comment by bagder** [comment]
Thanks! I completely agree. I have a fix that makes the parser stricter and adds the bracket requirement to the man page, will push in a second.

**Comment by MarcelRaad** [comment]
Great, thank you!
