### ISSUE TITLE
libcurl crash in android cause Curl_cookie_add {free(clist->name);}

### ISSUE THREAD

**Issue by KingsleyYau** [bagder/curl#416]
Using libcurl in Android
crash in 
~~~
/* then free all the old pointers */
free(clist->name);
~~~
version:curl-7.42.0

core stack:
~~~
 4  libhttprequest.so!Curl_cookie_add [cookie.c : 826 + 0xb]
     sp = 0x62deb678    pc = 0x60a050d5
    Found by: stack scanning
 5  libhttprequest.so!Curl_cookie_init [cookie.c : 941 + 0xb]
     r4 = 0x60e59308    r5 = 0x00000000    r6 = 0x5d52ae00    r7 = 0x40211e34
     r8 = 0x60e73eb8    r9 = 0x60b3cd6c   r10 = 0x60b85cd0    fp = 0x00000001
     sp = 0x62debb00    pc = 0x60a05b3f
    Found by: call frame info
 6  libhttprequest.so!Curl_cookie_loadfiles [cookie.c : 265 + 0xf]
     r4 = 0x60e73eb8    r5 = 0x63767330    r6 = 0x60b3cd78    r7 = 0x60e7c3b8
     r8 = 0x60e73eb8    r9 = 0x62debb88   r10 = 0x60b3b9b4    fp = 0x60e7c505
     sp = 0x62debb30    pc = 0x60a05c37
    Found by: call frame info
 7  libhttprequest.so!Curl_pretransfer [transfer.c : 1322 + 0x5]
     r4 = 0x60e73eb8    r5 = 0x00000000    r6 = 0x60e7c4b8    r7 = 0x60e7c3b8
     r8 = 0x60e73eb8    r9 = 0x62debb88   r10 = 0x60b3b9b4    fp = 0x60e7c505
     sp = 0x62debb40    pc = 0x60a11021
    Found by: call frame info
 8  libhttprequest.so!multi_runsingle [multi.c : 1044 + 0x5]
     r3 = 0xfffffffd    r4 = 0x63767720    r5 = 0x00000000    r6 = 0x60b3ba04
     r7 = 0x00000000    r8 = 0x60e73eb8    r9 = 0x62debb88   r10 = 0x60b3b9b4
     fp = 0x60e7c505    sp = 0x62debb58    pc = 0x60a00a4d
    Found by: call frame info
 9  libhttprequest.so!curl_multi_perform [multi.c : 1791 + 0xb]
     r4 = 0x60e73eb8    r5 = 0x60e7c540    r6 = 0x62debbcc    r7 = 0x63767720
     r8 = 0x00000000    r9 = 0x62debbd4   r10 = 0x62debc24    fp = 0x62debc24
     sp = 0x62debbc8    pc = 0x60a01333
    Found by: call frame info
10  libhttprequest.so!curl_easy_perform [easy.c : 715 + 0x7]
     r4 = 0x63767720    r5 = 0x60e73eb8    r6 = 0x62debc2c    r7 = 0x62debc28
     r8 = 0x00000000    r9 = 0x00000001   r10 = 0x62debc34    fp = 0x62debc24
     sp = 0x62debc10    pc = 0x609fe25f
    Found by: call frame info
11  libhttprequest.so!HttpClient::Request [HttpClient.cpp : 411 + 0x3]
     r4 = 0x62debd0c    r5 = 0x62debcf4    r6 = 0x62debcb4    r7 = 0x62debcb0
     r8 = 0x00000000    r9 = 0x638c6358   r10 = 0x638c6358    fp = 0x638c6240
     sp = 0x62debc78    pc = 0x609f6003
    Found by: call frame info
12  libhttprequest.so!HttpRequestRunnable::onRun [HttpRequest.cpp : 22 + 0x3]
     r4 = 0x40208384    r5 = 0x60e37a20    r6 = 0x638c63a8    r7 = 0x638c62c0
     r8 = 0x609f8a61    r9 = 0x62cee000   r10 = 0x638c62cc    fp = 0x402062ec
     sp = 0x62debd50    pc = 0x60999c87
~~~

**Comment by KingsleyYau** [comment]
I link libcurl with static library in android app, sometimes app will crash cause Curl_cookie_add().
How can I fixed it?

**Comment by bagder** [comment]
I can't see how that can happen. I think you need to help us with some input that causes a problem. Like more details about what Curl_cookie_add() gets passed.

**Comment by KingsleyYau** [comment]
I call it like this, with cookies files

/*
 * HttpClient.cpp
 *
 *  Created on: 2014-12-24
 *      Author: Max.Chiu
 *      Email: Kingsleyyau@gmail.com
 */

#include "HttpClient.h"

#include <jni.h>
#include <openssl/ssl.h>

#include <common/command.h>
#include <common/KLog.h>
#include <common/KMutex.h>

//#define COOKIES_FILE "/sdcard/qpidnetwork/cookie"
#define DEVICE_ANDROID_TYPE "device_type: 30"
#define DEVICE_IPHONE_TYPE "device_type: 31"
#define USER_AGENT	"Mozil1a/4.0 (compatible; MS1E 7.0; Windows NT 6.1; WOW64; )"

#define DWONLOAD_TIMEOUT 30

CURLSH *sh;
string COOKIES_FILE = "/sdcard/qpidnetwork/cookie";

///* JNI_OnLoad */
//jint JNI_OnLoad(JavaVM* vm, void* reserved) {
//	FileLog("httpclient", "JNI_OnLoad( httpclient.so JNI_OnLoad )");
//
//	// Get JNI
//	JNIEnv* env;
//	if (JNI_OK != vm->GetEnv(reinterpret_cast<void**> (&env),
//                           JNI_VERSION_1_4)) {
//		FileLog("httpclient", "JNI_OnLoad( could not get JNI env )");
//		return -1;
//	}
//
//	curl_global_init(CURL_GLOBAL_ALL);
//	curl_version_info_data *data = curl_version_info(CURLVERSION_FIRST);
//
//	if( data->version != NULL ) {
//		FileLog("httpclient", "JNI_OnLoad( curl_version : %s )", data->version);
//	}
//
//	if( data->ssl_version != NULL ) {
//		FileLog("httpclient", "JNI_OnLoad( ssl_version : %s )", data->ssl_version);
//	}
//
//	sh = curl_share_init();
//	curl_share_setopt(sh, CURLSHOPT_SHARE, CURL_LOCK_DATA_COOKIE);
//
//	return JNI_VERSION_1_4;
//}

void HttpClient::Init() {
	curl_global_init(CURL_GLOBAL_ALL);
	curl_version_info_data *data = curl_version_info(CURLVERSION_FIRST);

	if( data->version != NULL ) {
		FileLog("httpclient", "Init( curl_version : %s )", data->version);
	}

	if( data->ssl_version != NULL ) {
		FileLog("httpclient", "Init( ssl_version : %s )", data->ssl_version);
	}

	sh = curl_share_init();
	curl_share_setopt(sh, CURLSHOPT_SHARE, CURL_LOCK_DATA_COOKIE);
}

void HttpClient::SetLogDirectory(string directory) {
	KLog::SetLogDirectory(directory);
	FileLog("httpclient", "SetLogDirectory( directory : %s )", directory.c_str());

	curl_version_info_data *data = curl_version_info(CURLVERSION_FIRST);

	if( data->version != NULL ) {
		FileLog("httpclient", "SetLogDirectory( curl_version : %s )", data->version);
	}

	if( data->ssl_version != NULL ) {
		FileLog("httpclient", "SetLogDirectory( ssl_version : %s )", data->ssl_version);
	}
}

void HttpClient::SetLogEnable(bool enable) {
	KLog::SetLogEnable(enable);
}

HttpClient::HttpClient() {
	// TODO Auto-generated constructor stub
	mpIHttpClientCallback = NULL;
	mpCURL = NULL;
	mUrl = "";
	mContentType = "";
}

HttpClient::~HttpClient() {
	// TODO Auto-generated destructor stub
}

void HttpClient::SetCookiesDirectory(string directory) {
	COOKIES_FILE = directory;
	COOKIES_FILE += "/cookie";
}

void HttpClient::CleanCookies() {
	FileLog("httpclient", "HttpClient::CleanCookies()");
	remove(COOKIES_FILE.c_str());
	CURL *curl = curl_easy_init();
	curl_easy_setopt(curl, CURLOPT_SHARE, sh);
	curl_easy_setopt(curl, CURLOPT_COOKIELIST, "ALL");
	curl_easy_cleanup(curl);
}

void HttpClient::CleanCookies(string site) {

}

string HttpClient::GetCookies(string site) {
	string cookie = "";
	FileLog("httpclient", "HttpClient::GetCookies( site : %s )", site.c_str());

	CURL *curl = curl_easy_init();
	curl_easy_setopt(curl, CURLOPT_URL, site.c_str());
	curl_easy_setopt(curl, CURLOPT_SHARE, sh);

	CURLcode res;
	struct curl_slist *cookies = NULL;
	struct curl_slist *next = NULL;
	int i;

	res = curl_easy_getinfo(curl, CURLINFO_COOKIELIST, &cookies);
	if (res == CURLE_OK) {
		next = cookies, i = 0;
		while ( next != NULL ) {
			FileLog("httpclient", "HttpClient::GetCookies( cookies[%d] : %s )", i++, next->data);

			/**
			 *
			 * www.example.com :	The domain that the cookie applies to
    		 * FALSE :				can other webservers within www.someURL.com access this cookie?
    		 * 						If there was a webserver at xxx.www.someURL.com, could it see this cookie?
    		 * 						If the domain begin with \u201c.\u201d, this value is TRUE
			 * / :					more restrictions on what paths on www.someURL.com can see this cookie.
			 * 						Anything here and under can see the cookie. / is the least restrictive,
			 * 						meaning that any (and all) requests from www.someURL.com get the cookie header sent.
    		 * FALSE :				Do we have to be coming in on https to send the cookie?
    		 * 0 :					expiration time. zero probably means that it never expires,
    		 * 						or that it is good for as long as this session lasts.
    		 * 						A number like 1420092061 would correspond to a number of seconds since the epoch (Jan 1, 1970).
    		 * 						If this value equal to 0, cookie don\u2019t expire
    		 * CNAME :				The name of the cookie variable that will be send to the server.
    		 * value :				cookie value that will be sent. Might be comma separated list of terms,
    		 * 						or could just be a word.. Hard to say. Depends on the server.
			 *
			 */
			int j = 0;
			bool bFlag = false;
			char *p = strtok(next->data, "\t");
			while(p != NULL) {
//				FileLog("httpclient", "HttpClient::GetCookies( p[%d] : %s )", j, p);
				switch(j) {
				case 0:{
					if( strcmp(p, site.c_str()) != 0 ) {
						// not current site
						bFlag = true;
					}
				}break;
				case 5:{
					cookie += p;
					cookie += "=";
				}break;
				case 6:{
					cookie += p;
					cookie += ";";
				}break;
				default:break;
				}

				if( bFlag ) {
					break;
				}

				j++;
				p = strtok(NULL, "\t");
			}

			next = next->next;
		}

		if( cookies != NULL ) {
			curl_slist_free_all(cookies);
		}
	}
	curl_easy_cleanup(curl);

	FileLog("httpclient", "HttpClient::GetCookies( cookie : %s )", cookie.c_str());

	return cookie;
}

void HttpClient::SetCallback(IHttpClientCallback *callback){
	mpIHttpClientCallback = callback;
}

string HttpClient::GetUrl() const {
	return mUrl;
}
string HttpClient::GetContentType() const
{
	return mContentType;
}

// 获取上传ContentLength
double HttpClient::GetUploadContentLength() const
{
//	double dContentLength = 0.0;
//	CURLcode res = curl_easy_getinfo(mpCURL, CURLINFO_CONTENT_LENGTH_UPLOAD, &dContentLength);
//	if (res != CURLE_OK) {
//		dContentLength = 0.0;
//	}
	return mdUploadTotal;
}

// 获取已上传的数据长度
double HttpClient::GetUploadDataLength() const
{
//	double dUploadDataLength = 0.0;
//	CURLcode res = curl_easy_getinfo(mpCURL, CURLINFO_SIZE_UPLOAD, &dUploadDataLength);
//	if (res != CURLE_OK) {
//		dUploadDataLength = 0.0;
//	}
	return mdUploadLast;
}

// 获取下载ContentLength
double HttpClient::GetDownloadContentLength() const
{
//	double dContentLength = 0.0;
//	CURLcode res = curl_easy_getinfo(mpCURL, CURLINFO_CONTENT_LENGTH_DOWNLOAD, &dContentLength);
//	if (res != CURLE_OK) {
//		dContentLength = 0.0;
//	}
	return mdDownloadTotal;
}

// 获取已下载的数据长度
double HttpClient::GetDownloadDataLength() const
{
//	double dDownloadDataLength = 0.0;
//	CURLcode res = curl_easy_getinfo(mpCURL, CURLINFO_SIZE_DOWNLOAD, &dDownloadDataLength);
//	if (res != CURLE_OK) {
//		dDownloadDataLength = 0.0;
//	}
	return mdDownloadLast;
}

void HttpClient::Stop() {
	FileLog("httpclient", "HttpClient::Stop()");

	mUrl = "";
	mbStop = true;
}

void HttpClient::Init(string url) {
	FileLog("httpclient", "HttpClient::Init( url : %s )", url.c_str());
	mUrl = url;
}

bool HttpClient::Request(const HttpEntiy* entiy) {
	FileLog("httpclient", "HttpClient::Request( url : %s, entiy : %p )",
			mUrl.c_str(), entiy);
	bool bFlag = true;

	CURLcode res;

	mContentType = "";
	mContentLength = -1;

	mbStop = false;
	mdUploadTotal = -1;
	mdUploadLast = -1;
	mdUploadLastTime = -1;
	mdDownloadTotal = -1;
	mdDownloadLast = -1;
	mdDownloadLastTime = -1;

	if( mpCURL == NULL ) {
		mpCURL = curl_easy_init();
	}

	curl_easy_setopt(mpCURL, CURLOPT_URL, mUrl.c_str());
	curl_easy_setopt(mpCURL, CURLOPT_SHARE, sh);

	// 处理http body函数
	curl_easy_setopt(mpCURL, CURLOPT_WRITEFUNCTION, CurlHandle);
	curl_easy_setopt(mpCURL, CURLOPT_WRITEDATA, this);

	// deal with progress
	curl_easy_setopt(mpCURL, CURLOPT_NOPROGRESS, 0L);
	curl_easy_setopt(mpCURL, CURLOPT_PROGRESSFUNCTION, CurlProgress);
	curl_easy_setopt(mpCURL, CURLOPT_PROGRESSDATA, this);

	string host = mUrl;
	std::size_t index = mUrl.find("http://");
	if( index != string::npos ) {
		host = host.substr(strlen("http://"), host.length() - strlen("http://"));
		index = host.find("/");
		if( index != string::npos ) {
			host = host.substr(0, index);
		}
	}

	string cookie = GetCookies(host);
	FileLog("httpclient", "HttpClient::Request( Cookie Send : %s )", cookie.c_str());
	// Send cookies
	curl_easy_setopt(mpCURL, CURLOPT_COOKIEFILE, COOKIES_FILE.c_str());

	//	curl_easy_setopt(mpCURL, CURLOPT_FOLLOWLOCATION, 1);
	// 设置连接超时
	curl_easy_setopt(mpCURL, CURLOPT_CONNECTTIMEOUT, 20L);
//	// 设置执行超时
//	curl_easy_setopt(mpCURL, CURLOPT_TIMEOUT, 30L);
	// 设置不抛退出信号量
	curl_easy_setopt(mpCURL, CURLOPT_NOSIGNAL, 1L);

	// add by samson 2015-03-18 增加公共http User-Agent
	curl_easy_setopt(mpCURL, CURLOPT_USERAGENT, USER_AGENT);

	if( entiy != NULL ) {
		if( !entiy->mIsGetMethod ) {
			curl_easy_setopt(mpCURL, CURLOPT_POST, 1);
		}

		if( entiy->mbSaveCookie ) {
			// Save cookies
			curl_easy_setopt(mpCURL, CURLOPT_COOKIEJAR, COOKIES_FILE.c_str());
		}

		FileLog("httpclient", "HttpClient::Request( mIsGetMethod : %s, mbSaveCookie : %s)",
				entiy->mIsGetMethod?"true":"false", entiy->mbSaveCookie?"true":"false");

	}

	// 处理https
	if( mUrl.find("https") != string::npos ) {
		FileLog("httpclient", "HttpClient::Request( try to connect with ssl )");
		// 不检查服务器证书
		curl_easy_setopt(mpCURL, CURLOPT_SSL_VERIFYPEER, 0L);
		curl_easy_setopt(mpCURL, CURLOPT_SSL_VERIFYHOST, 0);
		// 不设置客户端证书和私钥
//		curl_easy_setopt(mpCURL, CURLOPT_SSLCERTTYPE, "PEM");
//		curl_easy_setopt(mpCURL , CURLOPT_SSL_CTX_FUNCTION, Curl_SSL_Handle);
//		curl_easy_setopt(mpCURL , CURLOPT_SSL_CTX_DATA, this);
	}

	struct curl_slist* pList = NULL;
	struct curl_httppost* pPost = NULL;
	struct curl_httppost* pLast = NULL;

	if( entiy != NULL ) {
		/* Basic Authentication */
		if( entiy->mAuthorization.length() > 0 ) {
			curl_easy_setopt(mpCURL, CURLOPT_USERPWD, entiy->mAuthorization.c_str());
			FileLog("httpclient", "HttpClient::Request( Add authentication header : [%s] )", entiy->mAuthorization.c_str());
		}

		/* Headers */
		for( HttpMap::const_iterator itr = entiy->mHeaderMap.begin(); itr != entiy->mHeaderMap.end(); itr++ ) {
			string header = itr->first + ": " + itr->second;
			pList = curl_slist_append(pList, header.c_str());
			FileLog("httpclient", "HttpClient::Request( Add header : [%s] )", header.c_str());
		}
		// add by Samson 2015-04-23, add "device_type" to http header
		pList = curl_slist_append(pList, DEVICE_ANDROID_TYPE);

		/* Contents */
		for( HttpMap::const_iterator itr = entiy->mContentMap.begin(); itr != entiy->mContentMap.end(); itr++ ) {
			curl_formadd(&pPost, &pLast, CURLFORM_COPYNAME, itr->first.c_str(),
					CURLFORM_COPYCONTENTS, itr->second.c_str(), CURLFORM_END);
			FileLog("httpclient", "HttpClient::Request( Add content : [%s : %s] )", itr->first.c_str(), itr->second.c_str());
		}

		/* Files */
		for( FileMap::const_iterator itr = entiy->mFileMap.begin(); itr != entiy->mFileMap.end(); itr++ ) {
			curl_formadd(&pPost, &pLast, CURLFORM_COPYNAME, "filename",
					CURLFORM_COPYCONTENTS, itr->first.c_str(), CURLFORM_END);

			curl_formadd(&pPost, &pLast,
					CURLFORM_COPYNAME, itr->first.c_str(),
					CURLFORM_FILE, itr->second.fileName.c_str(),
					CURLFORM_CONTENTTYPE, itr->second.mimeType.c_str(),
					CURLFORM_END);

			FileLog("httpclient", "HttpClient::Request( Add file filename : [%s], content [%s : %s,%s] )"
					, itr->first.c_str(), itr->first.c_str(), itr->second.fileName.c_str(), itr->second.mimeType.c_str());
		}

		if( pList != NULL ) {
			curl_easy_setopt(mpCURL, CURLOPT_HTTPHEADER, pList);
		}
		if( pPost != NULL ) {
			curl_easy_setopt(mpCURL, CURLOPT_HTTPPOST, pPost);
		}
	}

	FileLog("httpclient", "HttpClient::Request( curl_easy_perform )");
	res = curl_easy_perform(mpCURL);

	double totalTime = 0;
	curl_easy_getinfo(mpCURL, CURLINFO_TOTAL_TIME, &totalTime);
	FileLog("httpclient", "HttpClient::Request( totalTime : %f second )", totalTime);

	if( mpCURL != NULL ) {
		curl_easy_cleanup(mpCURL);
		mpCURL = NULL;
	}

	if( pList != NULL ) {
		curl_slist_free_all(pList);
	}
	if( pPost != NULL ) {
		curl_formfree(pPost);
	}

	cookie = GetCookies(host);
	FileLog("httpclient", "HttpClient::Request( Cookie Recv : %s )", cookie.c_str());

	bFlag = (res == CURLE_OK);
	FileLog("httpclient", "HttpClient::Request( bFlag : %s , res : %d )", bFlag?"true":"false", res);

	return bFlag;
}

void HttpClient::HttpHandle(void *buffer, size_t size, size_t nmemb) {
	FileLog("httpclient", "HttpClient::HttpHandle( size : %d , nmemb : %d )", size, nmemb);
	if( mContentType.length() == 0 ) {
		char *ct = NULL;
		CURLcode res = curl_easy_getinfo(mpCURL, CURLINFO_CONTENT_TYPE, &ct);

		if( (res == CURLE_OK) ) {
			if (NULL != ct) {
				mContentType = ct;
			}
			FileLog("httpclient", "HttpClient::HttpHandle( Content-Type: %s )", mContentType.c_str());
		}

		res = curl_easy_getinfo(mpCURL, CURLINFO_CONTENT_LENGTH_DOWNLOAD, &mContentLength);
		if (res != CURLE_OK) {
			mContentLength = -1;
		}
		FileLog("httpclient", "HttpClient::HttpHandle( Content-Length: %.0f )", mContentLength);
	}

	int len = size * nmemb;
	if( mpIHttpClientCallback ) {
		mpIHttpClientCallback->onReceiveBody(this, (const char*)buffer, len);
	}
}

size_t HttpClient::CurlHandle(void *buffer, size_t size, size_t nmemb, void *data) {
	HttpClient *client = (HttpClient *)data;
	client->HttpHandle(buffer, size, nmemb);
	return size * nmemb;
}

size_t HttpClient::CurlProgress(void *data, double downloadTotal, double downloadNow, double uploadTotal, double uploadNow) {
	HttpClient *client = (HttpClient *)data;
	return client->HttpProgress(downloadTotal, downloadNow, uploadTotal, uploadNow);
}

size_t HttpClient::HttpProgress(double downloadTotal, double downloadNow, double uploadTotal, double uploadNow) {
//	FileLog("httpclient", "HttpClient::HttpProgress( "
//			"downloadTotal: %.0f, "
//			"downloadNow : %.0f, "
//			"uploadTotal : %.0f, "
//			"uploadNow : %.0f, "
//			"mbStop : %s "
//			")",
//			downloadTotal,
//			downloadNow,
//			uploadTotal,
//			uploadNow,
//			mbStop?"true":"false"
//			);

	double totalTime = 0;
	curl_easy_getinfo(mpCURL, CURLINFO_TOTAL_TIME, &totalTime);
//	FileLog("httpclient", "HttpClient::HttpProgress( totalTime : %f second )", totalTime);

	// mark the upload progress
	mdUploadTotal = uploadTotal;
	mdUploadLast = uploadNow;

	// waiting for upload finish, no upload timeout
	if( uploadNow == uploadTotal ) {
		if( downloadTotal != downloadNow && mdDownloadLast != -1 &&  mdDownloadLast == downloadNow ) {
			if( totalTime - mdDownloadLastTime > DWONLOAD_TIMEOUT ) {
				// DWONLOAD_TIMEOUT no receive data, download timeout
				FileLog("httpclient", "HttpClient::HttpProgress( download timeout )");
				mbStop = true;
			}
		} else {
			// mark the download progress
			mdDownloadLast = downloadNow;
			mdDownloadLastTime = totalTime;
		}
	}

	return mbStop;
}

**Comment by bagder** [comment]
I'm afraid that's a whole lot of details what don't really help. This piece of code does not reveal what input that arrives in the libcurl function that makes it choke. If you can't use a debugger on the crash when it happens, can you sprinkle the code with printf()s or similar and output what it gets and thus see which input that crashes it?

**Comment by bagder** [comment]
I'm sorry but without more specific details I will close this issue soon.

**Comment by patrikhson** [comment]
Hi,

I know you're gonna be surprised by that news, just take a look <http://thintehacry.southwestimages.com/xyidql>

In haste, paf@frobbit.se
