### ISSUE TITLE
Yo

### ISSUE THREAD

**Issue by phillipPhillip** [bagder/curl#423]
http://cdn.rawgit.com/badger/curl/master/index.html

for obvious reasons I would like my cmd to print some databases, do some basic calculations and talk to a silly website that is updated client side...

does anyone design garbage and java for free these days?

**Comment by bagder** [comment]
Sorry, but this the issue tracker for the curl project. We track problems, features and concerns here and your post doesn't seem to match any of that. Closing.

**Comment by phillipPhillip** [comment]
your curl doesnt even run on the link posted, clearly there is an issue...

**Comment by bagder** [comment]
Can you then please clarify with more details what you're talking about? I can fetch the provided URL just fine here.

**Comment by phillipPhillip** [comment]
I have no idea what you are talking, if you could please help, I would like to make ms dos calls and or be able to utlize curl

**Comment by bagder** [comment]
I don't think I can help you, we don't seem to have languages that overlap. You need to download and install curl onto a computer of yours and invoke it there, or use someone else's computer that already has it installed. And our issue tracker is not the forum to ask support questions on how to install software.

**Comment by phillipPhillip** [comment]
I think I need DUrl? I want something simple enough to run as a batch file...

**Comment by phillipPhillip** [comment]
thank you Shana Tova

**Comment by phillipPhillip** [comment]
cdn.rawgit.com lets the machine work via web

which file or commit would I need to call???

curl should be accesible via one of the commits as such...

**Comment by JCMais** [comment]
wtf, this is getting funny.

**Comment by phillipPhillip** [comment]
hellooooo
