### ISSUE TITLE
your curl doesnt run on the online hosting...

### ISSUE THREAD

**Issue by phillipPhillip** [bagder/curl#424]
http://cdn.rawgit.com/badger/curl/master/index.html

::::::::::
for obvious reasons I would like my cmd to print some databases, do some basic calculations and talk to a silly website that is updated client side...

does anyone design garbage and java for free these days?

an example of why its so important for such a project

**Comment by phillipPhillip** [comment]
tip: consider grabbing forking dos....and a web based Command Prompt....imagine the possiilies

**Comment by phillipPhillip** [comment]
*adding

**Comment by bagder** [comment]
Can you clarify what problem you have with anything we do or have in the curl project? This is all just words without a coherent meaning to me.

**Comment by phillipPhillip** [comment]
I want curl to be available online....


http://cdn.rawgit.com/badger/curl/master/index.html

for obvious reasons I would like my cmd to print some databases, do some basic calculations and talk to a silly website that is updated client side...

does anyone design garbage and java for free these days?

**Comment by phillipPhillip** [comment]
http://cdn.rawgit.com/badger/curl/index.html

**Comment by phillipPhillip** [comment]
forking dos....is dos not required to run curl???

**Comment by phillipPhillip** [comment]
curl....need list of commands and a web available cmd...?

**Comment by phillipPhillip** [comment]
http://cdn.rawgit.com/badger/curl/index.php

**Comment by phillipPhillip** [comment]
yes this is a pull request...ibid

**Comment by phillipPhillip** [comment]
ping

**Comment by bagder** [comment]
> I want curl to be available online....

In the curl project we provide source code to the curl tool. Others provide binaries and pre-built executable versions. We link some from our download page at http://curl.haxx.se/download.html

If you want to find someone that runs curl from a server somewhere for you, then go look, that's not something we offer in this project.

**Comment by phillipPhillip** [comment]
cdn.rawgit.com
