### ISSUE TITLE
'-H Content-Type:application/octet-stream --data-binary @-'  appends 'Content-Type: application/x-www-form-urlencoded'

### ISSUE THREAD

**Issue by JVD66** [bagder/curl#426]
A niggle - I'm doing something like : 
 $ dd if=$binary_data_file bs=${block_size} skip=${seek} count=1 | 
    curl -X POST ${url} -H 'Content-Length:'${block_size} -H 'Content-Type: application/octet-stream' \
    --data-binary @- --trace-ascii /dev/fd/2
But curl 7.44.0 ( x86_64 / Linux ) is deciding to append an extra  
  'Content-Type: application/x-www-form-urlencoded'
header:
    03be: Accept: application/vnd.newbay.dv-1.3+json
03ea: Content-Type : application/octet-stream
0413: Content-Length: 524288
042b: Content-Type: application/x-www-form-urlencoded
045c: Expect: 100-continue
0472: 
== Info: STATE: DO => DO_DONE handle 0x1daebb0; line 1337 (connection #0) 
== Info: STATE: DO_DONE => WAITPERFORM handle 0x1daebb0; line 1464 (connection #0) 
== Info: STATE: WAITPERFORM => PERFORM handle 0x1daebb0; line 1474 (connection #0) 
== Info: HTTP 1.1 or later with persistent connection, pipelining supported
<= Recv header, 23 bytes (0x17)
0000: HTTP/1.1 100 Continue
=> Send data, 16384 bytes (0x4000)
0000: ....!..................... ...........`.1...C...w..........k ...
0040: .............................................................!..

The nginx server listening at ${url} is using only the second Content-Type header ,
which I did NOT specify, 
and is rejecting the request (returning a 400 error) because of invalid encoding .

To fix, I have to give curl an extra -H argument:
     ... -H 'Content-Length:'${block_size} -H 'Content-Type;'  -H 'Content-Type: application/octet-stream' 
The -H 'Content-Type;' disables the internal append of 'Content-Type: application/x-www-form-urlencoded',
I finally realized after a couple of hours of analyzing the documentation, source code and trial and error. 

But why, if I specified '--data-binary' , is curl appending the extra internal 
   Content-Type: application/x-www-form-urlencoded 
header at all ?

I don't think it should do this , since I thought I was instructing curl to not perform any conversions
with the '--data-binary' argument.

If the generation of the internal Content-Type header for '--data-binary @-' is not going to be removed, 
then  the  documentation should be made clearer :
"       --data-binary <data>
              (HTTP) This posts data exactly as specified with no extra processing whatsoever.
              If you start the data with the letter @, the rest should be a filename.  Data is posted in a
              similar manner as --data-ascii does, except that newlines  and  carriage
              returns are preserved and conversions are never done, 
+++         but the 'Content-Type: application/x-www-form-urlencoded'  internal header will be
+++         appended unless the '-H Content-Type;' arguments are given, even when no conversions are done.
"

**Comment by bagder** [comment]
I can't repeat this with 7.44.0. This is what my curl 7.44.0 does:

~~~
$ curl -V
curl 7.44.0 (x86_64-pc-linux-gnu) libcurl/7.44.0 GnuTLS/3.3.17 zlib/1.2.8 libidn/1.32 libssh2/1.5.0 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 

$ echo "data" | curl -H 'Content-Type: moo/foo' --data-binary @- localhost -v
* Rebuilt URL to: localhost/
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 80 (#0)
> POST / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.44.0
> Accept: */*
> Content-Type: moo/foo
> Content-Length: 5
>

**Comment by JVD66** [comment]
Hmm ... it appears to be triggered by the weird extra headers I have to send .
Yes, your example works, but adding the extra headers triggers the bug:

$ echo 'data' | curl jvasdias -X POST -H 'Set-Cookie: NWB=AHNVUAOPif63OPTqcJj826h3lc1nnGD4ap1CVAxx3OTMTIfnFVT6G5P2_5nikwkiiUHapXjNLcVsVqAHU3leHnRervv7X5bV3S9X_gGjhLMJCxxHNp5dGvn2X90dF-ZMM2t3wRkPYlp0KTOmcT5HMBGBPUy924-rzpZDda5dkj8ZzgdjUxHCQWHV8590b8E5SPxri-lBbEEYXcty-lW_1g19FieNFLDrAp8AD8HJz1EUbNtLk7RyWBNFmeSQYXJZ2n8l_5nJKzveNEOi3SZdgw6iaql8Lbkg9nvgYAw9W_GyM88r1VfWRnn8F3DhXaNnPQ~~' -H 'Authorization: NWB token="AHNVUAOPif63OPTqcJj826h3lc1nnGD4ap1CVAxx3OTMTIfnFVT6G5P2_5nikwkiiUHapXjNLcVsVqAHU3leHnRervv7X5bV3S9X_gGjhLMJCxxHNp5dGvn2X90dF-ZMM2t3wRkPYlp0KTOmcT5HMBGBPUy924-rzpZDda5dkj8ZzgdjUxHCQWHV8590b8E5SPxri-lBbEEYXcty-lW_1g19FieNFLDrAp8AD8HJz1EUbNtLk7RyWBNFmeSQYXJZ2n8l_5nJKzveNEOi3SZdgw6iaql8Lbkg9nvgYAw9W_GyM88r1VfWRnn8F3DhXaNnPQ~~"; authVersion="1.0"' -H 'Accept: application/vnd.newbay.dv-1.3+json' -H 'Content-Type : application/octet-stream' -H 'Content-Length: 5' --data-binary @- -v >/dev/null
* STATE: INIT => CONNECT handle 0xc621c0; line 1090 (connection #-5000) 
* Rebuilt URL to: jvasdias/
* Added connection 0. The cache now contains 1 members
*   Trying 172.16.8.9...
* STATE: CONNECT => WAITCONNECT handle 0xc621c0; line 1143 (connection #0) 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to jvasdias (172.16.8.9) port 80 (#0)
* STATE: WAITCONNECT => SENDPROTOCONNECT handle 0xc621c0; line 1240 (connection #0) 
* STATE: SENDPROTOCONNECT => DO handle 0xc621c0; line 1258 (connection #0) 
> POST / HTTP/1.1
> Host: jvasdias
> User-Agent: curl/7.44.0
> Set-Cookie: NWB=AHNVUAOPif63OPTqcJj826h3lc1nnGD4ap1CVAxx3OTMTIfnFVT6G5P2_5nikwkiiUHapXjNLcVsVqAHU3leHnRervv7X5bV3S9X_gGjhLMJCxxHNp5dGvn2X90dF-ZMM2t3wRkPYlp0KTOmcT5HMBGBPUy924-rzpZDda5dkj8ZzgdjUxHCQWHV8590b8E5SPxri-lBbEEYXcty-lW_1g19FieNFLDrAp8AD8HJz1EUbNtLk7RyWBNFmeSQYXJZ2n8l_5nJKzveNEOi3SZdgw6iaql8Lbkg9nvgYAw9W_GyM88r1VfWRnn8F3DhXaNnPQ~~
> Authorization: NWB token="AHNVUAOPif63OPTqcJj826h3lc1nnGD4ap1CVAxx3OTMTIfnFVT6G5P2_5nikwkiiUHapXjNLcVsVqAHU3leHnRervv7X5bV3S9X_gGjhLMJCxxHNp5dGvn2X90dF-ZMM2t3wRkPYlp0KTOmcT5HMBGBPUy924-rzpZDda5dkj8ZzgdjUxHCQWHV8590b8E5SPxri-lBbEEYXcty-lW_1g19FieNFLDrAp8AD8HJz1EUbNtLk7RyWBNFmeSQYXJZ2n8l_5nJKzveNEOi3SZdgw6iaql8Lbkg9nvgYAw9W_GyM88r1VfWRnn8F3DhXaNnPQ~~"; authVersion="1.0"
> Accept: application/vnd.newbay.dv-1.3+json
> Content-Type : application/octet-stream
> Content-Length: 5
> Content-Type: application/x-www-form-urlencoded
> 
} [5 bytes data]
* upload completely sent off: 5 out of 5 bytes
* STATE: DO => DO_DONE handle 0xc621c0; line 1337 (connection #0) 
* STATE: DO_DONE => WAITPERFORM handle 0xc621c0; line 1464 (connection #0) 
* STATE: WAITPERFORM => PERFORM handle 0xc621c0; line 1474 (connection #0) 
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 200 OK
< Date: Fri, 11 Sep 2015 16:17:51 GMT
* Server Apache/2.4.7 (Ubuntu) is not blacklisted
< Server: Apache/2.4.7 (Ubuntu)
< Last-Modified: Sun, 27 Apr 2014 21:01:30 GMT
< ETag: "2cf6-4f80c80cbab23"
< Accept-Ranges: bytes
< Content-Length: 11510
< Vary: Accept-Encoding
< Content-Type: text/html

**Comment by bagder** [comment]
Weird! Can you figure out which of the extra headers that cause this problem to trigger?

**Comment by bagder** [comment]
Oh, is there a space between "Content-Type" and the colon in your custom header? Can you try removing that space?

**Comment by JVD66** [comment]
Yes, it appears to be the header containing the spaces and semi-colons :  
     $ echo 'data' | curl jvasdias -X POST  -H 'Authorization: bogus"; authVersion="1.0"'  \
                        -H 'Content-Type : application/octet-stream' \
                        -H 'Content-Length: 5' --data-binary @- -v >/dev/null 2>/tmp/log
   $ sed 's/^/    /' < /tmp/log
    * STATE: INIT => CONNECT handle 0x7e41c0; line 1090 (connection #-5000) 
    * Rebuilt URL to: jvasdias/
    * Added connection 0. The cache now contains 1 members
    *   Trying 172.16.8.9...
    * STATE: CONNECT => WAITCONNECT handle 0x7e41c0; line 1143 (connection #0) 
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to jvasdias (172.16.8.9) port 80 (#0)
    * STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x7e41c0; line 1240 (connection #0) 
    * STATE: SENDPROTOCONNECT => DO handle 0x7e41c0; line 1258 (connection #0) 
    > POST / HTTP/1.1
    > Host: jvasdias
    > User-Agent: curl/7.44.0
    > Accept: */*
    > Authorization: bogus"; authVersion="1.0"
    > Content-Type : application/octet-stream
    > Content-Length: 5
    > Content-Type: application/x-www-form-urlencoded
    > 
    } [5 bytes data]
    * upload completely sent off: 5 out of 5 bytes
    * STATE: DO => DO_DONE handle 0x7e41c0; line 1337 (connection #0) 
    * STATE: DO_DONE => WAITPERFORM handle 0x7e41c0; line 1464 (connection #0) 
    * STATE: WAITPERFORM => PERFORM handle 0x7e41c0; line 1474 (connection #0) 
    * HTTP 1.1 or later with persistent connection, pipelining supported
    < HTTP/1.1 200 OK
    < Date: Fri, 11 Sep 2015 16:28:58 GMT
    * Server Apache/2.4.7 (Ubuntu) is not blacklisted
    < Server: Apache/2.4.7 (Ubuntu)
    < Last-Modified: Sun, 27 Apr 2014 21:01:30 GMT
    < ETag: "2cf6-4f80c80cbab23"
    < Accept-Ranges: bytes
    < Content-Length: 11510
    < Vary: Accept-Encoding
    < Content-Type: text/html
    < 
    { [11510 bytes data]
    * STATE: PERFORM => DONE handle 0x7e41c0; line 1632 (connection #0) 
    * Curl_done
    100 11515  100 11510  100     5  9623k   4280 --:--:-- --:--:-- --:--:-- 10.9M
    * Connection #0 to host jvasdias left intact
    * Expire cleared

**Comment by bagder** [comment]
The space between the name and the colon is what causes the problem.

**Comment by JVD66** [comment]
Same thing happens if I remove the stray '"' from the header:
    echo 'data' | curl jvasdias -X POST   'Authorization:bogus;authVersion="1.0"' \
                       -H 'Content-Type:application/octet-stream' -H 'Content-Length: 5' \
                       --data-binary @- -v >/dev/null 2>/tmp/log

**Comment by bagder** [comment]
Sorry, I can't repeat that and your last command line is broken. I successfully tried this:

~~~~
echo data | curl localhost -H  'Authorization:bogus;authVersion="1.0"' -H 'Content-Type:application/octet-stream' -H 'Content-Length: 5' --data-binary @- -v >/dev/null

**Comment by JVD66** [comment]
Aha ! sorry I posted that last comment before I saw your reply .   Yes, removing the space from  
'Content-Type : application/octet-stream' fixes the problem , as does appending -H 'Content-Type;'  .
But surely curl could handle '<header_name> : <value>' pairs?

**Comment by JVD66** [comment]
But surely curl could handle ' $header : $value ' pairs with spaces after the name better ?

**Comment by bagder** [comment]
*Could*, sure, but a valid header has no space there (https://tools.ietf.org/html/rfc7230#section-3.2) so I'm not convinced it should...

**Comment by JVD66** [comment]
OK, sorry , my mistake .

**Comment by JVD66** [comment]
Yes, this was due to the buttons on my mouse being unfortunately very close together, and when I 
changed focus to the script editor, a stray ' ' got inserted (both buttons were pressed); this
was when making a trivial change to the script ; the only other change was moving to
the new curl 7.44.0 version.

But actually, on second thoughts,  the thought that curl is silently inserting the header : 
         Content-Type: application/x-www-form-urlencoded
for a '--data-binary -@' stream , and then NOT doing any URL encoding, ie. then reading
the stream and passing it on as if it was already url-encoded, is somewhat disconcerting .

It resulted in the  Java server receiving the stream generating a full exception back-trace
for each incorrectly encoded byte it received , @ 1GB of log messages .

I think that '--data-binary' should always mean exactly that, and should disable any automatic
header generation by curl .  If it had not appended the x-www-form-urlencoded header, 
there's a good chance the nginx proxy would have detected the bad 'Content-Type :' header and 
rejected the request for containing no Content-Type , or treated the posted stream as default
Content-Type octet-stream .

If curl does decide to append a header for a --data-binary stream, it should complain loudly
about it to stderr log at the very least;  perhaps it should also perform encoding verification
on the stream it reads and passes on, and if the first block fails validation, it could perform
encoding conversion to the type specified by the appended header for the whole stream.
