### ISSUE TITLE
Tests not using the right libcurl.so if rpaths set via LDFLAGS

### ISSUE THREAD

**Issue by jay** [bagder/curl#432]
In Ubuntu 14 x64 I build curl from source. Recently test 1022 failed (version mismatch) and I traced it to the rpath ordering in the lt-curl binary `src/.libs/lt-curl` built by the libtool-generated wrapper script `src/curl`. The wrapper builds lt-curl with the lib/.libs location of the not-yet-installed libcurl.so.4 rpath appended instead of prepended. This is an issue because I pass rpath locations via `LDFLAGS` to configure since Ubuntu already has a separate libcurl shared library that I don't want to replace. The result is the tests run with an older version of libcurl that I already built and installed instead of the not-yet-installed version.

I build like basically like this:
~~~
LDFLAGS="-Wl,-rpath,$OPENSSL_PREFIX/lib -Wl,-rpath,$CURL_PREFIX/lib" \
./configure --with-ssl=$OPENSSL_PREFIX --prefix=$CURL_PREFIX && \
make && \
make test && \
sudo make install
~~~

Those rpaths can then be found in the libtool script, which has a relink command that's like:
~~~
gcc -O2 -Wno-system-headers -Wl,-rpath -Wl,/usr/local/ssl/lib -Wl,-rpath -Wl,/usr/local/lib -o \$progdir/\$file <object ...> <lib ...> -Wl,-rpath -Wl,/home/owner/curl-7.44.0/lib/.libs
~~~
or actually:
~~~
relink_command="(cd /home/owner/curl-7.44.0/src; { test -z \"\${LIBRARY_PATH+set}\" || unset LIBRARY_PATH || { LIBRARY_PATH=; export LIBRARY_PATH; }; }; { test -z \"\${COMPILER_PATH+set}\" || unset COMPILER_PATH || { COMPILER_PATH=; export COMPILER_PATH; }; }; { test -z \"\${GCC_EXEC_PREFIX+set}\" || unset GCC_EXEC_PREFIX || { GCC_EXEC_PREFIX=; export GCC_EXEC_PREFIX; }; }; { test -z \"\${LD_RUN_PATH+set}\" || unset LD_RUN_PATH || { LD_RUN_PATH=; export LD_RUN_PATH; }; }; { test -z \"\${LD_LIBRARY_PATH+set}\" || unset LD_LIBRARY_PATH || { LD_LIBRARY_PATH=; export LD_LIBRARY_PATH; }; }; PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games; export PATH; gcc -O2 -Wno-system-headers -Wl,-rpath -Wl,/usr/local/ssl/lib -Wl,-rpath -Wl,/usr/local/lib -o \$progdir/\$file curl-tool_binmode.o curl-tool_bname.o curl-tool_cb_dbg.o curl-tool_cb_hdr.o curl-tool_cb_prg.o curl-tool_cb_rea.o curl-tool_cb_see.o curl-tool_cb_wrt.o curl-tool_cfgable.o curl-tool_convert.o curl-tool_dirhie.o curl-tool_doswin.o curl-tool_easysrc.o curl-tool_formparse.o curl-tool_getparam.o curl-tool_getpass.o curl-tool_help.o curl-tool_helpers.o curl-tool_homedir.o curl-tool_hugehelp.o curl-tool_libinfo.o curl-tool_main.o curl-tool_metalink.o curl-tool_mfiles.o curl-tool_msgs.o curl-tool_operate.o curl-tool_operhlp.o curl-tool_panykey.o curl-tool_paramhlp.o curl-tool_parsecfg.o curl-tool_strdup.o curl-tool_setopt.o curl-tool_sleep.o curl-tool_urlglob.o curl-tool_util.o curl-tool_vms.o curl-tool_writeenv.o curl-tool_writeout.o curl-tool_xattr.o ../lib/curl-strtoofft.o ../lib/curl-rawstr.o ../lib/curl-nonblock.o ../lib/curl-warnless.o  -L/usr/local/ssl/lib ../lib/.libs/libcurl.so -lssl -lcrypto -lz -Wl,-rpath -Wl,/home/owner/curl-7.44.0/lib/.libs)"
~~~

As you can see it's putting the lib/.libs rpath last instead of first. For now I'm trying LD_PRELOAD as a workaround like:
~~~
LD_PRELOAD=/home/owner/curl-7.44.0/lib/.libs/libcurl.so.4 ./runtests.pl -p 1022
~~~
Though I haven't yet tried it with `make test` I expect that should work there as well.

**Comment by bagder** [comment]
I'm not saying it is a general solution, but I always build my development versions of libcurl static only as then I avoid this sort of problem...

**Comment by jay** [comment]
> I always build my development versions of libcurl static only as then I avoid this sort of problem

I see in my notes I've done it that way in the past, I'm not sure why I stopped. I've built libcurl like `--disable-shared --enable-static --enable-debug ` and then for programs that I link to libcurl I built like:
~~~
gcc -o a a.c libcurl.a -g -ggdb -rdynamic -I../../include -L/usr/local/ssl/lib -Wl,-rpath,/usr/local/ssl/lib -lidn -lrtmp -lssl -lcrypto -llber -lldap -lz
~~~
I'm not sure why I changed it back to shared. I'm installing a release version not a development version in Ubuntu now (probably why), though I have the dev built there as well just not installed. For now I'm using [LD_PRELOAD to load the lib/.libs libcurl.so](https://gist.github.com/jay/d88d74b6807544387a6c/e6a19b61f8e6f2fdbb30573e8f420da85bc5fc7d#file-curl-ubuntu-update-installed-release-txt-L57) when I run the tests.

I won't be much help with this, I took a look at libtool this afternoon and I couldn't figure out what to change. I don't even know if it's something that can be changed in curl's build script, though I assume we could come in with sed or something. I can't spend more time on it so if nobody else wants to take it I won't object if you close it.

**Comment by bagder** [comment]
I think we can just ignore this for now and possibly come back in the future if it turns out to become a bigger problem.

**Comment by jay** [comment]
I've just discovered the LD_PRELOAD trick does not work for me in tests where that variable is overridden, for example [test831](https://github.com/curl/curl/blob/curl-7_50_1/tests/data/test831#L39-L40).

If I change the LD_PRELOADs in all tests to prepend to the existing LD_PRELOAD it works, see https://github.com/curl/curl/compare/master...jay:ld_preload_tests_fix?expand=1

`LD_PRELOAD=$PWD/lib/.libs/libcurl.so make test TEST_Q='-d -v -a -p -n 831'`

I think though the rpath ordering could be a bug in libtool so I filed it this evening
[#24296 lt wrapper script puts the .libs rpath last instead of first](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=24296)

**Comment by jay** [comment]
I haven't heard back from the libtool people so to remedy this in the meantime I created a branch with a script to be run at the end of the build that will modify the src/curl libtool wrapper script to make lib/.libs the first rpath lt-curl checks for dependencies. Also, I added the lib/.libs rpath to AM_LDFLAGS in tests/libtest/Makefile.am since those libs need it to load the libcurl from lib/.libs.

https://github.com/curl/curl/compare/master...jay:workaround_libtool_bug_24296?expand=1

Though that works it seems kind of kludgy. I'm sure there's a better way. I don't see a reason to propose it for upstream atm.

Additionally when I'm not using buildconf (like with a release tarball) I have made a patch for the Makefile.in files though I gather that's not a typical thing to do.

If anyone else is affected by this issue and stumbled here, below is from my [Ubuntu 16 notes](https://gist.github.com/jay/d88d74b6807544387a6c) and shows the patches applied before running configure on a curl release. The second patch can be skipped if buildconf is run before configure, since that will regenerate the Makefile.in files.

```bash
# Workaround libtool bug 24296, see https://github.com/curl/curl/issues/432
#
curl --fail -L --output workaround_libtool_bug_24296.patch \
  https://github.com/curl/curl/compare/master...jay:workaround_libtool_bug_24296.patch && \
patch -p1 < workaround_libtool_bug_24296.patch && \
\
# Use a related workaround for src/Makefile.in since we're not regenerating it
#
curl --fail -OL \
  https://gist.githubusercontent.com/jay/d88d74b6807544387a6c/raw/workaround_when_buildconf_is_not_used.patch && \
patch -p1 < workaround_when_buildconf_is_not_used.patch
```
