### ISSUE TITLE
Need support for proxy protocol

### ISSUE THREAD

**Issue by miltieIV2** [bagder/curl#434]
By "proxy protocol", I mean:
  http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt

Abstract:
  The PROXY protocol provides a convenient way to safely transport connection
   information such as a client's address across multiple layers of NAT or TCP
   proxies. It is designed to require little changes to existing components and
   to limit the performance impact caused by the processing of the transported
   information.

Proxy protocol is useful in situations where you need the originating IP address, but you don't control the proxy (AWS ELB in proxy protocol mode), especially when the proxy is in simple TCP mode and isn't able insert things into the content, like X-Forwarded-For headers:
  http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-proxy-protocol.html

---

When a receiver is expecting proxy protocol, it can no longer receive connections using its native protocol. This breaks direct command line access from curl and direct probers that use curl/libcurl. The fix for curl is fairly simple: send a line of text before starting the normal protocol.

A number of programs have already been enhanced to support proxy protocol:
  http://blog.haproxy.com/haproxy/proxy-protocol/

**Comment by bagder** [comment]
I'm sorry, but this is not a feature-request tracker. We're drowning in good ideas to implement already. We need more humans with time and energy to write code, tests and documentation. I would urge you to bring up a discussion on the curl-library mailing list to see if you can find others who are interested in your idea and might be interested in helping out with the implementation.
