### ISSUE TITLE
easysrc generation is slow for large sequence of URLs

### ISSUE THREAD

**Issue by gnawhleinad** [bagder/curl#444]
Reported-by: @greafhe in #429

The proposed fix, by @bagder, is to use a linked-list with last.

The existing [`curl_slist`](https://github.com/bagder/curl/blob/master/include/curl/curl.h#L2022) implementation is really a node. Should this change update all `curl_slist` or keep track of the last at [`src/tool_easysrc.c`](src/tool_easysrc.c)?

**Comment by bagder** [comment]
Either way is fine I'd say. Perhaps the smaller (and thus preferable) fix is keeping track of the last in `src/tool_easysrc.c` ?

**Comment by bagder** [comment]
Fixed now!
