### ISSUE TITLE
ETA Doesn't Account for Local TCP Buffer

### ISSUE THREAD

**Issue by nathanila** [bagder/curl#450]
I am using the following command to upload a 10 MB file.  The transfer takes 107 seconds at 94.1 kB/s.

pscp -P 22 -l john -pw ******* -4 -C "C:\Temp\BigFile.rpm" 10.133.224.189:/tmp

At the start of the upload, the amount of data transferred immediately jumps to the size of the local TCP send buffer.  This buffer is inside the Windows 7 kernel.  The ETA states that the upload will only take a couple of seconds because the transfer rate is super high.  In reality, very little data has transferred on the wire.

As the transfer progresses, the ETA climbs upwards as the transfer rate comes down to reality.  Then once the transfer rate has stabilized, the ETA then drops by 1 second for every second that goes by.  This is perfect.

At the end of the transfer, the kernel holds the last X KB of data.  So, ETA reports 00:00:00 and the transfer is 100% complete.  pscp "hangs" here for several seconds while the data is transferred out of the kernel buffer.

When reporting the transfer speed, ETA and percent completed, please account for the kernel's TCP send buffer.

Consider setting the send buffer to size 0 using sockopt().  If pscp calls send() then the call will block until pscp's buffer is sent over the network.  Transfer speed will not be impacted as long as pscp is able to fill the buffer with the next set of bytes fast enough.

**Comment by bagder** [comment]
Sorry, you must've posted this in the wrong place. pscp is not a tool provided by the curl project.
