### ISSUE TITLE
FTP filesize-problem when uploading in ASCII mode

### ISSUE THREAD

**Issue by lzsiga** [bagder/curl#453]
Hi, I think I've found a little bug:
When file-size is pre-set to -1, it shouldn't be changed in **lib/transfer.c:926** Suggested patch:

    --- transfer.~c	2015-07-25 10:54:03.000000000 +0200
    +++ transfer.c	2015-09-24 17:42:00.000000000 +0200
    @@ -923,7 +923,9 @@
                 if(!data->set.crlf) {
                   /* we're here only because FTP is in ASCII mode...
                      bump infilesize for the LF we just added */
    -              data->state.infilesize++;
    +              if (data->state.infilesize != -1) {
    +                data->state.infilesize++;
    +              }
                 }
               }
               else

**Comment by lzsiga** [comment]
Well, there is a component called *checksrc* that doesn't like spaces between 'if' and '('.

    --- transfer.~c 2015-07-25 10:54:03.000000000 +0200
    +++ transfer.c  2015-09-24 17:42:00.000000000 +0200
    @@ -923,7 +923,9 @@
                 if(!data->set.crlf) {
                   /* we're here only because FTP is in ASCII mode...
                      bump infilesize for the LF we just added */
    -              data->state.infilesize++;
    +              if(data->state.infilesize != -1) {
    +                data->state.infilesize++;
    +              }
                 }
               }
               else

**Comment by bagder** [comment]
Awesome, merged in 32fc638ddf046d501 Thanks!
