### ISSUE TITLE
cURL Website, Binaries and Certificate Files Are Served Over Plaintext HTTP

### ISSUE THREAD

**Issue by Miserlou** [bagder/curl#455]
Given how easy it is to inject code into binaries and certificates being served over the wire, how common this practice is by governments, and how important cURL is, it seems extremely dangerous that important cURL files, such as http://curl.haxx.se/download/curl-7.44.0.tar.gz and http://curl.haxx.se/ca/cacert.pem are served over unencrypted, un-authenticated plaintext HTTP.

Please fix this as soon as possible. This should really be considered to be an emergency situation.

**Comment by jay** [comment]
There are [plans to convert](http://daniel.haxx.se/blog/2015/07/26/https-and-http2-plans-for-my-sites/) to HTTPS. It is not an emergency. The source is signed (`gpg --recv-keys 914C533DF9B2ADA2204F586D78E11C6B279D5C91`). Also there is an '[over HTTPS](https://github.com/bagder/curl/releases/)' link on the release page. The certificates page has a similar '[HTTPS from github](https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt)' link. The user provided builds that curl.haxx.se mirrors are not encrypted though.

**Comment by bagder** [comment]
I fail to see how this is suddenly an emergency. It has worked like this for 18 years. We provide signatures and we offer HTTPS links for download. There's a [plan for HTTPS for the site, mentioned previously on my blog](http://daniel.haxx.se/blog/2015/07/26/https-and-http2-plans-for-my-sites/). Hopefully it will become reality before the end of the year.
