### ISSUE TITLE
Modified buffer size approach

### ISSUE THREAD

**Issue by mtangoo** [bagder/curl#458]
Is [ this To do List](http://curl.haxx.se/docs/todo.html#Modified_buffer_size_approach) still a todo?
If Yes what do I do with app running both SFTP and Plain FTP?

**Comment by bagder** [comment]
It is still a TODO as the current buffer size is sub-optimal for SFTP transfers.

> what do I do with app running both SFTP and Plain FTP?

The larger buffer would only be used for connections/handles that do SFTP I would say. But yes, that's sort of one part of the problem.
