### ISSUE TITLE
Using HTTP2 makes batch of 1k files download slower than http1.1. Why?

### ISSUE THREAD

**Issue by carlitooo** [bagder/curl#460]
I am having a problem where downloading files with http2 is slower than from http1.1.

I downloaded the daily snapshot from September 28th and compiled it on my CentOS 6.6 machine with just 'make'. I compiled my linux app against the compiled curl and verified with ldd that it is pointing towards the newly build libcurl.

I have a nginx server with the following configuration:

```
server {
    listen       9081 http2;
    server_name cool-site.tv;

    ssl on;
    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    location / {
        root /my/cool/dir;
        allow all;
        autoindex on;
    }
}
```

I generated a certificate with:
```openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt```

I couldn't attach my code (not even as a .txt), so you can find it at http://pastebin.com/2H4fRVfg. You'll have to add/generate some urls for it to download.

In the /my/cool/dir directory, I have 1000 small files (<10 kb). If I remove the 'http2' part from my nginx config (so that it just uses http1.1), I can fetch 1k fragments in about 6 seconds. If I keep the http2 part in my nginx config, and I change the urls in my C code from http to https, I can fetch 1k fragments in about 25 seconds. I count the time per fragment in the code and process the output later with awk to calculate the total time.

I understand that it will check the cert, but I expected http2.0 to be faster than http1.1.

Why is using http2 slower in this case? Is it because my nginx setup is wrong, or is there something going on in the libcurl code?

**Comment by bagder** [comment]
There's nothing in your code there that asks for HTTP/2. What makes you think it uses HTTP/2?

Also, if you'd really want to really use HTTP/2's powers and ability to saturate a pipe in ways HTTP/1.1 cannot do then you should use multiplexed transfers and ask for N objects at once instead of getting them in a serial manner.
