### ISSUE TITLE
OpenSSL header mismatch when using --with-ssl=<dir> and libssl-dev installed

### ISSUE THREAD

**Issue by webmaster128** [bagder/curl#461]
When I install libssl-dev on Ubuntu 15.04 and build curl using a custom OpenSSL build without MD4, I get a linker error:

```
  CC       curl-tool_vms.o
  CC       curl-tool_writeenv.o
  CC       curl-tool_writeout.o
  CC       curl-tool_xattr.o
  CC       ../lib/curl-strtoofft.o
  CC       ../lib/curl-rawstr.o
  CC       ../lib/curl-nonblock.o
  CC       ../lib/curl-warnless.o
  CCLD     curl
../lib/.libs/libcurl.a(libcurl_la-curl_ntlm_core.o): In function `Curl_ntlm_core_mk_nt_hash':
curl_ntlm_core.c:(.text+0x353): undefined reference to `MD4_Init'
curl_ntlm_core.c:(.text+0x361): undefined reference to `MD4_Update'
curl_ntlm_core.c:(.text+0x36c): undefined reference to `MD4_Final'
collect2: error: ld returned 1 exit status
Makefile:758: recipe for target 'curl' failed
make[3]: *** [curl] Error 1
```

So I think the system's header and the custom build was used.

The error disappeared immediately when I uninstalled libssl-dev. When I installed libssl-dev again, the error did not come again. Is there a way to deterministically tell the compiler to use the OpenSSL headers from the custom directory?

**Comment by bagder** [comment]
It sounds as if your configure line wasn't enough to make the build your custom build but it was still using some cruft from your system's default include files. What was your full configure line when you build curl?

**Comment by webmaster128** [comment]
How to reproduce:

```
wokspace
  \-- curl
  \-- build-openssl
```

1) `build-openssl` does not exist (because it is not built yet)
2) Configure as follows (i.e. `--with-ssl` points to the non-existing directory)

```
$ ./buildconf
$ ./configure \
        --disable-debug --enable-optimize --disable-curldebug --enable-symbol-hiding --enable-silent-rules --disable-shared --enable-static \
        --disable-file --disable-ftp --disable-ldap --disable-ldaps --disable-rtsp --disable-dict --disable-telnet \
        --disable-tftp --disable-pop3 --disable-imap --disable-smb --disable-smtp --disable-gopher --disable-manual \
        --enable-ipv6 --enable-threaded-resolver --disable-ntlm-wb --enable-tls-srp --without-libidn --without-librtmp \
        --with-ssl="$SOURCE_DIR/../build-openssl" \
        CPPFLAGS='-D_FORTIFY_SOURCE=2' \
        CFLAGS='-pthread -O2 -g -fstack-protector -pie -fPIE -Wl,-z,relro,-z,now'
$ make
```

3) Making succeeded (`--with-ssl` does still not exist)
4) Target project build fails because of the missing library in `workspace/build-openssl`
5) Build openssl (creates `workspace/build-openssl`)
6) Build target project again fails with `undefined reference to `MD4_Init'`

Now I'd say this is entirely my fault caused by a usability issue in 2) where building curl does not fail when the users puts something invalid into `--with-ssl`.

**Comment by bagder** [comment]
That's a setup the configure script is not designed to handle. You're supposed to point to an OpenSSL prefix of an already installed openssl set of libs and headers. Failing that, curl's configure will not consider that to be a good/useful prefix.

So, just build and install openssl first, then build curl like that and it'll work just fine.

**Comment by webmaster128** [comment]
Thanks.
