### ISSUE TITLE
SFTP: Check if URL is Directory

### ISSUE THREAD

**Issue by mtangoo** [bagder/curl#462]
I have this code to check if the path is Directory or File. Its works fine with FTP but not with SFTP. How do I check if path is Directory not file with libcurl?

```cpp
bool IsDir(const wxString& path)
{ 

    wxString fullRemotePath = "sftp://user@server/home/user/";
    curl_easy_setopt(m_ftp, CURLOPT_URL, fullRemotePath.c_str().AsChar());
    curl_easy_setopt(m_ftp, CURLOPT_NOBODY, 1L);//No transfer
    m_rc = curl_easy_perform(m_ftp);

    //reset back to normal
    curl_easy_setopt(m_ftp, CURLOPT_NOBODY, 0L);

    return m_rc == CURLE_OK; //I expected it to fail on file, but it does not
}
```
Curl Version is curl-7.43.0

**Comment by mtangoo** [comment]
after several trials this Code works  (taken from (Here)[http://stackoverflow.com/questions/2477936/using-libcurl-to-check-if-a-file-exists-on-a-sftp-site]), but I don't want to send data yet since its another added delay
```cpp
CURL *curl = curl_easy_duphandle(m_ftp);
    curl_easy_setopt(curl, CURLOPT_RANGE,
                     (const char *)"0-0");
    wxString fullRemotePath = m_protocol+"://"+m_hostname+":"+m_port+remote; //sftp://user@server/home/user/
    curl_easy_setopt(curl, CURLOPT_URL, fullRemotePath.c_str().AsChar());
    CURLcode iRc = CURLE_OK;
    iRc = curl_easy_perform(curl);

    if(iRc == CURLE_REMOTE_FILE_NOT_FOUND) 
        return false;
    else
        return true;
```

**Comment by jay** [comment]
Stefano this is an issue tracker. If you have questions about libcurl that you cannot find the answer to please ask on the [mailing list](http://cool.haxx.se/mailman/listinfo/curl-library).

**Comment by mtangoo** [comment]
I read mailing list and its supposed to work (I will attach the link here once am at my machine)  so I think it's a bug. But before I term it so I wanted to confirm with someone who knows curl better. 

So you don't think it's a bug?

**Comment by mtangoo** [comment]
And the link I was saying is (this one)[http://curl.haxx.se/mail/archive-2014-03/0006.html]
I think the case is valid here and need to be addressed

**Comment by bagder** [comment]
The question from then remains though : what does libssh2 return there?

**Comment by mtangoo** [comment]
How can I step into that file. My IDE can't jump into curl_easy_perform()

**Comment by bagder** [comment]
@mtangoo, that depends entirely on your IDE and build and this is not really the place to dig into such details. You probably need to build libcurl in a sort of debug-mode and use that.

**Comment by mtangoo** [comment]
Its in debug mode.I thought I have to do some special thing in SSH. Let me dig that out and post findings

**Comment by mtangoo** [comment]
@bagder ,
I now have a working debug and I can step into the ssh.c but it seems a lot have changed and I cannot find what is asked exactly. Can you check it again and tell me exactly what I should check (perhaps line number too)?

My curl is 7.43.0

**Comment by bagder** [comment]
The mail is about curl not telling if the dir is non-existing, and the `libssh2_sftp_open_ex` call in the `SSH_SFTP_READDIR_INIT` state (line 1864 in lib/ssh.c or so) should return an error for that case.

Or perhaps, what does it return if you give it a file name as input?

**Comment by mtangoo** [comment]
@bagder  its the same issue am having.
Since I use NO_BODY option, I cannot reach the code in 1864
here is the code am talking about
```cpp
case SSH_SFTP_READDIR_INIT:
      Curl_pgrsSetDownloadSize(data, -1);
      if(data->set.opt_no_body) {
        state(conn, SSH_STOP);
        break; //breaks here so that I cannot reach the  code     sshc->sftp_handle = libssh2_sftp_open_ex(....)

      }

```

**Comment by bagder** [comment]
Then you're obviously on your way to figure out what's needed to make this work...!

**Comment by mtangoo** [comment]
Please decrypt that sentence for me. Do I need to remove the NO_BODY?
But FTP works fine!

**Comment by bagder** [comment]
FTP is a completely different protocol with a completely different code path so that doesn't help us at all. You pretty much identified which the SFTP case doesn't work. Now you just need to figure how what you need to modify so that it starts working!

**Comment by mtangoo** [comment]
So am removing the "no body" and see if the issue is still there.

**Comment by bagder** [comment]
Removing that will ask for a full transfer though, which is probably not what you want when you only want to figure out if it is a file or a directory...

**Comment by mtangoo** [comment]
You are right. Now I do check he protocol before I use no body option.
I think curl should just check if its sftp, it should let it continue. or else it should break there. In Other words, No body in this case should be ignored in sftp.
What do you think?

**Comment by bagder** [comment]
I think "no body" is at least as important for SFTP as for any other protocol. Why do you think it isn't necessary for SFTP? It would be highly surprising for users to suddenly actually get a very large file when they especially as for it to not be transfered (and only meta data to be retrieved).

I think the bug we've identified should be fixed though.

**Comment by mtangoo** [comment]
>I think the bug we've identified should be fixed though.

This kills the whole idea I proposed. I thought it is a "feature" in SFTP. If its a bug that can be fixed, I retract my statements :)

**Comment by bagder** [comment]
No interest for this, closing.
