### ISSUE TITLE
redirect and proxy

### ISSUE THREAD

**Issue by Rotkaermota** [bagder/curl#470]
I use curl as static lib.
I use following settings to download binary file:
CURLOPT_PROXYTYPE : CURLPROXY_SOCKS5_HOSTNAME
CURLOPT_FOLLOWLOCATION : 1
When I try download binary file from github, it redirected to amazon clouds and curl tries download file from redirected address not using proxy. So, if I disable direct internet access (only access via socks proxy), download fails.

**Comment by jay** [comment]
Did you set CURLOPT_PROXY? Please give us more information. http://curl.haxx.se/docs/bugs.html#What_to_report

**Comment by Rotkaermota** [comment]
I'm sorry, I hurried.
I tried to reproduce the problem using the latest "curl" command-line utility and found no problem.
It looks like I'm using static-compiled curl library wrong.
