### ISSUE TITLE
Automatic charset decoding?

### ISSUE THREAD

**Issue by denizzzka** [bagder/curl#472]
I am getting URL, server response contains header:

```
Content-Type: text/html; charset=windows-1251
```
but content from the server passed to my UTF-8 console "as is" without decoding cp1251 -> UTF-8 and all Russian text strings in the html looks like garbage.

**Comment by bagder** [comment]
curl dooesn't translate or decode charsets at all. The server is probably sending you the wrong charset  in its header.

**Comment by denizzzka** [comment]
> curl dooesn't translate or decode charsets at all. 

Ok, but why? As is conceived by design?

If user redirects curl output to html file encoding will be loss.

> The server is probably sending you the wrong charset in its header.

No. "iconv -cf cp1251" succesfully decodes this answer into UTF-8.

**Comment by bagder** [comment]
By design indeed, it doesn't interfere with the contents in any way. If you want to convert it based on the headers, I suggest you don't throw away the headers =)

**Comment by denizzzka** [comment]
Ok, I thought it a bug
