### ISSUE TITLE
HTTPS download URLs for 7.45.0 not (yet?) working

### ISSUE THREAD

**Issue by vszakats** [bagder/curl#474]
On http://curl.haxx.se/download.html the "over HTTPS" URLs are not working.
Not sure they were overlooked or they are just not up yet, hence this Issue, just in case.

**Comment by bagder** [comment]
Thanks, I missed that. Hang on...

**Comment by bagder** [comment]
There, fixed now!

**Comment by vszakats** [comment]
Thank you very much @bagder!
