### ISSUE TITLE
Provide a command line option for trusted URI's where sending password is allowed.

### ISSUE THREAD

**Issue by cneberg** [bagder/curl#475]
There needs to be an option to specify trusted URL's for sending authentication credentials when used with multiple redirects.   --location-trusted assumes everything is trusted, which often isn't true, and even --any-auth assumes the site is trusted if the site asks for auth - which also may not be true.    Could you add an option like --auth-locations https://bla.com/login/remoteuser,https://bla2.com/login/remoteuser2.   if either of those uri's (or uri's starting with those paths) ask for authentication send it, otherwise don't and return any errors.

**Comment by bagder** [comment]
I can see how this can be useful and I'll help out with reviews and comments to whoever wants to have a got at it.

**Comment by cneberg** [comment]
Thank you for looking at this.   I notice the new solution checked in only specifies the host name, and not the URL which was what was in the enhancement request.   While I think specifying the whole URL including path is preferable because it fits a lot more security use cases, I can understand if you believe that its overkill but the host method as implemented doesn't allow specifying http vs https.   I think being able to limit the request to just https is also very important.

**Comment by bagder** [comment]
I think it'll work better if you comment the push request in that place and not here so that it is easier for others to fine the feedback on the suggested work.

**Comment by bagder** [comment]
No need to keep this enhancement request open anymore. The associated pull-request seems to have died too but I'm open for new ones or if the existing ones go live again.

**Comment by patrikhson** [comment]
Hey,
Did you hear the latest news? You should definetely read more info here <http://thichunepra.automemberservices.com/xybqy>

paf@frobbit.se
