### ISSUE TITLE
WinRT

### ISSUE THREAD

**Issue by SimmonsTech** [bagder/curl#490]
Hi,
Do you know what happened to the WinRT port of this? I know MSOpenTech were meant to be working with you on this?
Steve

**Comment by bagder** [comment]
I'm not aware of any particular WinRT port, nor even what it means in comparison to the standard windows version.

I don't know what MSOpenTech is but I can assure you no MSOpenTech has been in contact with the project or me as individual regarding curl porting. Porting curl to anything is "just" about adding the necessary code adjustments. curl already builds for and run an a very large amount of platforms. It mostly takes a developer with some time and energy to get it done.

But this is an issue tracker. If you have questions or what to ask general questions, I recommend taking them to the curl-library list.
