### ISSUE TITLE
PolarSSL uses client private RSA key incorrectly

### ISSUE THREAD

**Issue by sasq64** [bagder/curl#495]
`ssl_set_won_cert_rsa()` is always called, regardless of wether the `connssl->rsa` structure was initialized or not (which it usually isn't).

Also `rsa_free()` is called on failure, even though `rsa_init()` is never called on the context.

**Comment by bagder** [comment]
@sasq64 any chance you can show us a suggested fix as a patch?

**Comment by bagder** [comment]
No response, closing
