### ISSUE TITLE
Add support for HTTP2 prio and dependencies

### ISSUE THREAD

**Issue by bagder** [bagder/curl#497]
@tatsuhiro-t, I'm slowly working on adding support for "prio" and dependencies for HTTP/2 to libcurl, and I've pushed my current state of work in a separate [branch](https://github.com/bagder/curl/tree/http2-priodeps).

Now I'm not quite sure how to tell nghttp2 to send out the correct frames when there's an update to push to the other end. Can you please have a look at https://github.com/bagder/curl/commit/cd55d030fa758 when you have a moment, and tell me how you think I should proceed to get it done the "proper" nghttp2 way?

The code is basically remembering the current prio/dep setting and if that is changed, it should queue an update to get sent whenever any other data is sent to the peer. I just haven't figured out how the nghttp2 API for this works!

**Comment by tatsuhiro-t** [comment]
The proper way to notify priority change to server is call nghttp2_submit_priority with nghttp2_priority_spec object.  If priority is known on request time, you can pass the object to nghttp2_submit_headers, which saves extra delay.
Looking at code from L989, note that priority consists of weight, exclusive flag, and dependent stream ID, and they are sent to server atomically, so we should compare these things, and if at least one of them is changed, we have to send PRIORITY frame with the resulting values.

**Comment by bagder** [comment]
Thanks a lot! I'll work something in and ask you for a review later on. Closing this for now.
