### ISSUE TITLE
Support for Botan TLS

### ISSUE THREAD

**Issue by diorahman** [bagder/curl#508]
Is it possible to use Botan TLS http://botan.randombit.net/manual/tls.html as one of the SSL support?

Thanks

**Comment by bagder** [comment]
Nobody has written the necessary libcurl backend glue code for Botan TLS, so no. It is normally not very hard to add support for a new TLS library but someone has to step up and do it.

There are however a vast amount of other TLS library alternatives that are already supported in case you don't feel like working on writing the glue layer for Botan TLS.
