### ISSUE TITLE
Dangling pointer to private key causes crash at Curl_ossl_close()

### ISSUE THREAD

**Issue by nased0** [bagder/curl#509]
I use the engine_pkcs11.dll and enigmap11.dll module for communication with the Encard pkcs11 card to download data from the protected polish government server. 
Unfortunately the libcurl library v. 7.45.0  (and curl.exe) crashes every time at Curl_ossl_close function (on Windows 7), because of the wrong reference count in the private key, which causes freeing memory too early, resulting in dangling pointer in connssl->ctx->cert->pkeys->privatekey, access to deallocated memory and crash (it does not crash on Windows XP, because of weaker memory protection).
Private key is allocated in cert_stuff function, case SSL_FILETYPE_ENGINE: 
by ENGINE_load_private_key function, its pointer is then sent to OpenSSL by SSL_CTX_use_PrivateKey function and then erroneously called EVP_PKEY_free (which decreases reference count) despite SSL_CTX_use_PrivateKey success. After commenting line 595 in openssl.c file libcurl works correctly.
```
--- openssl.c   2015-10-05 00:43:48.000000000 +0200
+++ my/openssl.c        2015-10-27 12:10:46.066604700 +0100
@@ -592,7 +592,6 @@ int cert_stuff(struct connectdata *conn,
             EVP_PKEY_free(priv_key);
             return 0;
           }
-          EVP_PKEY_free(priv_key);  /* we don't need the handle any more... */
         }
         else {
           failf(data, "crypto engine not set, can't load private key");

```

**Comment by bagder** [comment]
Have you found any documentation anywhere that explains that this is how it is supposed to work?

The offending code you point out landed in libcurl in commit af6c394785d, almost 14 years ago!

**Comment by nased0** [comment]
There wasn't Windows 7 14 years ago :) It works fine on Windows XP, but crashes on Windows 7. 
If this code is correct, then this reference counter must be erroneously decreased later.
I just have to make it work, to not get fired.
Please do your own tests with pkcs11 card and protected tls1.1 server.

**Comment by bagder** [comment]
I'd say you're exactly right. The OpenSSL code adds a pointer to the key and seems to take "ownership" of it here: https://github.com/openssl/openssl/blob/master/ssl/ssl_rsa.c#L217

**Comment by bagder** [comment]
Thanks!

**Comment by ghedo** [comment]
@bagder 
> I'd say you're exactly right. The OpenSSL code adds a pointer to the key and seems to take "ownership" of it here: https://github.com/openssl/openssl/blob/master/ssl/ssl_rsa.c#L217

But on the line above it also increases the refcount of the key...

**Comment by bagder** [comment]
Hm, right. But is that because it has taken ownership of it or to allow the free? (I really don't know the openssl internals enough to tell) I have no way to test this myself, but @nased0 have you checked that the function doesn't leak memory after this fix?

**Comment by nased0** [comment]
please wait 30 min.

**Comment by nased0** [comment]
Ok, VS2012 did not report any leaks in curl.exe operations (downloading XML from server protected with pkcs11 card).

**Comment by nased0** [comment]
Please check other uses of SSL_CTX_use_PrivateKey and SSL_CTX_use_PrivateKey_file in openssl.c
There could be similar problems too!

**Comment by ghedo** [comment]
Isn't it possible that it's the engine you are using that frees the key when it's not supposed to?As @bagder pointed out, the `EVP_PKEY_free()` call has been there since forever.

**Comment by nased0** [comment]
Engine_pkcs11.dll was compiled using mingw and it has its own statically linked OpenSSL library, also compiled with mingw.
Libcurl.dll has Openssl linked statically, compiled with VS2012.
So I find impossible for them to share the same memory.

**Comment by nased0** [comment]
Both openssl libs were compiled with no-threads and with -DOPENSSL_NO_LOCKING

**Comment by ghedo** [comment]
> So I find impossible for them to share the same memory

Not sure what you mean by that, but they *are* supposed to share the same memory.

libcurl calls ` ENGINE_load_private_key()` which returns the key loaded from the engine. The key is then passed to `SSL_CTX_use_PrivateKey()` which increases the reference count and later freed.

I really don't think that using different OpenSSL builds for the engine and for curl is advised, or even supported (even if they use the same OpenSSL version). What happens if you use the same build for both?

**Comment by ghedo** [comment]
> libcurl calls ENGINE_load_private_key() which returns the key loaded from the engine

That is, it's the engine itself that allocates the key.

I guess that having a backtrace of the crash would help better pinpoint the problem, but I really don't think that curl is at fault here.

**Comment by nased0** [comment]
Hmm, I meant DLL private heaps.
http://stackoverflow.com/questions/10820114/do-statically-linked-dlls-use-a-different-heap-than-the-main-program

https://www.openssl.org/docs/manmaster/crypto/engine.html
ENGINE_load_private_key()  is an OpenSSL function, not engine function.

**Comment by ghedo** [comment]
> ENGINE_load_private_key() is an OpenSSL function, not engine function

Yes, but it's only a wrapper around the `load_privkey()` engine callback, which is what actually allocates the `EVP_PKEY`:
https://github.com/openssl/openssl/blob/HEAD/crypto/engine/eng_pkey.c#L121

**Comment by nased0** [comment]
I made a screenshot of vs2012 with visible callstack of a crashed libcurl.
![curl_crash](https://cloud.githubusercontent.com/assets/13164219/10762306/cd698024-7cc5-11e5-8220-b25d0af4a08c.png)

**Comment by nased0** [comment]
```
void Curl_ossl_close(struct connectdata *conn, int sockindex)
{
  struct ssl_connect_data *connssl = &conn->ssl[sockindex];

  if(connssl->handle) {
    (void)SSL_shutdown(connssl->handle);
    SSL_set_connect_state(connssl->handle);

    SSL_free (connssl->handle);
    connssl->handle = NULL;
  }
  if(connssl->ctx) {
    SSL_CTX_free (connssl->ctx);
    connssl->ctx = NULL;
  }
}
```
IMO the private key need to be referenced twice, because it is released in the above function for the first time in SSL_free function 
(conn->handle->cert->pkeys->privatekey)
and for the second time in SSL_CTX_free function 
(connssl->ctx->cert->pkeys->privatekey)

**Comment by nased0** [comment]
'''
Yes, but it's only a wrapper around the load_privkey() engine callback, which is what actually allocates the EVP_PKEY:
'''
@ghedo So one module (engine_pkcs11.dll) allocates private key on its private heap, and another module (libcurl.dll) attempts to deallocate this private key from the private heap of another module!
This may be the true cause of this crash on Windows 7 and the reason why it works on Windows XP (and presumably also in Linux) - stricter heap protection.
So according to this hypothesis this patch causes memory leak in engine_pkcs11.dll module, libcurl.dll does not crash because it doesn't deallocate the private key at all. To correctly free it you may need private key deallocating callback to the engine module from the OpenSSL.

@bagder Sorry, but my patch does not solve this problem correctly, only replaces it by memory leak.
I couldn't detect it using VS2012, because it is in engine_pkcs11.dll module. So please revert it for now.

**Comment by nased0** [comment]
The crash may also be caused by the fact that engine_pkcs11.dll compiled by mingw uses another memory allocator (from msvcrt.dll) than libcurl.dll with statically linked openssl (from MSVCR100.DLL or MSVCR110.DLL). 
http://blogs.msdn.com/b/oldnewthing/archive/2006/09/15/755966.aspx
I'll compile openssl with mingw and test it tomorrow with curl engine_pkcs11 operations.

**Comment by nased0** [comment]
Confirmed above theory. 
OpenSSL (compiled with mingw/gcc) and libcurl.dll v.7.45.0 (compiled with VS2012) dynamically linked with it do not crash when deallocating private key allocated by engine_pkcs11.dll (compiled with mingw/gcc).
@badger Please remove my patch.

**Comment by bagder** [comment]
Thanks for your thorough work on this. commit 4c62066ce reverted the change.

**Comment by patrikhson** [comment]
Hi,
Look what I've found on the web, this is something new I guess, you'll be excited. More info here <http://tedispumi.cateblanchett.com/xypatiib>

Bests, paf@frobbit.se

**Comment by patrikhson** [comment]
hey,

Have you seen these impressive pics? They are shocking! Just take a look <http://thophyndasty.terrylhebert.com/xyiki>

Later, paf@frobbit.se
