### ISSUE TITLE
Zip corrupted when sending to FTP folder

### ISSUE THREAD

**Issue by SofianeKali** [bagder/curl#512]
When i send a Zip file from Debian 7 machine to FTP folder hosted on a Windows 8 machine (IIS 8), the Zip is corrupted one in two times.
The command I typed is:
curl -T ZIP-02-11-2015-16-57-54.zip ftp://login:password@ftp/folder

After multiple attempts, I put a --trace to debugging, and there ... strangely it works, my Zip file is not corrupted at all.

curl --trace -T ZIP-02-11-2015-16-57-54.zip ftp://login:password@ftp/folder

**Comment by bagder** [comment]
which curl version is this? (curl -V shows that)

**Comment by SofianeKali** [comment]
I have the problem both in v7.26.0 and v7.45.0

**Comment by jay** [comment]
How is the zip corrupted, and is it corrupted the same way every time? Is it truncated, are a few bytes missing from the beginning, is it bigger in size than what you uploaded, etc.

**Comment by SofianeKali** [comment]
The zip contrains PowerShell, word, excel and text files, it is not bigger (128Ko). In most cases, 1 byte is missing

**Comment by bagder** [comment]
If you store the trace to a file instead of stdout, it will delay the operation less. Can you then get it to fail and also log what curl says it sends? If so, does curl's view of what it sent match what you see ending up on the server?
