### ISSUE TITLE
Can't connect to https://http2.golang.org/

### ISSUE THREAD

**Issue by ismail** [bagder/curl#513]
Using nghttp2 1.3.4, openssl 1.0.2d and curl 7.45.0 on openSUSE Linux x86-64:

λ curl --http2 -v https://http2.golang.org/
*   Trying 130.211.116.44...
* Connected to http2.golang.org (130.211.116.44) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-SHA
* ALPN, server accepted to use h2
* Server certificate:
*        subject: C=US; ST=California; L=Mountain View; O=Google Inc; CN=http2.golang.org
*        start date: Nov 18 14:39:20 2014 GMT
*        expire date: Nov 18 14:39:20 2015 GMT
*        subjectAltName: http2.golang.org matched
*        issuer: C=US; O=Google Inc; CN=Google Internet Authority G2
*        SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* TCP_NODELAY set
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x561a94b86f40)
> GET / HTTP/1.1
> Host: http2.golang.org
> User-Agent: curl/7.45.0
> Accept: */*
>
* http2_recv: 16384 bytes buffer at 0x561a94b878b8 (stream 1)
* http2_recv: 16384 bytes buffer at 0x561a94b878b8 (stream 1)
* TLSv1.2 (IN), TLS alert, Client hello (1):
* Unexpected EOF
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (56) Unexpected EOF

**Comment by MoSal** [comment]
Confirmed.
I tested with the same headers Firefox sends. And it still errors.

**Comment by bagder** [comment]
Being discussed in #406 where we sort of wait for a response from the go team...

**Comment by ismail** [comment]
Closing as a dup then, thank you!
