### ISSUE TITLE
curl tool option to percent-encode the passed raw URL

### ISSUE THREAD

**Issue by vszakats** [bagder/curl#514]
In certain situations it'd would be useful if `curl` (the tool) could translate a raw URL (f.e. containing spaces or other special characters) passed to its command-line to the [percent-encoded](https://en.wikipedia.org/wiki/Percent-encoding) (AKA 'URL encoded') version that would then be used to make the actual request.

This could be handy on Windows mainly, where the `%` sign has special uses, so including it in a command may be problematic (needs different escaping on the command-line, inside a batch file, in shell script), ~~or [impossible](https://github.com/appveyor/ci/issues/246)~~.

So f.e. this line:
```
curl -O https://example.com/hello%20world.txt
```
could become:
```
curl -O "https://example.com/hello world.txt" -rawurl
```

~~Required low-level logic is already implemented in the codebase as [`curl_easy_escape()`](http://curl.haxx.se/libcurl/c/curl_easy_escape.html).~~

**Comment by bagder** [comment]
One problem would be that you probably don't want it to become fully "URL encoded" (as said libcurl function would make it) as then for example the slashes would also be encoded... It sounds to me like you're looking to getting some specific letters to get encoded, like space for example.

**Comment by vszakats** [comment]
Yes, exactly, thanks for pointing that out. Spaces, percent-sign look like good candidates to start with.

(I've updated the original message)

**Comment by patrikhson** [comment]
Hi,

I've visited a wonderful place recently, it amazed me! Just take a look here <http://syfedoma.highspeedi.com/xyudy>

paf@frobbit.se

**Comment by vszakats** [comment]
@patrikhson Looks like something is spamming this space on your behalf.

**Comment by bagder** [comment]
Yeah and I  have no way to block a specific user or email address other than to report them for abuse but I  did it now in an attempt to stop this flood.

**Comment by kdudka** [comment]
On Tuesday, July 12, 2016 08:28:02 Daniel Stenberg wrote:
> Yeah and I  have no way to block a specific user or email address other than
> to report them for abuse but I  did it now in an attempt to stop this
> flood.

So did I (together with request to delete the comments).  Then I spotted that 
@patrikhson posted a "normal" comment in 2013.  Looks like somebody hacked his 
account recently.

**Comment by bagder** [comment]
Yes I know Patrik Fältström so I know this isn't him. But AFAIK there's nothing preventing you from sending emails to github and just forging the From address.

**Comment by vszakats** [comment]
I believe it's not enough to spoof the sender address to be able to post to spaces like this. One needs to also obtain a valid reply address, which looks like this in case of GitHub:

reply+<very-long-unique-hex-id>@reply.github.com

Assuming such reply ID cannot be spoofed, it should be harvested from email archives in some ways.

**Comment by vszakats** [comment]
One stop-gap solution is to _lock_ old Issues and other places where he appears as participant.

**Comment by jay** [comment]
No that shouldn't be necessary. I wrote GitHub about this and they are going to look into that account to improve their spam protection. Clearly no person would post that many messages in such a short period of time, only an automated process. The content was also suspect.

Collaborators are limited in how they can handle abuse like this to reporting it, Owners however can throw down the hammer I believe by ignoring the user because when you ignore a user it should ban them from posting comments in any repos they own. That may be different for organizations (which we are) so @bagder should this happen again you could also try https://help.github.com/articles/blocking-a-user-from-your-organization/

**Comment by bagder** [comment]
I noticed already 10 hours ago that github admins had removed the spam comments (I think several of us reported the incident). At least all the ones I checked.

**Comment by svnpenn** [comment]
@bagder its nice that you added this to the TODO list, but that doesnt really, or shouldnt really close this issue

also that was over a year ago

**Comment by bagder** [comment]
@svnpenn: we don't keep issues open if nobody intends to work on them: https://curl.haxx.se/docs/bugs.html#Closing_off_stalled_bugs
