### ISSUE TITLE
Which thread lib are you using

### ISSUE THREAD

**Issue by RustJason** [bagder/curl#519]
Hey, Today I want to learn how you implement multi_curl. and run this command:
```
strace -eclone ./multi-app
```
It pops out this:
```
clone(child_stack=0x7f78c6b2af70, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f78c6b2b9d0, tls=0x7f78c6b2b700, child_tidptr=0x7f78c6b2b9d0) = 2612
clone(child_stack=0x7f78c6329f70, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f78c632a9d0, tls=0x7f78c632a700, child_tidptr=0x7f78c632a9d0) = 2613
clone(child_stack=0x7f78c5b28f70, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f78c5b299d0, tls=0x7f78c5b29700, child_tidptr=0x7f78c5b299d0) = 2614
```

But I can't see those thread under ```ps``` and ```htop```, This makes me very confuse and I decided to compile this library from source.
After I finished and reruned my code again. Things gets more strange, cause It won't output any syscall of ```clone()``` to me. So I tried to comfirm my libcurl version and it was:
```
c/curl [ curl --version                                                                                                              ] 6:25 PM
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP 

```
So, I use ```git checkout```  to  the tag of  7.35.0 then recompiled again and reinstall.
Unfortunately, I didn't get what I was expected.
As long as I use 'compile from source edition libcurl', It won't do any syscall of ```clone()```
What is wrong with my operation? Did you remove thread since a new release?

Thanks in advance.

**Comment by bagder** [comment]
If you build with the threaded resolver, it will create and use a pthread to resolve the host names in.
