### ISSUE TITLE
DNSSEC via cloudflare

### ISSUE THREAD

**Issue by scriptzteam** [bagder/curl#527]
I just enabled dnssec via cloudlfare on site, but after i wanted curl the site via ssh terminal, all i got was Connection Refused.

**Comment by bagder** [comment]
Connection refused means there's no server listening on the port. It is not related to dnssec.

**Comment by scriptzteam** [comment]
Yes it is, i am set on cloudflare DNSSEC option to enable before i was able to curl site after set cloudflare DNSSEC and added godaddy DS record all i get via curl was connection refused, but dunno why?

**Comment by scriptzteam** [comment]
curl https://skripterz.info
curl: (6) Could not resolve host: skripterz.info

-----
DNSSEC is active
 	Found 1 DS records for skripterz.info in the info zone
	Found 1 RRSIGs over DS RRset
	RRSIG=59270 and DNSKEY=59270 verifies the DS RRset

**Comment by bagder** [comment]
That's not connection refused. It appears you lack A and AAAA entries. Tried 'dig' the name?

**Comment by bagder** [comment]
No response
