### ISSUE TITLE
Multihandle crashes on iOS 9 when closing a socket marked as guarded

### ISSUE THREAD

**Issue by BaraBaltico** [bagder/curl#531]
I've had this crash on iOS 9.1 using libcurl 7.42.1

Exception Type: EXC_GUARD
Exception Subtype: GUARD_TYPE_FD
Exception Message: CLOSE on file descriptor 14 (guarded with 0x08fd4dbfade2dead)
Triggered by Thread: 101

Thread 101 name: 0x1723b7000
Thread 101 Crashed:
0 libsystem_kernel.dylib 0x0000000199c35db4 close + 8
1 Jabber 0x0000000101b75af8 Curl_closesocket + 76
2 Jabber 0x0000000101b6aaa4 conn_free + 88
3 Jabber 0x0000000101b6a9c8 Curl_disconnect + 184
4 Jabber 0x0000000101b6e310 disconnect_if_dead + 140
5 Jabber 0x0000000101b6e338 call_disconnect_if_dead + 12
6 Jabber 0x0000000101b82f04 Curl_conncache_foreach + 116
7 Jabber 0x0000000101b6ca98 Curl_connect + 6456
8 Jabber 0x0000000101b78378 multi_runsingle + 312
9 Jabber 0x0000000101b780f8 curl_multi_perform + 172

Investigating the exception it comes out that it is thrown by Apple operating systems when attempting to use standard posix API on a file descriptor that has been opened specifying the "guarded" flag. Such a file descriptor once opened needs to be accessed using special guard-aware APIs. Otherwise it throws this exception.

Now I'm not sure if libcurl is opening his socket using the guarded flag but in case it doesn't what can be happening here is that the file descriptor:
- has been closed once by libcurl --> all good
- as been reopened by another application with the guarded flag  --> all good
- has been closed again by libcurl --> crash

So I suspect a double close that unfortunately ended up on a special file descriptor

**Comment by bagder** [comment]
We don't use any "guarded flag" (and this is the first time I ever read anything about them existing).

A double-close also seems a bit unlikely, but is certainly possible. You need to help us repeat this (== provide more details on how to reproduce) or dig further yourself to see what actually causes the exception. I personally don't have iOS myself so I would try to repeat your problem using another platform.

**Comment by nickzman** [comment]
Guarded resources are created on Apple operating systems using a private API. We don't use private API in curl for obvious reasons, so the socket descriptor must have been opened elsewhere. Are you using Core Data by any chance?

Here is what I could find on the subject: https://developer.apple.com/library/prerelease/ios/technotes/tn2151/_index.html

**Comment by BaraBaltico** [comment]
I've just verified that our application doesn't use the Apple private API so we are not explicitely marking any app owned file descriptor guarded.
The crash happened only once and unfortunately I'm unable to reproduce it.

**Comment by bagder** [comment]
okay, if you manage to repeat it or find other details that can help then we'll consider to go further. until then I close this report.
