### ISSUE TITLE
MSI installer don't not broadcast the WM_SETTINGCHANGE message

### ISSUE THREAD

**Issue by Sanchiezz** [bagder/curl#541]
MSI installer doesn't not broadcast the WM_SETTINGCHANGE message after path to 'bin' directory was added to PATH environment variable, and this change doesn't take effect untill system reboot.

**Comment by bagder** [comment]
Which MSI installer are you talking about?

**Comment by Sanchiezz** [comment]
Just today I've used "curl-7.45.0-win64.msi"

**Comment by bagder** [comment]
That means you downloaded a binary curl package a friendly volunteer put together for you. Possibly you found the package here: http://www.confusedbycode.com/curl/

That installer is not part of what we in the curl project host or work on, it was added and provided by the person or team that created the package you downloaded. They are probably not monitoring this issue tracker. I'd advice you to contact the ones who made the package you downloaded, and work with them to resolve your issue!

**Comment by Sanchiezz** [comment]
OK, I understand you.
Thank you.
