### ISSUE TITLE
32bit and 64bit of curl.exe (without SSL)

### ISSUE THREAD

**Issue by westor7** [bagder/curl#542]
Hello,

I wanna ask for a link about 32bit and 64bit curl.exe WITHOUT any SSL libraries, can someone help me about this because on the Downloads into the main site of the cURL i got confused.

- Thanks!

**Comment by bagder** [comment]
This is not a support forum, this is an issue tracker. Use the curl-users mailing list for questions. See http://curl.haxx.se/dlwiz/?type=bin&os=Win32&flav=-&ver=- for windows binary downloads.
