### ISSUE TITLE
darwinssl appears to fail if both verifypeer and verifyhost are false

### ISSUE THREAD

**Issue by rmccue** [bagder/curl#547]
Reporting this upstream from [WordPress Trac](https://core.trac.wordpress.org/ticket/34794). Discussion on that ticket covers the details (particularly [this comment](https://core.trac.wordpress.org/ticket/34794#comment:7)), but the summary essentially is:

On OSX Server 5 (OSX 10.10.5 and 10.11.1 both tested) with RC4 disabled, loopback connections through cURL fail with `SSLRead() return error -9841` (`errSSLServerAuthCompleted` per [Apple's docs](https://developer.apple.com/library/mac/documentation/Security/Reference/secureTransportRef/#//apple_ref/c/econst/errSSLServerAuthCompleted)). Both verifypeer (`CURLOPT_SSL_VERIFYPEER`) and verifyhost (`CURLOPT_SSL_VERIFYHOST`) must be off (`0`/`false` internally).

This error code is handled in `darwinssl_connect_step2` [here](https://github.com/bagder/curl/blob/4f037367ed69b77e14953fe88d8c0497782c0aab/lib/vtls/darwinssl.c#L1837-L1847), but per the error message, the code appears to be returned in `darwinssl_recv` instead from `SSLRead`.

[This PHP script](https://gist.github.com/rmccue/64e6a89e900cbe33d7eb) should replicate the issue.

**Comment by bagder** [comment]
ping @nickzman

**Comment by nickzman** [comment]
Have you reported this to Apple? SSLRead() should never return any error state other than an I/O error, or an informative message such as "ask me again because this might block" or "the remote server terminated the connection." If it's returning -9841, then that suggests that the context's internal state is screwed up, and we're not using the context in any undocumented way, so it seems to me this is for Apple to investigate.

**Comment by rmccue** [comment]
I've not reported this to Apple, merely passing it up from the WordPress bug tracker. I can do so, though I'm not an experienced C developer, so I can't say I understand the API very well. :)

**Comment by nickzman** [comment]
Go to https://bugreport.apple.com/ and sign in with an Apple ID. Then create a report that shows how to get SSLRead() to malfunction. You can cite curl/libcurl in the steps to reproduce.

**Comment by bbc-tomfitzhenry** [comment]
I have also experienced `curl: (56) SSLRead() return error -9841`.

I tried to sign up on https://bugreport.apple.com/ to file a bug, but it required I had an Apple developer account, which costs £79 for a year, so I didn't sign up.
