### ISSUE TITLE
configure/building on OSX:: SSL lib

### ISSUE THREAD

**Issue by gaming-hacker** [bagder/curl#550]
hello,
i can successfully build/configure curl with following results

curl 7.46.1-DEV (x86_64-apple-darwin15.0.0) libcurl/7.46.1-DEV OpenSSL/0.9.8zd zlib/1.2.5 c-ares/1.10.0 libidn/1.32 libssh2/1.6.0 nghttp2/1.5.0 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets Metalink 

as you can see it is using OpenSSL/0.9.8zd which is the default for OSX 10.11,  i have install installed via home-brew openssl and have this set in the configure script

from Makefile
~~~
CPPFLAGS = -I/Users/glen/abrew/Cellar/c-ares/1.10.0/include -I/Users/glen/abrew/Cellar/libidn/1.32/include -pipe -march=native -mmacosx-version-min=10.11 -isystem /Users/glen/myLocal/include -isystem /Users/glen/abrew/include -isystem  -I/Users/glen/abrew/opt/openssl/include -isystem /usr/local/include -isystem /opt/X11/include -isystem /Developer/NVIDIA/CUDA-7.5/include -isystem /Users/glen/myLocal/openmpi/include -isystem /usr/include -I/usr/include -I/Users/glen/abrew/opt/libssh2/include -I/Users/glen/abrew/Cellar/rtmpdump/2.4+20150115/include -I/Users/glen/abrew/Cellar/nghttp2/1.5.0/include

LDFLAGS = -L/Users/glen/abrew/Cellar/c-ares/1.10.0/lib -L/Users/glen/abrew/opt/openssl/lib  -L/Users/glen/abrew/Cellar/libidn/1.32/lib -L/usr/lib -L/Users/glen/abrew/opt/libssh2/lib -L/Users/glen/abrew/Cellar/rtmpdump/2.4+20150115/lib -L/Users/glen/abrew/Cellar/nghttp2/1.5.0/lib
LIBCURL_LIBS = -lcares -lnghttp2 -lidn -lssh2 -lssl -lcrypto -lz -lgssapi_krb5 -lresolv -lldap -lz

LIBS = -lcares -lnghttp2 -lidn -lssh2 -lssl -lcrypto  -lz -lgssapi_krb5 -lresolv -lldap -lz
~~~
also where is libcrypto?

I can't seem to figure why configure is not obeying the configure and using the system default?

any help?

**Comment by gaming-hacker** [comment]
ok i'll give it a try,  here's what otool reports

	/Users/glen/myLocal/lib/libcurl.4.dylib (compatibility version 9.0.0, current version 9.0.0)
	/Users/glen/abrew/opt/libmetalink/lib/libmetalink.3.dylib (compatibility version 5.0.0, current version 5.0.0)
	/Users/glen/abrew/opt/c-ares/lib/libcares.2.dylib (compatibility version 4.0.0, current version 4.0.0)
	/Users/glen/abrew/opt/nghttp2/lib/libnghttp2.14.dylib (compatibility version 18.0.0, current version 18.0.0)
	/Users/glen/abrew/opt/libidn/lib/libidn.11.dylib (compatibility version 18.0.0, current version 18.15.0)
	/Users/glen/abrew/lib/libssh2.1.dylib (compatibility version 2.0.0, current version 2.1.0)
	/usr/lib/libssl.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/usr/lib/libcrypto.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos (compatibility version 5.0.0, current version 6.0.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/LDAP.framework/Versions/A/LDAP (compatibility version 1.0.0, current version 2.4.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)

**Comment by bagder** [comment]
> also where is libcrypto?

What do you mean? There's a "-lcrypto" in the snippet just above your question. Is that not enough?

If configure detects the wrong lib, you should probably investigate `config.log` after completion to see what it says about the checks and detection. In your case it seems it defaults back to the standard place and detects your default install instead of the special one you wanted it to use.

**Comment by gaming-hacker** [comment]
thanks.
there are multiple versions of ssl laying around on OSX, the default, homebrew versions of openssl and libressl, for some reason either pkg-config or the ENV is only picking up the default even though with configure i specified the exact --with-path, probably something about multiple ssl's. 

oh well, eventually i forced the ENV and not to use default libs and installed with libressl. it works.
