### ISSUE TITLE
How can I push something one by one?(C++)

### ISSUE THREAD

**Issue by JamesXu20150314** [bagder/curl#551]
Hello,

I want to know how can I know that when I pushed a source.
 if I have received a request from client, I want to response the request with some sources. But I want to push some sources to client, I want to push the source one by one. It means that I want to push next source after I have accomplished push the last one. But how can I get the  signal that the source has pushed the last one to the client from the server side.

I use the response.on_close() function. But I found that the function is invoked after the request and response are finished. So I can not continue to push next source to the client.

Thanks.

JamesXu.

**Comment by bagder** [comment]
I don't understand what you're asking. curl is client-side only and you seem to be talking about how to send data from the server?

Also, this is an issue tracker. If you need help or have questions on how to use libcurl or possibly how to improve libcurl, then the curl-library mailing list is the suitable place.
