### ISSUE TITLE
Unclear error message

### ISSUE THREAD

**Issue by haegemon** [bagder/curl#552]
Hello. I got some mistery error `Connection timed out after 5516 milliseconds` at working with php-curl. I tested this situation and find that I got this bug when I overflow user limits:

```
>ulimit -n 100
>echo "<?php \$i=1; while(1){ \$x = curl_init('http://google.com'); curl_setopt(\$x, CURLOPT_TIMEOUT, 5); curl_setopt(\$x, CURLOPT_RETURNTRANSFER, 1); curl_exec(\$x); var_dump(curl_error(\$x), \$i++); \$antigc[] = \$x; }" | php

```

I think that curl should show more clear error message at this situation.

**Comment by bagder** [comment]
"more clear" ? It returns an error code saying it timed out, the error message says it timed out and after how long time. What exactly is not clear and how can we make it clearer?

**Comment by haegemon** [comment]
As I understand real bug is that curl can`t open new file for connection. It wait a possibility of open and then shutdown by timeout. Might message show any information about it?

**Comment by bagder** [comment]
I don't understand. Why would that be the problem here? I don't think it is.

**Comment by haegemon** [comment]
We develop a big application based on service architecture. All services have a lot of curl connection one another. Error message 'Connection timed out after X milliseconds' say nothing about problem at open files at server. 'Connection timed out after X milliseconds' means that there is error at network most common. There is a very surprised that this error means error at server and count of processes.

**Comment by bagder** [comment]
curl can only report about problems it sees or gets. In this case, curl has no problem with neither files nor processes. That problem can of course exist in the server end, which then might be the problem that causes it to respond slowly and thus trigger the timeout in curl.

Barring me misunderstanding what you're reporting, I don't see what else curl can do.

**Comment by Tatikoma** [comment]
Why curl cant check if nofile limits exceed and display suitable error?

**Comment by haegemon** [comment]
As shared library curl has full access to process and has a lot information of server at all. Before open connection curl might check is any file descriptor. If there is no one throw exception about it. 
It's possible and might be simply realize.

**Comment by bagder** [comment]
curl has not reached that limit so it doesn't warn about it. **If** curl would hit that limit it would say so.

**Comment by Tatikoma** [comment]
Okay, but if curl doesnt reached that limit, please help me to understand why when i change $ulimit -n it prevents curl from executing requests? - I just copied code from top comment and changed limit from 100 to 10.
![nofile_error](https://cloud.githubusercontent.com/assets/1888609/11590834/28627818-9aa4-11e5-8af5-8586f3b7b354.png)

**Comment by bagder** [comment]
First, can you start with enabling verbose so we see what curl says about things, then can you show us what libcurl returns in that error situation? You keep drawing conclusions but I'd say that if curl returns a timeout and it reports a timeout in the message then we can only argue if it would detect another problem earlier - a problem I don't think it has but I'm willing to say that we of course have bugs so that can be one.

I don't run any PHP stuff myself so I can't test this easily on my own just yet, but I'm willing to write up a more plain libcurl-using app later to see if I can reproduce.

Also, what libcurl version is this on what platform?

**Comment by haegemon** [comment]
Platform Debian 7, Ubuntu 14.04
version 7.35.0

```
> php -r "var_dump(curl_version());"
array(9) {
  ["version_number"]=>
  int(467712)
  ["age"]=>
  int(3)
  ["features"]=>
  int(50877)
  ["ssl_version_number"]=>
  int(0)
  ["version"]=>
  string(6) "7.35.0"
  ["host"]=>
  string(19) "x86_64-pc-linux-gnu"
  ["ssl_version"]=>
  string(14) "OpenSSL/1.0.1f"
  ["libz_version"]=>
  string(5) "1.2.8"
  ["protocols"]=>
  array(19) {
    [0]=>
    string(4) "dict"
    [1]=>
    string(4) "file"
    [2]=>
    string(3) "ftp"
    [3]=>
    string(4) "ftps"
    [4]=>
    string(6) "gopher"
    [5]=>
    string(4) "http"
    [6]=>
    string(5) "https"
    [7]=>
    string(4) "imap"
    [8]=>
    string(5) "imaps"
    [9]=>
    string(4) "ldap"
    [10]=>
    string(5) "ldaps"
    [11]=>
    string(4) "pop3"
    [12]=>
    string(5) "pop3s"
    [13]=>
    string(4) "rtmp"
    [14]=>
    string(4) "rtsp"
    [15]=>
    string(4) "smtp"
    [16]=>
    string(5) "smtps"
    [17]=>
    string(6) "telnet"
    [18]=>
    string(4) "tftp"
  }
}
```

**Comment by bagder** [comment]
Cannot reproduce. I set 'ulimit -n 6' and I run my test program using pure libcurl and it just works. How many loops do you need to get to happen? 100 loops is no problem here.

$ ulimit -n 6
$ $ ./debugit 
Did try 0
Did try 1
Did try 2
Did try 3
Did try 4
Did try 5
Did try 6
Did try 7
Did try 8
Did try 9
Did try 10
Did try 11
Did try 12
Did try 13
[snip]

I used this code:
~~~~~
#include <stdio.h>
#include <curl/curl.h>

/* CURLOPT_WRITEFUNCTION */
static size_t write_cb(void *ptr, size_t size, size_t nmemb, void *data)
{
  size_t realsize = size * nmemb;
  (void)data;
  (void)ptr;
  return realsize;
}

int main(void)
{
  CURL *curl;
  CURLcode res;

  curl = curl_easy_init();
  if(curl) {
    int i;
    for(i=0; i < 100; i++) {

      curl_easy_setopt(curl, CURLOPT_URL, "http://google.com");
      curl_easy_setopt(curl, CURLOPT_TIMEOUT, 5L);
      curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, write_cb);

      /* Perform the request, res will get the return code */
      res = curl_easy_perform(curl);
      /* Check for errors */
      if(res != CURLE_OK) {
        fprintf(stderr, "curl_easy_perform() failed: %s\n",
                curl_easy_strerror(res));
        break;
      }
      fprintf(stderr, "Did try %d\n", i);
    }

    /* always cleanup */
    curl_easy_cleanup(curl);
  }
  return 0;
}

**Comment by mawajdak** [comment]
Free good
