### ISSUE TITLE
curl-7.46.0 requires perl and GNU make

### ISSUE THREAD

**Issue by 0-wiz-0** [bagder/curl#555]
curl up to 7.45.0 could be built without perl and GNU make (BSD make was fine).
In 7.46.0, the zsh support in scripts/ made both of these tools necessary.

```
gmake[1]: Entering directory '/scratch/www/curl/work/curl-7.46.0/scripts'
/usr/pkg/bin/perl zsh.pl > _curl
curl: not found
Use of uninitialized value $opts_str in scalar chomp at zsh.pl line 16.
Use of uninitialized value $opts_str in concatenation (.) or string at zsh.pl line 18.
````

About GNU make: The new Makefile rule is:
````
$(ZSH_COMPLETION_FUNCTION_FILENAME): zsh.pl
        $(PERL) $< > $@
```
This is an explicit rule that uses "$<". The man page for BSD make (on NetBSD) says about "$<":
````
             .IMPSRC   In suffix-transformation rules, the name/path of the
                       source from which the target is to be transformed (the
                       ``implied'' source); also known as `<'.  It is not
                       defined in explicit rules.
````
I.e., it's supported only in implicit rules.
I suggest just using "zsh.pl" instead of "$<".

About perl: perhaps there is a way to use awk or sed instead. Either way, the warnings should be fixed, and it should be passed a path to curl.

**Comment by bagder** [comment]
Thanks, fixed now. It doesn't work without perl now but it should at least handle it gracefully.
