### ISSUE TITLE
curl could warn the user that his .netrc file has insecure modes

### ISSUE THREAD

**Issue by landryb** [bagder/curl#557]
Much like ssh does when .ssh isnt mode 700 or authorized_keys (or hosts file or ssh keys..) is not mode 600, when using -n curl could check for the mode/ownership on the .netrc file and warn the user (here? https://github.com/bagder/curl/blob/master/lib/netrc.c#L112)  if it is group/world-readable/writable, ie anything different from 400 or 600 and owned by the user.

**Comment by bagder** [comment]
It could. Feel like implementing that?

**Comment by landryb** [comment]
Possibly, i have to dive into the code..

**Comment by bagder** [comment]
Then feel free to send a pull-request send a patch (that goes for anyone interested in helping out here). I don't think we need to keep this issue open for this.
