### ISSUE TITLE
build failure for curl 7.46 for nghttp2 usage ?

### ISSUE THREAD

**Issue by centminmod** [bagder/curl#559]
Didn't have any problems with my Ubuntu nghttp2 docker image rebuilds https://hub.docker.com/r/centminmod/docker-ubuntu-nghttp2/ until curl 7.46. Docker builds now fail and it's at curl 7.46 compile stage that there are problems.

The relevant line is line 21 of Dockerfile run outlined at https://github.com/centminmod/docker-ubuntu-nghttp2/blob/master/Dockerfile#L21 and build log line for curl failure at https://gist.github.com/centminmod/667d9441d1fc0986226a

and output specifically for this part is

    curl version:     7.46.1-DEV
    Host setup:       x86_64-unknown-linux-gnu
    Install prefix:   /usr/local/http2-15
    Compiler:         gcc
    SSL support:      enabled (OpenSSL)
    SSH support:      enabled (libSSH2)
    zlib support:     enabled
    GSS-API support:  no      (--with-gssapi)
    TLS-SRP support:  enabled
    resolver:         POSIX threaded
    IPv6 support:     enabled
    Unix sockets support: enabled
    IDN support:      no      (--with-{libidn,winidn})
    Build libcurl:    Shared=yes, Static=no
    Built-in manual:  no      (--enable-manual)
    --libcurl option: enabled (--disable-libcurl-option)
    Verbose errors:   enabled (--disable-verbose)
    SSPI support:     no      (--enable-sspi)
    ca cert bundle:   /etc/ssl/certs/ca-certificates.crt
    ca cert path:     no
    LDAP support:     no      (--enable-ldap / --with-ldap-lib / --with-lber-lib)
    LDAPS support:    no      (--enable-ldaps)
    RTSP support:     enabled
    RTMP support:     no      (--with-librtmp)
    metalink support: no      (--with-libmetalink)
    PSL support:      no      (libpsl not found)
    HTTP2 support:    enabled (nghttp2)
    Protocols:        DICT FILE FTP FTPS GOPHER HTTP HTTPS IMAP IMAPS POP3 POP3S RTSP SCP SFTP SMB SMBS SMTP SMTPS TELNET TFTP
    Making all in lib
    make[1]: Entering directory '/usr/local/src/libcurl_static/lib'
    make  all-am
    make[2]: Entering directory '/usr/local/src/libcurl_static/lib'
    CC       libcurl_la-file.lo
    CC       libcurl_la-timeval.lo
    CC       libcurl_la-base64.lo
    CC       libcurl_la-hostip.lo
    CC       libcurl_la-progress.lo
    CC       libcurl_la-formdata.lo
    CC       libcurl_la-cookie.lo
    CC       libcurl_la-http.lo
    [91mhttp.c: In function 'output_auth_headers':
    [0m
    [91mhttp.c:643:11: error: 'data' undeclared (first use in this function)
         infof(data, "%s auth using %s with user '%s'\n",
               ^
    [0m
    [91mhttp.c:643:11: note: each undeclared identifier is reported only once for each function it appears in
    [0m
    Makefile:1178: recipe for target 'libcurl_la-http.lo' failed
    make[2]: Leaving directory '/usr/local/src/libcurl_static/lib'
    [91mmake[2]: *** [libcurl_la-http.lo] Error 1
    [0m
    Makefile:704: recipe for target 'all' failed
    [91mmake[1]: *** [all] Error 2
    [0m
    make[1]: Leaving directory '/usr/local/src/libcurl_static/lib'
    Makefile:868: recipe for target 'all-recursive' failed
    [91mmake: *** [all-recursive] Error 1
    [0m
    [91m/bin/sh: 1: [0m
    [91m/usr/local/http2-15/bin/curl: not found[0m

not sure exactly what has changed ?

any help is appreciated :)

George

**Comment by bagder** [comment]
Thanks!

Yeah, you want basically this fix: 034317d2af3987 ie make the declaration there to be unconditional. The commit I link is the second fix for the same line so it doesn't apply as-is to 7.46.0 but I think the point is clear. As you can see, this is now fixed in git.

**Comment by dfandrich** [comment]
This looks like the issue with --disable-verbose that was just fixed in
commit b6d5cb40

**Comment by centminmod** [comment]
cheers @bagder @dfandrich compiles work well now :)
