### ISSUE TITLE
Merge MinGW-package patches

### ISSUE THREAD

**Issue by mback2k** [bagder/curl#560]
The MINGW-packages project seems to use 3 custom patches to make curl compile using MSYS2. I never had issues compiling curl without these patches from source, but someone should figure out if it makes sense to merge those changes upstream: https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-curl

**Comment by bagder** [comment]
The 0001-curl-relocation.patch is a big one and I would like to have someone explain and clarify what purpose it serves. The other two seem to be more straight-forward and mostly just leave me wanting to know why they haven't been sent to us...

**Comment by bagder** [comment]
(I've merged the 0002 and 0003 patches now)

Perhaps @Chilledheart or @Alexpux can educate us on the benefits of the 0001 patch?

**Comment by mback2k** [comment]
It seems like patch 0001 was originally introduced in https://github.com/Alexpux/MINGW-packages/commit/66664b3f480b4239fbbc3acdbc0d8c332a978b90.

**Comment by bagder** [comment]
But do you understand its purpose?

**Comment by mback2k** [comment]
No, sorry. From the description it seems like it has to do something with support for the binary being relocatable, but that does not really make sense to me. It also looks like the patch includes functions to handle different-style paths, e.g. / vs. \ as path element.

**Comment by bagder** [comment]
So let's see if we can get someone to educate us, otherwise I'll close this later.

**Comment by bagder** [comment]
Silence. We can always open it again later if something turns up.
