### ISSUE TITLE
Trailers not output for HTTP2

### ISSUE THREAD

**Issue by louiscryan** [bagder/curl#561]
cc @tatsuhiro-t 

Trailers are output for HTTP/1.1 with chunked encoding but not output for h2.

Easiest way to reproduce is the build nghttp2 from head with its applications, then run the webserver with TLS enabled

src/nghttpd -v -d . --trailer='foo: bar' 8080 some.key some.pem

curl -v --raw --http2 --insecure https://localhost:8080/README  --> No trailers output
src/nghttp -v https://localhost:8080/README  --> Shows trailers being received

**Comment by tatsuhiro-t** [comment]
curl does not support HTTP/2 trailer yet.
I have PR for this.  See #564.

**Comment by bagder** [comment]
Fixed by @tatsuhiro-t and merged in 15cb03ad846a

**Comment by louiscryan** [comment]
Very cool. Thanks!
