### ISSUE TITLE
winssl curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_INVALID_TOKEN (0x80090308)

### ISSUE THREAD

**Issue by dfangboy** [bagder/curl#568]
C:\curl-7.46.0\src>curl -V
curl 7.46.0 (i386-pc-win32) libcurl/7.46.0 WinSSL zlib/1.2.7
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp
smb smbs smtp smtps telnet tftp
Features: AsynchDNS Largefile SSPI Kerberos SPNEGO NTLM SSL libz

C:\curl-7.46.0\src>curl https://fp.gdltax.gov.cn/
curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_INVALID_TOKEN
(0x80090308) - 给函数提供的标志无效

C:\curl-7.46.0\src>curl -k https://fp.gdltax.gov.cn/
curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_INVALID_TOKEN
(0x80090308) - 给函数提供的标志无效

**Comment by mback2k** [comment]
Does your Windows installation trust the self-signed certificate of fp.gdltax.gov.cn? Please check if you can connect using Internet Explorer.

**Comment by dfangboy** [comment]
http://chuantu.biz/t2/22/1450351246x-1376440154.jpg
http://chuantu.biz/t2/22/1450351275x-1376440132.jpg

**Comment by mback2k** [comment]
So, Windows / Internet Explorer does not trust the certificate either. You must import the self-signed certificate into the Windows Trust Store. You can open it by typing certmgr.msc into the start menu.

**Comment by dfangboy** [comment]
https://www.12306.cn/mormhweb/
C:\curl-7.46.0\src>curl https://www.12306.cn/mormhweb/
curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT
 (0x80090325) - 证书链是由不受信任的颁发机构颁发的。  

C:\curl-7.46.0\src>curl -k https://www.12306.cn/mormhweb/  ---ok

http://chuantu.biz/t2/22/1450352827x-1376440132.jpg
http://chuantu.biz/t2/22/1450352850x-1376440132.jpg

**Comment by bagder** [comment]
@dfangboy : that's exactly what @mback2k is saying. You don't have that root trusted so without -k curl won't get the resource. Isn't that clear?

**Comment by dfangboy** [comment]
Already know. Thank you.
-k is not skip verification, so ask.
