### ISSUE TITLE
curl forcefully print output to STDOUT  when gets called with `-G` parameter

### ISSUE THREAD

**Issue by melezhik** [bagder/curl#572]
Please compare results of these two identical requests:
```
vagrant@Debian-jessie-amd64-netboot:~/projects/sph$ curl -G 'foo=bar' http://curl.haxx.se/ -o /dev/null | head
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2376  100  2376    0     0    378      0  0:00:06  0:00:06 --:--:--   632
100  3033  100  3033    0     0   2661      0  0:00:01  0:00:01 --:--:--     0
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
<title>curl and libcurl</title>
<meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
<link rel="stylesheet" type="text/css" href="http://curl.haxx.se/curl.css">
<link rel="shortcut icon" href="http://curl.haxx.se/favicon.ico">
</head>
<body bgcolor="#ffffff" text="#000000">
<div class="main">

 
# VERSUS


vagrant@Debian-jessie-amd64-netboot:~/projects/sph$ curl 'http://curl.haxx.se?foo=bar' -o /dev/null | head
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3033  100  3033    0     0    472      0  0:00:06  0:00:06 --:--:--   778
```

**Comment by kdudka** [comment]
On Monday 21 December 2015 03:19:23 Alexey wrote:
> Please compare results of these two identical requests:
> ```
> vagrant@Debian-jessie-amd64-netboot:~/projects/sph$ curl -G 'foo=bar'
> http://curl.haxx.se/ -o /dev/null | head

You are using the -G option in a wrong way.  It does not take any argument.  
Consequently, the string foo=bar is taken as the first URL, whose output is 
correctly written to /dev/null, whereas output of the actual URL is then 
written to stdout.

I guess you instead wanted to write -G -d foo=bar?

Kamil

**Comment by melezhik** [comment]
yes, it was typo. But the error is till here. using -G "what every you have here" will result in forceful printing server output into STDOUT, ignoring -o settings.

**Comment by melezhik** [comment]
Ahh, you were RIGHT. Now behavior is expected . Thanks alot.
```
vagrant@Debian-jessie-amd64-netboot:~/projects/swat-github$ curl -G -d 'foo=bar' http://curl.haxx.se/ -o /dev/null | head
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3033  100  3033    0     0    466      0  0:00:06  0:00:06 --:--:--   762
```

**Comment by melezhik** [comment]
I'd live this as issue though. As curl would acts a bit strange when gets called with -G 'foo=bar' and without -d before 'foo=bar', don't you think so? It's not really much mater now for me as I know right syntax, but could be confusing though when doing debug, if/when one missed some `-d` chunks  in curl command call ...

**Comment by bagder** [comment]
This is the downside of curl accepting "anything" as a URL that isn't a recognized option. So yes "curl foo=bar' (which is basically what you tried) will make curl try to use that given string as a URL, and yes that will most likely fail. This is by design though and not a bug.

It could possibly help out by outputting a text suggesting that the URL doesn't start with a scheme and thus it could potentially lead you down the wrong path...

**Comment by melezhik** [comment]
You probably miss my point, curl try host foo=bar and that is FINE , but curl also ignore -o /dev/null option and this not good. Please consider this example again. Uising -o /dev/null I expect to not get output at all, but it here in stdout:


```
vagrant@Debian-jessie-amd64-netboot:~/projects/sph$ curl -s  -G 'foo' http://curl.haxx.se -o /dev/null | head
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
<title>curl and libcurl</title>
<meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
<link rel="stylesheet" type="text/css" href="http://curl.haxx.se/curl.css">
<link rel="shortcut icon" href="http://curl.haxx.se/favicon.ico">
</head>
<body bgcolor="#ffffff" text="#000000">
<div class="main">
 

```

**Comment by bagder** [comment]
Aha now I get it.

But no, it doesn't ignore it. You specify **one output for each given URL** and thus curl consumes that -o for the first URL you gave ('foo=bar') and for the second URL you gave no output option and then it defaults to stdout for that.

**Comment by melezhik** [comment]
Ok, I see.
