### ISSUE TITLE
buildconf reports variable 'curl_SOURCES' is defined but not used

### ISSUE THREAD

**Issue by mback2k** [bagder/curl#577]
```src/Makefile.inc:114: warning: variable 'curl_SOURCES' is defined but no program or
src/Makefile.inc:114: library has 'curl' as canonical name (possible typo)
Makefile.am:151:   'src/Makefile.inc' included from here```

My builds work fine, but still this error message makes me wonder what happened.

**Comment by dfandrich** [comment]
This isn't a new warning, and yes, it's a bit disconcerting. I'm quite sure it
has to do with the name curl_SOURCES being a magic automake name and it being
used in a context where the curl executable is not being built (i.e. the root
Makefile.am). Fixing it involves renaming curl_SOURCES in Makefile.inc to
some other name (maybe CURL_SOURCES would be enough), renaming all the
references to that new name, then adding a curl_SOURCES = $(CURL_SOURCES) to
src/Makefile.am so the magic behaviour is maintained only where it's desired.

**Comment by bagder** [comment]
Yes, that's exactly my understanding of it too.

**Comment by mback2k** [comment]
Thanks, @bagder and @dfandrich. :+1:

**Comment by patrikhson** [comment]
Hi,

Have you seen this? You've got to take a look, that's really cool, read more here <http://tacotuwo.summernite.com/xybln>

Best regards, paf@frobbit.se
