### ISSUE TITLE
Following a 301, 302 or 303 uses POST instead of GET

### ISSUE THREAD

**Issue by andrenarchy** [bagder/curl#578]
If a POST request returns 301, 302 or 303, curl should GET the returned location if `-L` is supplied (according to the docs and [rfc2616](https://tools.ietf.org/html/rfc2616)). However, it issues the second request with POST again:

```
$ curl -X POST -d 'bigdata' -v -L http://httpstat.us/303
[...]
> POST /303 HTTP/1.1
[...]
< HTTP/1.1 303 See Other
[...]
< Location: http://httpstat.us
< 
* Ignoring the response-body
* Connection #0 to host httpstat.us left intact
* Issue another request to this URL: 'http://httpstat.us'
* Disables POST, goes with GET
* Rebuilt URL to: http://httpstat.us/
* Found bundle for host httpstat.us: 0xe326d0
* Re-using existing connection! (#0) with host httpstat.us
* Connected to httpstat.us (23.99.0.12) port 80 (#0)
> POST / HTTP/1.1
[...]
> 
< HTTP/1.1 411 Length Required
[...]
```

**Comment by bagder** [comment]
So why use "-X POST" ?

**Comment by andrenarchy** [comment]
I need to send a POST request to the original URL. The docs say:

> When curl follows a redirect and the request is not a plain GET (for example POST  or  PUT),  it will  do  the  following  request  with  a GET if the HTTP response was 301, 302, or 303. If the response code was any other 3xx code, curl will re-send the following  request  using  the  same unmodified method.

Is there another way to specify that POST should be used?

**Comment by bagder** [comment]
-d already does a POST on its own. The docs for -X explicitly says:

              Normally you don't need this option. All sorts of GET, HEAD, POST and
              PUT requests are rather  invoked  by  using  dedicated  command  line
              options.

In recent curl versions, your command line would show this verbose output:
~~~
Note: Unnecessary use of -X or --request, POST is already inferred.

**Comment by andrenarchy** [comment]
Thanks! Maybe it should be added to the docs that `-X` overrides the behavior of `-L`?

**Comment by bagder** [comment]
You mean like...

              The method string you set with -X will  be  used  for  all  requests,
              which  if  you  for  example  use -L, --location may cause unintended
              side-effects when curl doesn't change request method according to the
              HTTP 30x response codes - and similar.

**Comment by andrenarchy** [comment]
Something like this would help. Thanks!

**Comment by bagder** [comment]
that was a quote from the current version of the man page!

**Comment by andrenarchy** [comment]
Oops, sorry for burning your time with my outdated curl installation!

**Comment by patrikhson** [comment]
Hi,

I'm planning a house renovation and wanted to share some ideas with you, take a look please  <http://tharyguta.infinityemarket.com/xydel>

Very truly yours, paf@frobbit.se

**Comment by patrikhson** [comment]
Hey,

Just take a look at that super cool stuff that I found by chance, you're gonna love it, here is the link <http://thilotrathu.highspeedi.net/xyimsexg>

Warmest regards, paf@frobbit.se

**Comment by hadrienk** [comment]
@bagder so how do you make a PUT/POST request that will follow Location headers and use GET method?

**Comment by jzakrzewski** [comment]
POST: ``` curl -d 'bigdata' -v -L http://httpstat.us/303 ```
PUT: ``` curl -T 'somefile.txt' -v -L http://httpstat.us/303 ```

**Comment by bagder** [comment]
@hadrienk for questions, please use a curl mailing list, we use the issue tracker for bugs
