### ISSUE TITLE
Missing curl_setup.h in /lib/vtls

### ISSUE THREAD

**Issue by primesoftware** [bagder/curl#579]
I'm trying to compile curl with MingGW in Eclipse and I am getting an error about curl_setup.h missing in /lib/vtls. I copied the file and now it looks like other files one level up are not being found. Is this an error or am I missing something here? I need to cross compile with mbedtls support. I've also noticed the ./configure options don't seem to have any effect when using under MSYS.

**Comment by mback2k** [comment]
Are you compiling using MSYS(2) by using ./buildconf, /configure and make (e.g. eclipse autotools project) or a mingw-make project? I can confirm that the first one does work, while the later one requires special build files.

**Comment by bagder** [comment]
curl_setup.h is in /lib only. Builds should be setup to look for include files there even when vtls files are compiled.

**Comment by primesoftware** [comment]
@mback2k I was using MSYS(1). I have upgraded and like MSYS(2) MUCH better especially since I have an Arch box. I've managed to get everything to compile and the curl.exe file works fine when I run it in an MSYS shell. When I try to compile the https.c example with mingw64 from eclipse cdt I get an exe file that gives an error on execution. The error says the following:

```
The program can;t start because libcurl-4.dll is missing from your computer. Try reinstalling the program to fix the problem.
```
Why is it looking for a DLL? I compiled libcurl as a static library and liked it accordingly.

**Comment by primesoftware** [comment]
I'm not getting the following:

```
gcc -ID:/Programming/mbedcurlnet/thirdparty/curl/include -O0 -g3 -Wall -c -fmessage-length=0 -o "src\\main.o" "..\\src\\main.c" 
g++ "-LD:\\Programming\\mbedcurlnet\\thirdparty\\curl\\lib" -static -o HTTPClient.exe "src\\main.o" -lcurl 
src\main.o: In function `main':
D:\Programming\Eclipse\HTTPClient\Debug/../src/main.c:23: undefined reference to `__imp_curl_global_init'
D:\Programming\Eclipse\HTTPClient\Debug/../src/main.c:25: undefined reference to `__imp_curl_easy_init'
D:\Programming\Eclipse\HTTPClient\Debug/../src/main.c:27: undefined reference to `__imp_curl_easy_setopt'
D:\Programming\Eclipse\HTTPClient\Debug/../src/main.c:54: undefined reference to `__imp_curl_easy_perform'
D:\Programming\Eclipse\HTTPClient\Debug/../src/main.c:57: undefined reference to `__imp_curl_easy_strerror'
D:\Programming\Eclipse\HTTPClient\Debug/../src/main.c:61: undefined reference to `__imp_curl_easy_cleanup'
D:\Programming\Eclipse\HTTPClient\Debug/../src/main.c:64: undefined reference to `__imp_curl_global_cleanup'
```
It looks like the static library is missing these function but I do not know why.

**Comment by jay** [comment]
> It looks like the static library is missing these function but I do not know why.

__imp is short for dll import. You see that error because [the curl header assumes you are linking to the DLL](https://github.com/bagder/curl/blob/curl-7_46_0/include/curl/curl.h#L105). For static you need to define `CURL_STATICLIB` before including curl.h. Preferably define it once in some central location like your preprocessor defines (or whatever the eclipse equivalent), that way you don't have to do it in each source file that includes curl.h. I'm sure this information must be documented somewhere, but I can't find where at the moment.

**Comment by jay** [comment]
> I'm sure this information must be documented somewhere, but I can't find where at the moment.

Found it as [Important static libcurl usage note](https://github.com/bagder/curl/blob/curl-7_46_0/docs/INSTALL#L467-L472) in docs/INSTALL.

I think it would be good to add something similar to the tutorial,  that `CURL_STATICLIB` is only in `curl-config --cflags` if a static-only build was installed. What do you guys think of:
https://github.com/jay/curl/compare/master...jay:tutorial-add-static-linking?expand=1
I assumed curl-config --libs is correct if only static-only libcurl is installed, but is --static-libs preferred in that case as well?

**Comment by bagder** [comment]
Can you tell us exactly what you're doing and how it fails? The title is now clearly wrong and I don't understand what we're discussing right now...

**Comment by primesoftware** [comment]
@bagder I think Jay is right. I missed the direction to set CURL_STATICLIB. I'm going to close this thread since I no longer have the original issue.
