### ISSUE TITLE
Let --fail show body if used with -i or -v

### ISSUE THREAD

**Issue by zeisss** [bagder/curl#580]
I regularly use `curl` with simple webapis. For scripting purposed I would want the following things, that are currently not easily achievable with curl:

* Fail with exicode > 0, if any unexpected error code appears
* Show me the body of the response

The first can be achieved with `--fail`, the second with `-i` or `-v`, but both are not really combinable. `--fail` seems to always hide the response body.

**Comment by bagder** [comment]
yes, --fail implies that you don't care for the message body as it won't wait for it and instead bail out as soon as the error is detected. If you want the body, you're better off using the -w option to extract the http response code.
