### ISSUE TITLE
no SSLCERTPASSWD and KEYPASSWD with gnutls binding

### ISSUE THREAD

**Issue by poggenpower** [bagder/curl#587]
Found an issue using pycurl with different libcurl binding.

If pycurl using gnutls as SSL Library, it does not support encrypted keyfiles for use with client authentication. (libcurl-gnutls.so.4)
If I use pycurl with openssl or apple keychain bindig, it works fine.

Tested this with
PycURL/7.19.5 libcurl/7.37.1 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
and
PycURL/7.19.5 libcurl/7.38.0 GnuTLS/3.3.8 zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3

With gnutls you will get an very unspecific error message:
pycurl.error: (35, 'error reading X.509 key or certificate file')

I found that the gnutls_certificate_set_x509_key_file function does not support to the a password, but there is gnutls_certificate_set_x509_key_file2 which does.

May be it is an easy patch to enable encrypted keyfiles.
Sorry, I am not familiar enough with C to write the patch by my own.

Thanks for this great library and your support.

**Comment by jay** [comment]
KEYPASSWD with the GnuTLS backend is supported since 7.45.0, see 6b56901. It looks like your libcurl is too old, you will need to upgrade.
