### ISSUE TITLE
Example needed how to load certificates from memory using mbedtls

### ISSUE THREAD

**Issue by mindej** [bagder/curl#588]
Hello I am implementing an application with libcurl. I have a certificate and private key in memory.
```
const chat *cert = "-----BEGIN CERTIFICATE----- ...."; 
const char *key = "-----BEGIN RSA PRIVATE KEY----- ....";
```
I have found an example how to do so with openSSL http://curl.haxx.se/libcurl/c/usercertinmem.html but according to documentation this approach is for OpenSSL or wolfSSL/CyaSSL only.

**Comment by bagder** [comment]
Sorry, but there's no need to ask for missing functions to get implemented here. I would strongly suggest you instead work on implementing them and submitting a patch or pull-request, or optionally discuss how to do it on the curl-library mailing list to see if others may be able to join in and help.
