### ISSUE TITLE
rstp.c: returns null pointer to writefunction object after rstp request CURL_RTSPREQ_GET_PARAMETER

### ISSUE THREAD

**Issue by zakreuskaya** [bagder/curl#590]
I can't save stream data to file after calling:

curl_easy_setopt(curl, CURLOPT_RTSP_REQUEST, (long)CURL_RTSPREQ_GET_PARAMETER);
Result = curl_easy_perform(curl);

I think, the problem is in function "CURLcode rtp_client_write(struct connectdata *conn, char *ptr, size_t len)", 
line "wrote = writeit(ptr, 1, len, data->set.rtp_out);".
"data->set.rtp_out" is always null, the pointer to the writefunction object is still in "data->set.out".

[my_files.zip](https://github.com/bagder/curl/files/81072/my_files.zip)

**Comment by bagder** [comment]
`data->set.rtp_out` is the value you set with `CURLOPT_INTERLEAVEDATA`.

**Comment by zakreuskaya** [comment]
Thank you very much for your faster answer:) My fault - now it does work properly. Thanks!!!
