### ISSUE TITLE
Curl is trying to use IPv6 when it is not usable

### ISSUE THREAD

**Issue by kamermans** [bagder/curl#593]
On some of my machines (mostly running Ubuntu 14.04) with libcurl 7.35.0 (tested up to libcurl 7.44.0), I am experiencing the following problem.  When getting a DNS response that includes both an IPv4 and IPv6 response (like `example.com`), curl chooses to attempt a IPv6 connection.  When this happens, the process stalls for 5 seconds, fails and then attempts an IPv4 connection, which succeeds.  It's hard to say how often this 5 second delay occurs, but at least 20% of the time, as it is very rare for me to send 5 requests and not see one do this.

Note that IPv6 is not enabled on this internal network, and this happens even if there are no IPv6 addresses on any interfaces.

I know that I can tell curl to only use the IPv4 addresses, but there are dozens of applications on my hundreds of servers that all use curl in some way, so unless this preference is globally configurable, I'll need another strategy.  Currently, I'm considering compiling libcurl without IPv6 support, creating a deb and pushing it to the servers.

I have been looking through the curl source code, but I'm not 100% sure where the decision to follow IPv6 is made.  I see here that the code is using the so-called "Happy Eyeballs" IPv6 strategy to mitigate problems with dual-stack IP setups, but I can't understand where the 5 second delay is coming from before the IPv4 method is chosen.

Here's an example of sending a HEAD request to www.example.com:
```
time curl -sSIvvvv http://www.example.com/ > /dev/null
* Hostname was NOT found in DNS cache
##### There is a 5 second delay here #####
*   Trying 93.184.216.34...
* Connected to www.example.com (93.184.216.34) port 80 (#0)
> HEAD / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: www.example.com
> Accept: */*
>
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Cache-Control: max-age=604800
< Content-Type: text/html
< Date: Fri, 08 Jan 2016 01:19:06 GMT
< Etag: "359670651+gzip"
< Expires: Fri, 15 Jan 2016 01:19:06 GMT
< Last-Modified: Fri, 09 Aug 2013 23:54:35 GMT
* Server ECS (iad/182A) is not blacklisted
< Server: ECS (iad/182A)
< X-Cache: HIT
< x-ec-custom-error: 1
< Content-Length: 1270
<
* Connection #0 to host www.example.com left intact

real    0m5.524s
user    0m0.005s
sys     0m0.005s
```

You can see that it ended up using IPv4 and succeeding.

I can also see this via `strace`.  Here's a fast request:
```
* Hostname was NOT found in DNS cache
socket(PF_INET6, SOCK_DGRAM, IPPROTO_IP) = 3
poll(0, 0, 4)                           = 0 (Timeout)
socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 3
```

and here's a 5-second delay request:
```
* Hostname was NOT found in DNS cache
socket(PF_INET6, SOCK_DGRAM, IPPROTO_IP) = 3
poll(0, 0, 4)                           = 0 (Timeout)
poll(0, 0, 8)                           = 0 (Timeout)
poll(0, 0, 16)                          = 0 (Timeout)
poll(0, 0, 32)                          = 0 (Timeout)
poll(0, 0, 64)                          = 0 (Timeout)
poll(0, 0, 128)                         = 0 (Timeout)
poll(0, 0, 256)                         = 0 (Timeout)
poll(0, 0, 1000)                        = 0 (Timeout)
poll(0, 0, 1000)                        = 0 (Timeout)
poll(0, 0, 1000)                        = 0 (Timeout)
poll(0, 0, 1000)                        = 0 (Timeout)
poll(0, 0, 1000)                        = 0 (Timeout)
socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 3
```

Note also that I tested curl 7.22.0 and it does *not* happen at all in that version.

If anyone can shed some light on this situation it would be much appreciated.

**Comment by jay** [comment]
Please give us the `curl -V` from those you tested. Since you say you tested 7.44 this doesn't sound like a libcurl issue to me, sounds like a DNS issue. I don't see libcurl attempting an IPv6 connection to example.com in your output. I do see DGRAM INET6 so I assume it's trying some DNS. To clarify, when you say the DNS reply contains both IPv4 and IPv6 did you actually see that in Wireshark? Do you not have this problem with any other utility? What happens when you wget http://example.com ?
From what I'm reading on google you may want to look into using `single-request` or `single-request-reopen` in [resolv.conf](http://man7.org/linux/man-pages/man5/resolv.conf.5.html)

> Note that IPv6 is not enabled on this internal network, and this happens even if there are no IPv6 addresses on any interfaces.

I have an Ubuntu 14 LTS x64 box with no IPv6 and I can't reproduce.
~~~
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP 
~~~

**Comment by bagder** [comment]
Yes it very much feels like the name resolving since the pause is before the "Trying 93.184.216.34" line and strace is a datagram. Not sure what curl can or can't do to avoid this hang.

It is interesting that 7.22.0 doesn't show this problem but was it built with the same resolver backend?

**Comment by kamermans** [comment]
Hi, thanks for the quick response!  I spent several hours sifting through the curl code and then into glibc and determined that when curl calls glibc's `getaddrinfo()` function without asking for a IPv4 or IPv6 address (`AF_UNSPEC`), new-ish versions of glibc send two DNS requests in parallel using `sendmmsg()` (one for v4 and one for v6).  Some network equipment in my environment is causing one of those parallel requests to be dropped when transiting between two vlans, which causes the request to timeout after 5 seconds, then get retransmitted, at which point it succeeds.

As you suggested, my old version of of curl was on a system with an old version of glibc, which had an old resolver implementation that did not send the requests in parallel.

After what was perhaps the deepest rabbit hole I've ever followed, it seems this "parallel DNS request" things is known to cause problems in some cases, and can be disabled in Linux by adding this to `/etc/resolv.conf`: `options single-request`.

So in the end, this really has nothing to do with curl :)

Special thanks to @M3hran for the assistance!
