### ISSUE TITLE
CURLOPT_FTP_CREATE_MISSING_DIRS counterpart for HTTP

### ISSUE THREAD

**Issue by Sufi-Al-Hussaini** [bagder/curl#600]
The command line `curl` utility does support a `--create-dirs` option. However, I wasn't able to find any `CREATE_MISSING_DIRS` option for HTTP in libcurl. 

Has this been implemented or is there any plan to implement this?

**Comment by bagder** [comment]
It cannot be implemented for HTTP as HTTP has no such mechanism. And please take ideas and suggestions for new things to the mailing list for discussions, not the issue tracker.
