### ISSUE TITLE
Add option '--smb-create-dirs' for SMB/CIFS-protocol

### ISSUE THREAD

**Issue by umgfoin** [bagder/curl#609]
As of current, curl seems to have no possibility to create a directory-structure when uploading to a smb/cifs-share. 
Therefor, I strongly vote for an option similar to '--ftp-create-dirs" or extending the latter's scope to cover also the SMB-protocol.

bg umgfoin.

**Comment by bagder** [comment]
We don't keep feature requests in the issue tracker, this issue will be closed soon unless there's a need for a discussion or something. If you want a feature, work on it and submit it or take the discussion to the mailing list and see if you can drum up interest from someone else to help you work on it.

**Comment by captain-caveman2k** [comment]
Rather than introduce a new option, and I appreciate the current name will be a little misleading in the short term, but I think it would be better to re-use the --ftp-create-dirs option which is currently used for FTP and SFTP. We can then add an alias for something like --create-remote-dirs. ;-)

**Comment by bagder** [comment]
> We can then add an alias for something like --create-remote-dirs

:+1:
