### ISSUE TITLE
Segmentation fault when making an invalid POST request on 0x0.st

### ISSUE THREAD

**Issue by sbraz** [bagder/curl#625]
Hi,
I haven't been able to reproduce this on any other website but I see a segfault if I do:
`curl -K /dev/null -4vd test http://0x0.st/`:
```
*   Trying 148.251.137.227...
* Connected to 0x0.st (148.251.137.227) port 80 (#0)
> POST / HTTP/1.1
> Host: 0x0.st
> User-Agent: curl/7.47.1-DEV
> Accept: */*
> Content-Length: 4
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 4 out of 4 bytes
< HTTP/1.1 415 UNSUPPORTED MEDIA TYPE
< Server: nginx
< Date: Mon, 01 Feb 2016 12:37:39 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 19
< Connection: keep-alive
< 
Segmentation fault
* Connection #0 to host 0x0.st left intact
```
Reproduced with old and new versions so this should be easy for you to reproduce:
```
curl 7.15.5 (i486-pc-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8c zlib/1.2.3 libidn/0.6.5
curl 7.19.7 (i486-pc-linux-gnu) libcurl/7.19.7 OpenSSL/0.9.8k zlib/1.2.3.3 libidn/1.15
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 OpenSSL/1.0.2f zlib/1.2.8 nghttp2/1.6.0
curl 7.47.1-DEV (x86_64-pc-linux-gnu) libcurl/7.47.0 OpenSSL/1.0.2f zlib/1.2.8 nghttp2/1.6.0
```

**Comment by bagder** [comment]
Ack. Even `curl -d "" http://0x0.st` is enough. I'll dig into it.

**Comment by bagder** [comment]
The "Segmentation fault" text is part of the response body. It is not an actual segmentation fault. No bug here!

**Comment by sbraz** [comment]
Oh my… Sorry about that :/

**Comment by haasn** [comment]
The `* Connection #0 to host 0x0.st left intact` gives it away. When a process segfaults, it segfaults hard :)

**Comment by patrikhson** [comment]
Hey,

I've seen some cool stuff on the web, this is definitely must have of the season! Look at it here <http://thupeshero.madisondylan.com/xyqza>

paf@frobbit.se
